// Code generated by command: go run asm.go -out max.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Max(x []uint8, y []uint8)
// Requires: SSE2
TEXT ·Max(SB), NOSPLIT, $0-48
	MOVQ x_base+0(FP), AX
	MOVQ y_base+24(FP), CX
	MOVQ x_len+8(FP), DX
	XORQ BX, BX

loop:
	// Loop until zero bytes remain.
	CMPQ BX, DX
	JE   done

	// Load.
	MOVUPD (CX)(BX*1), X0
	MOVUPD 16(CX)(BX*1), X1
	MOVUPD 32(CX)(BX*1), X2
	MOVUPD 48(CX)(BX*1), X3
	PMAXUB (AX)(BX*1), X0
	PMAXUB 16(AX)(BX*1), X1
	PMAXUB 32(AX)(BX*1), X2
	PMAXUB 48(AX)(BX*1), X3
	MOVUPD X0, (AX)(BX*1)
	MOVUPD X1, 16(AX)(BX*1)
	MOVUPD X2, 32(AX)(BX*1)
	MOVUPD X3, 48(AX)(BX*1)

	// Advance index.
	ADDQ $0x40, BX
	JMP  loop

done:
	RET
