// Code generated by command: go run asm.go -out max.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Max(x []uint8, y []uint8)
// Requires: AVX, SSE2
TEXT ·Max(SB), NOSPLIT, $0-48
	MOVQ x_base+0(FP), AX
	MOVQ y_base+24(FP), CX
	MOVQ x_len+8(FP), DX
	XORQ BX, BX

loop:
	// Loop until zero bytes remain.
	CMPQ BX, DX
	JE   done

	// Load.
	VMOVDQU (CX)(BX*1), X0
	PMAXUB  (AX)(BX*1), X0
	VMOVDQU X0, (AX)(BX*1)

	// Advance index.
	ADDQ $0x10, BX
	JMP  loop

done:
	RET
