linters:
  enable-all: false
  enable:
    - golint
    - gosimple
    - misspell
    - gocyclo
    - gofmt
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - megacheck
    - deadcode
    - govet
    - errcheck
    - goimports
    - depguard
    - goconst
    - unconvert
    - gocritic

linters-settings:
  depguard:
    list-type: whitelist
    packages:
      - github.com/mmcloughlin/avo
      - golang.org/x/

issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # golint: Annoying issue about not having a comment. The rare codebase has such comments
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
