run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - cyclop
    - errname
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - golint
    - gomnd
    - gosec
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - prealloc
    - scopelint
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  depguard:
    list-type: whitelist
    packages:
      - github.com/mmcloughlin/avo
      - golang.org/x/
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mmcloughlin/avo)
issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # gocritic: https://github.com/go-critic/go-critic/issues/762
    - " with `(len|cap|real|imag)`"
    # We want to allow all caps in certain cases.
    - "ALL_CAPS in Go names"
