// Code generated by command: go run asm.go -out issue193.s -stubs stub.go. DO NOT EDIT.

package issue193

// Destructively Add/Subtract successive pairs
func AddSubPairs(a *[8]int64)

// Destructively Add/Subtract successive pairs
func AddSubPairsNoBase(a *[8]int64)
