// Code generated by command: go run asm.go -out signature.s -stubs stub.go -seed 42 -num 256. DO NOT EDIT.

// func Signature0() (uint32, complex64)
TEXT ·Signature0(SB), $0-12
	RET

// func Signature1() (int16, complex64)
TEXT ·Signature1(SB), $0-12
	RET

// func Signature2(float32, int16) (float32, uint)
TEXT ·Signature2(SB), $0-24
	RET

// func Signature3(uint32, complex128, int64, int8) (uint64, int64)
TEXT ·Signature3(SB), $0-56
	RET

// func Signature4(uint, int16) (uint32, uintptr, int16, uint16)
TEXT ·Signature4(SB), $0-36
	RET

// func Signature5(uintptr, uint32) uint32
TEXT ·Signature5(SB), $0-20
	RET

// func Signature6(string, int64) (int32, bool)
TEXT ·Signature6(SB), $0-29
	RET

// func Signature7(uint16, float32) (uint32, int8, uintptr, int8)
TEXT ·Signature7(SB), $0-25
	RET

// func Signature8() complex128
TEXT ·Signature8(SB), $0-16
	RET

// func Signature9(string) string
TEXT ·Signature9(SB), $0-32
	RET

// func Signature10() (uint, int8)
TEXT ·Signature10(SB), $0-9
	RET

// func Signature11(float32) (bool, bool, int)
TEXT ·Signature11(SB), $0-24
	RET

// func Signature12(string, uintptr, uintptr, float32) (uint16, complex64)
TEXT ·Signature12(SB), $0-52
	RET

// func Signature13(int) (bool, uint32, uint16)
TEXT ·Signature13(SB), $0-18
	RET

// func Signature14(float32, uint16, uint64) (uint16, int8, string)
TEXT ·Signature14(SB), $0-40
	RET

// func Signature15(uint8, uint, bool)
TEXT ·Signature15(SB), $0-17
	RET

// func Signature16(int64, int8, int8, complex64) (complex64, uint)
TEXT ·Signature16(SB), $0-40
	RET

// func Signature17()
TEXT ·Signature17(SB), $0
	RET

// func Signature18(float32, uint64, int16, float32) (uint64, uint, complex64, uintptr)
TEXT ·Signature18(SB), $0-56
	RET

// func Signature19(string, string) (uint8, float32, uint8)
TEXT ·Signature19(SB), $0-41
	RET

// func Signature20() uint8
TEXT ·Signature20(SB), $0-1
	RET

// func Signature21(int8, bool, float32) (complex64, uint64, string)
TEXT ·Signature21(SB), $0-40
	RET

// func Signature22() (uintptr, int32, int8, uint32)
TEXT ·Signature22(SB), $0-20
	RET

// func Signature23(float32, string, int16) (uint64, complex64)
TEXT ·Signature23(SB), $0-48
	RET

// func Signature24(int) uint32
TEXT ·Signature24(SB), $0-12
	RET

// func Signature25(uint16) int16
TEXT ·Signature25(SB), $0-10
	RET

// func Signature26(int32, string, uint, int8) float32
TEXT ·Signature26(SB), $0-44
	RET

// func Signature27() (uintptr, complex128, uint8, complex64)
TEXT ·Signature27(SB), $0-36
	RET

// func Signature28(uint32, int32, int) (uint64, int)
TEXT ·Signature28(SB), $0-32
	RET

// func Signature29(int32, complex64) (string, uintptr, uint64, uint32)
TEXT ·Signature29(SB), $0-52
	RET

// func Signature30() (uint8, int8, complex128)
TEXT ·Signature30(SB), $0-24
	RET

// func Signature31(complex128, uint64, uint16, float64) (uint32, float32)
TEXT ·Signature31(SB), $0-48
	RET

// func Signature32(float64, string, uint16) uint8
TEXT ·Signature32(SB), $0-33
	RET

// func Signature33(int8) (int8, uint32)
TEXT ·Signature33(SB), $0-16
	RET

// func Signature34(int32, uint32) (float64, uint8)
TEXT ·Signature34(SB), $0-17
	RET

// func Signature35(int16, float32, int16, uintptr)
TEXT ·Signature35(SB), $0-24
	RET

// func Signature36(complex64, int8, float32, complex128)
TEXT ·Signature36(SB), $0-32
	RET

// func Signature37(float64, string, int32, complex128) (float64, float32, uint)
TEXT ·Signature37(SB), $0-72
	RET

// func Signature38()
TEXT ·Signature38(SB), $0
	RET

// func Signature39(uint16, uint64, int) uint32
TEXT ·Signature39(SB), $0-28
	RET

// func Signature40(float64, float32) (uint8, uint64, int16)
TEXT ·Signature40(SB), $0-34
	RET

// func Signature41(uint8) (uint32, uint16, uintptr)
TEXT ·Signature41(SB), $0-24
	RET

// func Signature42(string, int8, int32, string)
TEXT ·Signature42(SB), $0-40
	RET

// func Signature43() float32
TEXT ·Signature43(SB), $0-4
	RET

// func Signature44() float64
TEXT ·Signature44(SB), $0-8
	RET

// func Signature45(int64, float64) (int8, float32)
TEXT ·Signature45(SB), $0-24
	RET

// func Signature46(complex128) (string, complex128, complex128)
TEXT ·Signature46(SB), $0-64
	RET

// func Signature47(int32, uint64, uint16, complex128) (complex128, float64, complex128, complex128)
TEXT ·Signature47(SB), $0-96
	RET

// func Signature48(complex128, uint8, uint32, uint64) int16
TEXT ·Signature48(SB), $0-34
	RET

// func Signature49() uintptr
TEXT ·Signature49(SB), $0-8
	RET

// func Signature50(int16, int) (int64, bool, complex64, uint64)
TEXT ·Signature50(SB), $0-48
	RET

// func Signature51(uintptr)
TEXT ·Signature51(SB), $0-8
	RET

// func Signature52() (string, bool, int16)
TEXT ·Signature52(SB), $0-20
	RET

// func Signature53(float64, int8, uintptr, uint16) int8
TEXT ·Signature53(SB), $0-33
	RET

// func Signature54(complex128) (uint, int8, uint64)
TEXT ·Signature54(SB), $0-40
	RET

// func Signature55() (uint8, complex128, int, complex128)
TEXT ·Signature55(SB), $0-48
	RET

// func Signature56(float32, complex64) (uint, int8, string, complex64)
TEXT ·Signature56(SB), $0-56
	RET

// func Signature57(uint16, float64, uint16) (float64, float32, float32, uint16)
TEXT ·Signature57(SB), $0-42
	RET

// func Signature58(uint8, uint, float32) (uint32, int)
TEXT ·Signature58(SB), $0-40
	RET

// func Signature59(int32, int, string)
TEXT ·Signature59(SB), $0-32
	RET

// func Signature60(int16, complex64, int) (float32, int16, int32)
TEXT ·Signature60(SB), $0-36
	RET

// func Signature61(int8, uint64, complex64) (uint, uintptr, uint32)
TEXT ·Signature61(SB), $0-44
	RET

// func Signature62(string, complex128)
TEXT ·Signature62(SB), $0-32
	RET

// func Signature63(uint8, uint8, uint8, float32) (int16, float64)
TEXT ·Signature63(SB), $0-24
	RET

// func Signature64(float32, uint32, int32, string) (float64, uintptr, string, uintptr)
TEXT ·Signature64(SB), $0-72
	RET

// func Signature65(uintptr, int8, uint8, uint8) (int32, float64, complex128, uint8)
TEXT ·Signature65(SB), $0-49
	RET

// func Signature66(uint) (int32, uint, uintptr, float64)
TEXT ·Signature66(SB), $0-40
	RET

// func Signature67() (uint64, bool)
TEXT ·Signature67(SB), $0-9
	RET

// func Signature68(string) (float64, uint8, complex64)
TEXT ·Signature68(SB), $0-36
	RET

// func Signature69(int16)
TEXT ·Signature69(SB), $0-2
	RET

// func Signature70(float64, float64, int64, int16) uintptr
TEXT ·Signature70(SB), $0-40
	RET

// func Signature71(int8, uint, complex64)
TEXT ·Signature71(SB), $0-24
	RET

// func Signature72(int32, uintptr, int64) (uint32, int8)
TEXT ·Signature72(SB), $0-29
	RET

// func Signature73()
TEXT ·Signature73(SB), $0
	RET

// func Signature74(uint8, int32, int64)
TEXT ·Signature74(SB), $0-16
	RET

// func Signature75(uint8, uint16) (uint64, complex64, int16)
TEXT ·Signature75(SB), $0-26
	RET

// func Signature76(uint64, complex64, float32) (int16, int16, int32)
TEXT ·Signature76(SB), $0-32
	RET

// func Signature77(complex128, uint, float32, int) (uint32, float64, complex128, uintptr)
TEXT ·Signature77(SB), $0-80
	RET

// func Signature78() (float32, int16)
TEXT ·Signature78(SB), $0-6
	RET

// func Signature79() (uint32, uint8, uint)
TEXT ·Signature79(SB), $0-16
	RET

// func Signature80() (int, int64)
TEXT ·Signature80(SB), $0-16
	RET

// func Signature81()
TEXT ·Signature81(SB), $0
	RET

// func Signature82(uint8) (uintptr, int8, uint8, uint)
TEXT ·Signature82(SB), $0-32
	RET

// func Signature83() (float64, int8, uint16)
TEXT ·Signature83(SB), $0-12
	RET

// func Signature84(complex64, bool, int8, uint64)
TEXT ·Signature84(SB), $0-24
	RET

// func Signature85(float32) (int32, int, string, int64)
TEXT ·Signature85(SB), $0-48
	RET

// func Signature86(int64, uintptr, bool, float32)
TEXT ·Signature86(SB), $0-24
	RET

// func Signature87(uint64) (uint32, string, string)
TEXT ·Signature87(SB), $0-48
	RET

// func Signature88(uint16, complex64, uint8) (int16, int32)
TEXT ·Signature88(SB), $0-24
	RET

// func Signature89(int32, complex128) (uintptr, int64, uint16)
TEXT ·Signature89(SB), $0-42
	RET

// func Signature90(uintptr, float64, uint32, complex128) (bool, string, uint32)
TEXT ·Signature90(SB), $0-68
	RET

// func Signature91(complex128, bool)
TEXT ·Signature91(SB), $0-17
	RET

// func Signature92() (int32, uint64, float32)
TEXT ·Signature92(SB), $0-20
	RET

// func Signature93(uint16, int32, float32, int) complex64
TEXT ·Signature93(SB), $0-32
	RET

// func Signature94(float32, uint)
TEXT ·Signature94(SB), $0-16
	RET

// func Signature95(int64) (int, int8, uint16, uint16)
TEXT ·Signature95(SB), $0-22
	RET

// func Signature96(string, uint16) (uint64, uint32, uintptr, uint8)
TEXT ·Signature96(SB), $0-49
	RET

// func Signature97(uint16, int8, float64, complex128) (uint16, string, string)
TEXT ·Signature97(SB), $0-72
	RET

// func Signature98(int8) (uint32, int8)
TEXT ·Signature98(SB), $0-13
	RET

// func Signature99(uint64, int64, uint64, int64) bool
TEXT ·Signature99(SB), $0-33
	RET

// func Signature100(uint64, uint16, int64) (uint16, int)
TEXT ·Signature100(SB), $0-40
	RET

// func Signature101(uintptr, uint, bool) (float64, uint32)
TEXT ·Signature101(SB), $0-36
	RET

// func Signature102() int8
TEXT ·Signature102(SB), $0-1
	RET

// func Signature103(uint32, uint32)
TEXT ·Signature103(SB), $0-8
	RET

// func Signature104(string) float32
TEXT ·Signature104(SB), $0-20
	RET

// func Signature105(int, uint) (float32, bool)
TEXT ·Signature105(SB), $0-21
	RET

// func Signature106(complex64, int16, int64)
TEXT ·Signature106(SB), $0-24
	RET

// func Signature107(int32, uintptr) (bool, int64, uint8, int64)
TEXT ·Signature107(SB), $0-48
	RET

// func Signature108(int8) (int8, float32)
TEXT ·Signature108(SB), $0-16
	RET

// func Signature109()
TEXT ·Signature109(SB), $0
	RET

// func Signature110() int32
TEXT ·Signature110(SB), $0-4
	RET

// func Signature111(uint, float32, int32)
TEXT ·Signature111(SB), $0-16
	RET

// func Signature112(int64, float64) (uint8, uintptr, complex128, uint)
TEXT ·Signature112(SB), $0-56
	RET

// func Signature113(float32, uint64) (uint, int8)
TEXT ·Signature113(SB), $0-25
	RET

// func Signature114(uintptr)
TEXT ·Signature114(SB), $0-8
	RET

// func Signature115(uint64, int16) (float64, uint32, uint64)
TEXT ·Signature115(SB), $0-40
	RET

// func Signature116(uintptr) string
TEXT ·Signature116(SB), $0-24
	RET

// func Signature117(string, int8) uint64
TEXT ·Signature117(SB), $0-32
	RET

// func Signature118(int16, float32, uint64, int64) (complex128, uint64, uint32)
TEXT ·Signature118(SB), $0-52
	RET

// func Signature119(complex128, float32, float32, float32)
TEXT ·Signature119(SB), $0-28
	RET

// func Signature120(int32, uint8, int32, int8) uintptr
TEXT ·Signature120(SB), $0-24
	RET

// func Signature121(int, float64, float64, int8) uintptr
TEXT ·Signature121(SB), $0-40
	RET

// func Signature122(uint8, uint8) bool
TEXT ·Signature122(SB), $0-9
	RET

// func Signature123(int64)
TEXT ·Signature123(SB), $0-8
	RET

// func Signature124(int64, complex64) uint16
TEXT ·Signature124(SB), $0-18
	RET

// func Signature125(bool, uint8, int)
TEXT ·Signature125(SB), $0-16
	RET

// func Signature126(uint64, uint64, complex128) (complex128, uint64, int64)
TEXT ·Signature126(SB), $0-64
	RET

// func Signature127(uint16, uintptr, int, int64) (bool, int8, uint8, int)
TEXT ·Signature127(SB), $0-48
	RET

// func Signature128(uint32) (uint64, uint32, uint)
TEXT ·Signature128(SB), $0-32
	RET

// func Signature129(int8, uint8, uint) (float32, uint32, uint, complex64)
TEXT ·Signature129(SB), $0-40
	RET

// func Signature130(complex64, float32, int64, int)
TEXT ·Signature130(SB), $0-32
	RET

// func Signature131(uint64)
TEXT ·Signature131(SB), $0-8
	RET

// func Signature132() (uint, uintptr, float64, int)
TEXT ·Signature132(SB), $0-32
	RET

// func Signature133()
TEXT ·Signature133(SB), $0
	RET

// func Signature134(uint8, int16, bool) int
TEXT ·Signature134(SB), $0-16
	RET

// func Signature135(uint64, int32, uint) complex64
TEXT ·Signature135(SB), $0-32
	RET

// func Signature136(int8, float64, int, int64) (int8, int)
TEXT ·Signature136(SB), $0-48
	RET

// func Signature137(int16, float32) (complex128, bool)
TEXT ·Signature137(SB), $0-25
	RET

// func Signature138(int64, uintptr, complex64, int16) (uintptr, complex128, bool)
TEXT ·Signature138(SB), $0-57
	RET

// func Signature139(int32, float32)
TEXT ·Signature139(SB), $0-8
	RET

// func Signature140(complex64, complex64, bool) float32
TEXT ·Signature140(SB), $0-28
	RET

// func Signature141(int, int16, bool, int64) (uint, uint64, float32, uint64)
TEXT ·Signature141(SB), $0-56
	RET

// func Signature142(bool) (int16, uint32, complex64, uint)
TEXT ·Signature142(SB), $0-32
	RET

// func Signature143()
TEXT ·Signature143(SB), $0
	RET

// func Signature144(float32)
TEXT ·Signature144(SB), $0-4
	RET

// func Signature145(complex128, int, string, uint) (uint16, complex128, string)
TEXT ·Signature145(SB), $0-88
	RET

// func Signature146(int64, complex64) (uint64, uint, uint32, int64)
TEXT ·Signature146(SB), $0-48
	RET

// func Signature147(bool, uint32, uint8, uintptr) (uint64, uintptr)
TEXT ·Signature147(SB), $0-40
	RET

// func Signature148(bool) (int, complex64, uint8)
TEXT ·Signature148(SB), $0-25
	RET

// func Signature149(int64, uint8) string
TEXT ·Signature149(SB), $0-32
	RET

// func Signature150(float64) int64
TEXT ·Signature150(SB), $0-16
	RET

// func Signature151(uint, string, uint, float64) (uint8, complex128, uint32)
TEXT ·Signature151(SB), $0-68
	RET

// func Signature152(int)
TEXT ·Signature152(SB), $0-8
	RET

// func Signature153(uint8) (uint32, uint)
TEXT ·Signature153(SB), $0-24
	RET

// func Signature154(int16, uint64, string, uint32) (uint32, complex128, uint, complex128)
TEXT ·Signature154(SB), $0-88
	RET

// func Signature155(complex128, uintptr, complex128) (uint16, string, uint32)
TEXT ·Signature155(SB), $0-68
	RET

// func Signature156(int16) (uint, uintptr, int64)
TEXT ·Signature156(SB), $0-32
	RET

// func Signature157() (float64, int16, int64, int32)
TEXT ·Signature157(SB), $0-28
	RET

// func Signature158() string
TEXT ·Signature158(SB), $0-16
	RET

// func Signature159(uint32, complex64, int8, float32)
TEXT ·Signature159(SB), $0-20
	RET

// func Signature160(uint64, uint32) (complex128, int64)
TEXT ·Signature160(SB), $0-40
	RET

// func Signature161(uint16, uintptr) float32
TEXT ·Signature161(SB), $0-20
	RET

// func Signature162(bool, int64, int32) (complex128, int64, complex64)
TEXT ·Signature162(SB), $0-56
	RET

// func Signature163(int32, float32) (uint, int32, int16, int16)
TEXT ·Signature163(SB), $0-24
	RET

// func Signature164(uintptr, complex128, bool) (bool, int)
TEXT ·Signature164(SB), $0-48
	RET

// func Signature165(uint8)
TEXT ·Signature165(SB), $0-1
	RET

// func Signature166(float64) (bool, uint32, int32, uintptr)
TEXT ·Signature166(SB), $0-32
	RET

// func Signature167() string
TEXT ·Signature167(SB), $0-16
	RET

// func Signature168(int32)
TEXT ·Signature168(SB), $0-4
	RET

// func Signature169(uint, complex128, uint) (int32, int32)
TEXT ·Signature169(SB), $0-40
	RET

// func Signature170(uint64, int32, uint32, uint32) (uint32, uint32, uint8)
TEXT ·Signature170(SB), $0-33
	RET

// func Signature171(float32, uint32)
TEXT ·Signature171(SB), $0-8
	RET

// func Signature172() (uint, float32, uint8)
TEXT ·Signature172(SB), $0-13
	RET

// func Signature173() (float32, complex64)
TEXT ·Signature173(SB), $0-12
	RET

// func Signature174()
TEXT ·Signature174(SB), $0
	RET

// func Signature175(uint64, bool) (uintptr, uint32)
TEXT ·Signature175(SB), $0-28
	RET

// func Signature176(string) (float64, string)
TEXT ·Signature176(SB), $0-40
	RET

// func Signature177(complex64, uint64)
TEXT ·Signature177(SB), $0-16
	RET

// func Signature178() (uint64, string, uint8)
TEXT ·Signature178(SB), $0-25
	RET

// func Signature179(int8) (uint, uint8, float64, uint)
TEXT ·Signature179(SB), $0-40
	RET

// func Signature180() (uint64, complex64)
TEXT ·Signature180(SB), $0-16
	RET

// func Signature181(uint8)
TEXT ·Signature181(SB), $0-1
	RET

// func Signature182(uint8, uint32, float64) (float64, int64, int64, int)
TEXT ·Signature182(SB), $0-48
	RET

// func Signature183(uint64, uint64, uint8) (uint32, float64, uint32, uint8)
TEXT ·Signature183(SB), $0-45
	RET

// func Signature184(string, complex64, int32) int32
TEXT ·Signature184(SB), $0-36
	RET

// func Signature185(uintptr) uint16
TEXT ·Signature185(SB), $0-10
	RET

// func Signature186(uintptr, complex128, int32, int) int32
TEXT ·Signature186(SB), $0-44
	RET

// func Signature187(uint64, uint8, uint16, int) (int8, float32, int64)
TEXT ·Signature187(SB), $0-40
	RET

// func Signature188()
TEXT ·Signature188(SB), $0
	RET

// func Signature189() (int, uint8, uint32)
TEXT ·Signature189(SB), $0-16
	RET

// func Signature190(uint32, int16) int8
TEXT ·Signature190(SB), $0-9
	RET

// func Signature191(uint16) (uintptr, string, uint32)
TEXT ·Signature191(SB), $0-36
	RET

// func Signature192(uint64, float32)
TEXT ·Signature192(SB), $0-12
	RET

// func Signature193(int64, uint64) (int, float32)
TEXT ·Signature193(SB), $0-28
	RET

// func Signature194(int64, int) string
TEXT ·Signature194(SB), $0-32
	RET

// func Signature195(int, int32) (uint64, int16, string, int8)
TEXT ·Signature195(SB), $0-49
	RET

// func Signature196(complex128, int16, uint64) (float64, uint64, int32, uint16)
TEXT ·Signature196(SB), $0-54
	RET

// func Signature197(int, int64)
TEXT ·Signature197(SB), $0-16
	RET

// func Signature198(uint, string, complex128, bool)
TEXT ·Signature198(SB), $0-41
	RET

// func Signature199(int8) (uint32, int16, float64)
TEXT ·Signature199(SB), $0-24
	RET

// func Signature200(string, uint) (string, complex128, uint8, int32)
TEXT ·Signature200(SB), $0-64
	RET

// func Signature201(float32, uint16) (uint, int, uint64)
TEXT ·Signature201(SB), $0-32
	RET

// func Signature202(uint64, int) (complex128, int8)
TEXT ·Signature202(SB), $0-33
	RET

// func Signature203(uintptr, int, float32) (complex128, bool, uint64, complex128)
TEXT ·Signature203(SB), $0-72
	RET

// func Signature204() (float64, uint32)
TEXT ·Signature204(SB), $0-12
	RET

// func Signature205(int32, bool, int16, uintptr) (float64, float32, uint32, int16)
TEXT ·Signature205(SB), $0-34
	RET

// func Signature206(int, string, float32) (uint, uint)
TEXT ·Signature206(SB), $0-48
	RET

// func Signature207() (uint, int32, int64)
TEXT ·Signature207(SB), $0-24
	RET

// func Signature208(uint8, uint16, uint64, uint) complex128
TEXT ·Signature208(SB), $0-40
	RET

// func Signature209(int) (uint, int, int32, float32)
TEXT ·Signature209(SB), $0-32
	RET

// func Signature210(bool, int64, uint16, float32)
TEXT ·Signature210(SB), $0-24
	RET

// func Signature211(complex128, int8, complex128) (int16, complex128, uintptr)
TEXT ·Signature211(SB), $0-72
	RET

// func Signature212(int16, complex64) (float64, float32, complex64)
TEXT ·Signature212(SB), $0-36
	RET

// func Signature213() (uint, complex64)
TEXT ·Signature213(SB), $0-16
	RET

// func Signature214(uint, int16, string, int64)
TEXT ·Signature214(SB), $0-40
	RET

// func Signature215(float32, int64, uint16) int64
TEXT ·Signature215(SB), $0-32
	RET

// func Signature216(uint, complex64)
TEXT ·Signature216(SB), $0-16
	RET

// func Signature217(string, int64, int8, int32) int64
TEXT ·Signature217(SB), $0-40
	RET

// func Signature218(bool, float32) (uint, int)
TEXT ·Signature218(SB), $0-24
	RET

// func Signature219() int
TEXT ·Signature219(SB), $0-8
	RET

// func Signature220(uint, int32, uint64, float32) (int16, int8, complex64)
TEXT ·Signature220(SB), $0-44
	RET

// func Signature221() complex128
TEXT ·Signature221(SB), $0-16
	RET

// func Signature222(float32, int32, uint) (int8, uintptr)
TEXT ·Signature222(SB), $0-32
	RET

// func Signature223(int) (int16, int8)
TEXT ·Signature223(SB), $0-11
	RET

// func Signature224(string) (uintptr, float64)
TEXT ·Signature224(SB), $0-32
	RET

// func Signature225(uintptr, uint8, int64, uint) (uint64, uintptr, bool)
TEXT ·Signature225(SB), $0-49
	RET

// func Signature226(bool, bool, uintptr, int64)
TEXT ·Signature226(SB), $0-24
	RET

// func Signature227(int, float64) (string, string, bool, complex64)
TEXT ·Signature227(SB), $0-60
	RET

// func Signature228(int16, int16, int64)
TEXT ·Signature228(SB), $0-16
	RET

// func Signature229(uint64) int
TEXT ·Signature229(SB), $0-16
	RET

// func Signature230(int64, string, float64) (uint16, float32)
TEXT ·Signature230(SB), $0-40
	RET

// func Signature231(complex128, complex128) (uintptr, float32, complex64, int32)
TEXT ·Signature231(SB), $0-56
	RET

// func Signature232() (uint16, uint16, complex128)
TEXT ·Signature232(SB), $0-24
	RET

// func Signature233(uint16, uint32, float64) (int64, complex128)
TEXT ·Signature233(SB), $0-40
	RET

// func Signature234() bool
TEXT ·Signature234(SB), $0-1
	RET

// func Signature235(uintptr) complex64
TEXT ·Signature235(SB), $0-16
	RET

// func Signature236(uintptr, float64) (uint8, uint64)
TEXT ·Signature236(SB), $0-32
	RET

// func Signature237()
TEXT ·Signature237(SB), $0
	RET

// func Signature238(int32, uint32) (string, int8)
TEXT ·Signature238(SB), $0-25
	RET

// func Signature239(int64, uint8) (uint64, float64, uint, uint8)
TEXT ·Signature239(SB), $0-41
	RET

// func Signature240(float32) (uint32, float32)
TEXT ·Signature240(SB), $0-16
	RET

// func Signature241(float32, uint8, int8, float32) uintptr
TEXT ·Signature241(SB), $0-24
	RET

// func Signature242(complex128, int, string, uint8)
TEXT ·Signature242(SB), $0-41
	RET

// func Signature243(uint, uint) (int16, uintptr)
TEXT ·Signature243(SB), $0-32
	RET

// func Signature244() bool
TEXT ·Signature244(SB), $0-1
	RET

// func Signature245(int32) int32
TEXT ·Signature245(SB), $0-12
	RET

// func Signature246() (complex128, int8)
TEXT ·Signature246(SB), $0-17
	RET

// func Signature247(float64, string, complex128) uintptr
TEXT ·Signature247(SB), $0-48
	RET

// func Signature248() uint16
TEXT ·Signature248(SB), $0-2
	RET

// func Signature249(float64, int64, float64, uint8)
TEXT ·Signature249(SB), $0-25
	RET

// func Signature250()
TEXT ·Signature250(SB), $0
	RET

// func Signature251(int8, uintptr) (int32, uint32)
TEXT ·Signature251(SB), $0-24
	RET

// func Signature252(uintptr, string, int, complex128) (uint, uint, uint32, int32)
TEXT ·Signature252(SB), $0-72
	RET

// func Signature253(int, string, string) (uint8, uintptr)
TEXT ·Signature253(SB), $0-56
	RET

// func Signature254(string) (float32, complex128)
TEXT ·Signature254(SB), $0-40
	RET

// func Signature255(complex128, int16) complex128
TEXT ·Signature255(SB), $0-40
	RET
