// Code generated by command: go run asm.go -out signature.s -stubs stub.go -seed 42 -num 256. DO NOT EDIT.

package signature

func Signature0() (uint32, complex64)

func Signature1() (int16, complex64)

func Signature2(float32, int16) (float32, uint)

func Signature3(uint32, complex128, int64, int8) (uint64, int64)

func Signature4(uint, int16) (uint32, uintptr, int16, uint16)

func Signature5(uintptr, uint32) uint32

func Signature6(string, int64) (int32, bool)

func Signature7(uint16, float32) (uint32, int8, uintptr, int8)

func Signature8() complex128

func Signature9(string) string

func Signature10() (uint, int8)

func Signature11(float32) (bool, bool, int)

func Signature12(string, uintptr, uintptr, float32) (uint16, complex64)

func Signature13(int) (bool, uint32, uint16)

func Signature14(float32, uint16, uint64) (uint16, int8, string)

func Signature15(uint8, uint, bool)

func Signature16(int64, int8, int8, complex64) (complex64, uint)

func Signature17()

func Signature18(float32, uint64, int16, float32) (uint64, uint, complex64, uintptr)

func Signature19(string, string) (uint8, float32, uint8)

func Signature20() uint8

func Signature21(int8, bool, float32) (complex64, uint64, string)

func Signature22() (uintptr, int32, int8, uint32)

func Signature23(float32, string, int16) (uint64, complex64)

func Signature24(int) uint32

func Signature25(uint16) int16

func Signature26(int32, string, uint, int8) float32

func Signature27() (uintptr, complex128, uint8, complex64)

func Signature28(uint32, int32, int) (uint64, int)

func Signature29(int32, complex64) (string, uintptr, uint64, uint32)

func Signature30() (uint8, int8, complex128)

func Signature31(complex128, uint64, uint16, float64) (uint32, float32)

func Signature32(float64, string, uint16) uint8

func Signature33(int8) (int8, uint32)

func Signature34(int32, uint32) (float64, uint8)

func Signature35(int16, float32, int16, uintptr)

func Signature36(complex64, int8, float32, complex128)

func Signature37(float64, string, int32, complex128) (float64, float32, uint)

func Signature38()

func Signature39(uint16, uint64, int) uint32

func Signature40(float64, float32) (uint8, uint64, int16)

func Signature41(uint8) (uint32, uint16, uintptr)

func Signature42(string, int8, int32, string)

func Signature43() float32

func Signature44() float64

func Signature45(int64, float64) (int8, float32)

func Signature46(complex128) (string, complex128, complex128)

func Signature47(int32, uint64, uint16, complex128) (complex128, float64, complex128, complex128)

func Signature48(complex128, uint8, uint32, uint64) int16

func Signature49() uintptr

func Signature50(int16, int) (int64, bool, complex64, uint64)

func Signature51(uintptr)

func Signature52() (string, bool, int16)

func Signature53(float64, int8, uintptr, uint16) int8

func Signature54(complex128) (uint, int8, uint64)

func Signature55() (uint8, complex128, int, complex128)

func Signature56(float32, complex64) (uint, int8, string, complex64)

func Signature57(uint16, float64, uint16) (float64, float32, float32, uint16)

func Signature58(uint8, uint, float32) (uint32, int)

func Signature59(int32, int, string)

func Signature60(int16, complex64, int) (float32, int16, int32)

func Signature61(int8, uint64, complex64) (uint, uintptr, uint32)

func Signature62(string, complex128)

func Signature63(uint8, uint8, uint8, float32) (int16, float64)

func Signature64(float32, uint32, int32, string) (float64, uintptr, string, uintptr)

func Signature65(uintptr, int8, uint8, uint8) (int32, float64, complex128, uint8)

func Signature66(uint) (int32, uint, uintptr, float64)

func Signature67() (uint64, bool)

func Signature68(string) (float64, uint8, complex64)

func Signature69(int16)

func Signature70(float64, float64, int64, int16) uintptr

func Signature71(int8, uint, complex64)

func Signature72(int32, uintptr, int64) (uint32, int8)

func Signature73()

func Signature74(uint8, int32, int64)

func Signature75(uint8, uint16) (uint64, complex64, int16)

func Signature76(uint64, complex64, float32) (int16, int16, int32)

func Signature77(complex128, uint, float32, int) (uint32, float64, complex128, uintptr)

func Signature78() (float32, int16)

func Signature79() (uint32, uint8, uint)

func Signature80() (int, int64)

func Signature81()

func Signature82(uint8) (uintptr, int8, uint8, uint)

func Signature83() (float64, int8, uint16)

func Signature84(complex64, bool, int8, uint64)

func Signature85(float32) (int32, int, string, int64)

func Signature86(int64, uintptr, bool, float32)

func Signature87(uint64) (uint32, string, string)

func Signature88(uint16, complex64, uint8) (int16, int32)

func Signature89(int32, complex128) (uintptr, int64, uint16)

func Signature90(uintptr, float64, uint32, complex128) (bool, string, uint32)

func Signature91(complex128, bool)

func Signature92() (int32, uint64, float32)

func Signature93(uint16, int32, float32, int) complex64

func Signature94(float32, uint)

func Signature95(int64) (int, int8, uint16, uint16)

func Signature96(string, uint16) (uint64, uint32, uintptr, uint8)

func Signature97(uint16, int8, float64, complex128) (uint16, string, string)

func Signature98(int8) (uint32, int8)

func Signature99(uint64, int64, uint64, int64) bool

func Signature100(uint64, uint16, int64) (uint16, int)

func Signature101(uintptr, uint, bool) (float64, uint32)

func Signature102() int8

func Signature103(uint32, uint32)

func Signature104(string) float32

func Signature105(int, uint) (float32, bool)

func Signature106(complex64, int16, int64)

func Signature107(int32, uintptr) (bool, int64, uint8, int64)

func Signature108(int8) (int8, float32)

func Signature109()

func Signature110() int32

func Signature111(uint, float32, int32)

func Signature112(int64, float64) (uint8, uintptr, complex128, uint)

func Signature113(float32, uint64) (uint, int8)

func Signature114(uintptr)

func Signature115(uint64, int16) (float64, uint32, uint64)

func Signature116(uintptr) string

func Signature117(string, int8) uint64

func Signature118(int16, float32, uint64, int64) (complex128, uint64, uint32)

func Signature119(complex128, float32, float32, float32)

func Signature120(int32, uint8, int32, int8) uintptr

func Signature121(int, float64, float64, int8) uintptr

func Signature122(uint8, uint8) bool

func Signature123(int64)

func Signature124(int64, complex64) uint16

func Signature125(bool, uint8, int)

func Signature126(uint64, uint64, complex128) (complex128, uint64, int64)

func Signature127(uint16, uintptr, int, int64) (bool, int8, uint8, int)

func Signature128(uint32) (uint64, uint32, uint)

func Signature129(int8, uint8, uint) (float32, uint32, uint, complex64)

func Signature130(complex64, float32, int64, int)

func Signature131(uint64)

func Signature132() (uint, uintptr, float64, int)

func Signature133()

func Signature134(uint8, int16, bool) int

func Signature135(uint64, int32, uint) complex64

func Signature136(int8, float64, int, int64) (int8, int)

func Signature137(int16, float32) (complex128, bool)

func Signature138(int64, uintptr, complex64, int16) (uintptr, complex128, bool)

func Signature139(int32, float32)

func Signature140(complex64, complex64, bool) float32

func Signature141(int, int16, bool, int64) (uint, uint64, float32, uint64)

func Signature142(bool) (int16, uint32, complex64, uint)

func Signature143()

func Signature144(float32)

func Signature145(complex128, int, string, uint) (uint16, complex128, string)

func Signature146(int64, complex64) (uint64, uint, uint32, int64)

func Signature147(bool, uint32, uint8, uintptr) (uint64, uintptr)

func Signature148(bool) (int, complex64, uint8)

func Signature149(int64, uint8) string

func Signature150(float64) int64

func Signature151(uint, string, uint, float64) (uint8, complex128, uint32)

func Signature152(int)

func Signature153(uint8) (uint32, uint)

func Signature154(int16, uint64, string, uint32) (uint32, complex128, uint, complex128)

func Signature155(complex128, uintptr, complex128) (uint16, string, uint32)

func Signature156(int16) (uint, uintptr, int64)

func Signature157() (float64, int16, int64, int32)

func Signature158() string

func Signature159(uint32, complex64, int8, float32)

func Signature160(uint64, uint32) (complex128, int64)

func Signature161(uint16, uintptr) float32

func Signature162(bool, int64, int32) (complex128, int64, complex64)

func Signature163(int32, float32) (uint, int32, int16, int16)

func Signature164(uintptr, complex128, bool) (bool, int)

func Signature165(uint8)

func Signature166(float64) (bool, uint32, int32, uintptr)

func Signature167() string

func Signature168(int32)

func Signature169(uint, complex128, uint) (int32, int32)

func Signature170(uint64, int32, uint32, uint32) (uint32, uint32, uint8)

func Signature171(float32, uint32)

func Signature172() (uint, float32, uint8)

func Signature173() (float32, complex64)

func Signature174()

func Signature175(uint64, bool) (uintptr, uint32)

func Signature176(string) (float64, string)

func Signature177(complex64, uint64)

func Signature178() (uint64, string, uint8)

func Signature179(int8) (uint, uint8, float64, uint)

func Signature180() (uint64, complex64)

func Signature181(uint8)

func Signature182(uint8, uint32, float64) (float64, int64, int64, int)

func Signature183(uint64, uint64, uint8) (uint32, float64, uint32, uint8)

func Signature184(string, complex64, int32) int32

func Signature185(uintptr) uint16

func Signature186(uintptr, complex128, int32, int) int32

func Signature187(uint64, uint8, uint16, int) (int8, float32, int64)

func Signature188()

func Signature189() (int, uint8, uint32)

func Signature190(uint32, int16) int8

func Signature191(uint16) (uintptr, string, uint32)

func Signature192(uint64, float32)

func Signature193(int64, uint64) (int, float32)

func Signature194(int64, int) string

func Signature195(int, int32) (uint64, int16, string, int8)

func Signature196(complex128, int16, uint64) (float64, uint64, int32, uint16)

func Signature197(int, int64)

func Signature198(uint, string, complex128, bool)

func Signature199(int8) (uint32, int16, float64)

func Signature200(string, uint) (string, complex128, uint8, int32)

func Signature201(float32, uint16) (uint, int, uint64)

func Signature202(uint64, int) (complex128, int8)

func Signature203(uintptr, int, float32) (complex128, bool, uint64, complex128)

func Signature204() (float64, uint32)

func Signature205(int32, bool, int16, uintptr) (float64, float32, uint32, int16)

func Signature206(int, string, float32) (uint, uint)

func Signature207() (uint, int32, int64)

func Signature208(uint8, uint16, uint64, uint) complex128

func Signature209(int) (uint, int, int32, float32)

func Signature210(bool, int64, uint16, float32)

func Signature211(complex128, int8, complex128) (int16, complex128, uintptr)

func Signature212(int16, complex64) (float64, float32, complex64)

func Signature213() (uint, complex64)

func Signature214(uint, int16, string, int64)

func Signature215(float32, int64, uint16) int64

func Signature216(uint, complex64)

func Signature217(string, int64, int8, int32) int64

func Signature218(bool, float32) (uint, int)

func Signature219() int

func Signature220(uint, int32, uint64, float32) (int16, int8, complex64)

func Signature221() complex128

func Signature222(float32, int32, uint) (int8, uintptr)

func Signature223(int) (int16, int8)

func Signature224(string) (uintptr, float64)

func Signature225(uintptr, uint8, int64, uint) (uint64, uintptr, bool)

func Signature226(bool, bool, uintptr, int64)

func Signature227(int, float64) (string, string, bool, complex64)

func Signature228(int16, int16, int64)

func Signature229(uint64) int

func Signature230(int64, string, float64) (uint16, float32)

func Signature231(complex128, complex128) (uintptr, float32, complex64, int32)

func Signature232() (uint16, uint16, complex128)

func Signature233(uint16, uint32, float64) (int64, complex128)

func Signature234() bool

func Signature235(uintptr) complex64

func Signature236(uintptr, float64) (uint8, uint64)

func Signature237()

func Signature238(int32, uint32) (string, int8)

func Signature239(int64, uint8) (uint64, float64, uint, uint8)

func Signature240(float32) (uint32, float32)

func Signature241(float32, uint8, int8, float32) uintptr

func Signature242(complex128, int, string, uint8)

func Signature243(uint, uint) (int16, uintptr)

func Signature244() bool

func Signature245(int32) int32

func Signature246() (complex128, int8)

func Signature247(float64, string, complex128) uintptr

func Signature248() uint16

func Signature249(float64, int64, float64, uint8)

func Signature250()

func Signature251(int8, uintptr) (int32, uint32)

func Signature252(uintptr, string, int, complex128) (uint, uint, uint32, int32)

func Signature253(int, string, string) (uint8, uintptr)

func Signature254(string) (float32, complex128)

func Signature255(complex128, int16) complex128
