// Code generated by command: go run asm.go -out zeroing.s -stubs stub.go. DO NOT EDIT.

package zeroing

// Zeroing computes the sum 1+2+...+10 in 8 lanes of 512-bit register.
func Zeroing(out *[8]uint64)
