// Code generated by command: go run asm.go -out complex.s -stubs stub.go. DO NOT EDIT.

package complex

func Real(x complex128) float64

func Imag(x complex128) float64

func Norm(x complex128) float64
