// Code generated by command: go run asm.go -out issue387.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

DATA f32<>+0(SB)/4, $(0)
DATA f32<>+4(SB)/4, $(1)
DATA f32<>+8(SB)/4, $(2)
DATA f32<>+12(SB)/4, $(3)
DATA f32<>+16(SB)/4, $(4)
DATA f32<>+20(SB)/4, $(5)
DATA f32<>+24(SB)/4, $(6)
DATA f32<>+28(SB)/4, $(7)
DATA f32<>+32(SB)/4, $(8)
DATA f32<>+36(SB)/4, $(9)
GLOBL f32<>(SB), RODATA|NOPTR, $40

// func Float32At(i int) float32
// Requires: SSE
TEXT ·Float32At(SB), NOSPLIT, $0-12
	MOVQ  i+0(FP), AX
	LEAQ  f32<>+0(SB), CX
	MOVSS (CX)(AX*4), X0
	MOVSS X0, ret+8(FP)
	RET
