// Code generated by command: go run asm.go -out issue387.s -stubs stub.go. DO NOT EDIT.

package issue387

// Float32 indexes into an array of single-precision integral floats.
func Float32(i int) float32

// Float64 indexes into an array of double-precision integral floats.
func Float64(i int) float64
