name: create-pull-request
description: Create Pull Request
inputs:
  title:
    description: "Pull request title"
    required: true
  branch:
    description: "Branch name"
    required: true
  body:
    description: "Body of the pull request"
    required: true
runs:
  using: composite
  steps:
    - name: Generate Bot Token
      uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe # v1.5.2
      id: bot
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e # v4.0.2
      with:
        token: ${{ steps.bot.outputs.token }}
        commit-message: ${{ inputs.title }}
        branch: ${{ inputs.branch }}
        base: master
        delete-branch: true
        draft: true
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
