name: create-pull-request
description: Create Pull Request
inputs:
  bot:
    description: "Bot username"
    required: false
    default: "cadobot[bot]"
  app_id:
    description: "Bot App ID"
    required: true
  app_private_key:
    description: "Bot App Private Key"
    required: true
  title:
    description: "Pull request title"
    required: true
  branch:
    description: "Branch name"
    required: true
  body:
    description: "Body of the pull request"
    required: true
  draft:
    description: "Create draft pull request"
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Get Bot User
      id: bot
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
      with:
        script: |
          const res = await github.rest.users.getByUsername({username: '${{ inputs.bot }}'});
          for (const [key, value] of Object.entries(res.data)) {
            core.setOutput(key, value)
          }
    - name: Generate App Token
      uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1.7.0
      id: app
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_private_key }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@331d02c7e2104af23ad5974d4d5cbc58a3e6dc77 # v4.2.2
      with:
        token: ${{ steps.app.outputs.token }}
        commit-message: ${{ inputs.title }}
        author: "${{ steps.bot.outputs.login }} <${{ steps.bot.outputs.id }}+${{ steps.bot.outputs.login }}@users.noreply.github.com>"
        branch: ${{ inputs.branch }}
        base: master
        delete-branch: true
        draft: ${{ inputs.draft }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
