// Code generated by command: go run asm.go -out returns.s -stubs stub.go. DO NOT EDIT.

package returns

func Interval(start uint64, size uint64) (uint64, uint64)

func Butterfly(x0 float64, x1 float64) (y0 float64, y1 float64)

func Septuple(byte) [7]byte

func CriticalLine(t float64) complex128

func NewStruct(w uint16, p [2]float64, q uint64) Struct
