#!/bin/bash -ex

# We intend that the x86 arch sub-repo should be the only dependency.
go get -v -u golang.org/x/arch/x86/...

# Install golangci-lint
golangci_lint_version='v1.12.3'
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin ${golangci_lint_version}
