#!/bin/bash -ex

# Complex documentation generation with docgen.
go install ./internal/cmd/docgen

docgen -type readme -output README.md

# Process simple file embeddings with embedmd.
find . -name '*.md' | xargs embedmd -w
