#!/bin/bash -ex

repo="github.com/mmcloughlin/avo"

# Files to apply formatting to. Exclude stadtx since some of it was imported
# from the original repo.
files=$(find . -name '*.go' -not -path '*/stadtx/*')

# Remove blank lines in import blocks. This will force formatting to group
# imports correctly.
sed -i '' '/^import (/,/)/ { /^$$/ d; }' ${files}

# gofumports is goimports with stricter formatting.
gofumports -w -local ${repo} ${files}
