#!/bin/bash -ex

# Ensure the repository is clean after code generation.
./script/generate
test -z "$(git status --porcelain)"

# And it's still clean after asmfmt.
# Note: we want to confirm we agree with asmfmt without actually depending on it.
find . -name '*.s' | xargs asmfmt -w
test -z "$(git status --porcelain)"

# Run suite of golangci-lint checks.
golangci-lint run
