package printer_test

import (
	"testing"

	"github.com/mmcloughlin/avo/build"
	"github.com/mmcloughlin/avo/printer"
	"github.com/mmcloughlin/avo/reg"
)

func TestBasic(t *testing.T) {
	ctx := build.NewContext()
	ctx.Function("add")
	ctx.SignatureExpr("func(x, y uint64) uint64")
	x := ctx.Load(ctx.Param("x"), reg.RAX)
	y := ctx.Load(ctx.Param("y"), reg.R9)
	ctx.ADDQ(x, y)
	ctx.Store(y, ctx.ReturnIndex(0))
	ctx.RET()

	AssertPrintsLines(t, ctx, printer.NewGoAsm, []string{
		"// Code generated by avo. DO NOT EDIT.",
		"",
		"#include \"textflag.h\"",
		"",
		"// func add(x uint64, y uint64) uint64",
		"TEXT ·add(SB), 0, $0-24",
		"\tMOVQ\tx(FP), AX",
		"\tMOVQ\ty+8(FP), R9",
		"\tADDQ\tAX, R9",
		"\tMOVQ\tR9, ret+16(FP)",
		"\tRET",
		"",
	})
}

func TestTextSize(t *testing.T) {
	ctx := build.NewContext()

	ctx.Function("noargs")
	ctx.SignatureExpr("func()")
	ctx.AllocLocal(16)
	ctx.RET()

	ctx.Function("withargs")
	ctx.SignatureExpr("func(x, y uint64) uint64")
	ctx.RET()

	AssertPrintsLines(t, ctx, printer.NewGoAsm, []string{
		"// Code generated by avo. DO NOT EDIT.",
		"",
		"#include \"textflag.h\"",
		"",
		"// func noargs()",
		"TEXT ·noargs(SB), 0, $16", // expect only the frame size
		"\tRET",
		"",
		"// func withargs(x uint64, y uint64) uint64",
		"TEXT ·withargs(SB), 0, $0-24", // expect both frame size and argument size
		"\tRET",
		"",
	})
}
