// Code generated by command: go run asm.go -out issue419.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Sum(n uint64) uint64
TEXT ·Sum(SB), NOSPLIT, $0-16
	PCALIGN $0x0400
	MOVQ    n+0(FP), AX
	XORQ    CX, CX
	TESTQ   AX, AX
	JZ      done
	PCALIGN $0x20

loop:
	DECQ  AX
	ADDQ  AX, CX
	TESTQ AX, AX
	JNZ   loop

done:
	MOVQ CX, ret+8(FP)
	RET

// func SumAddr() uintptr
TEXT ·SumAddr(SB), NOSPLIT, $0-8
	LEAQ ·Sum+0(SB), AX
	MOVQ AX, ret+0(FP)
	RET
