// Code generated by command: go run asm.go -out issue419.s -stubs stub.go. DO NOT EDIT.

package issue419

// Sum returns the sum of integers in [0, n), using a loop aligned with PCALIGN.
func Sum(n uint64) uint64

// SumAddr returns the address of the assembly implementation of Sum.
func SumAddr() uintptr
