// Code generated by command: go run asm.go -out issue83.s -stubs stubs.go. DO NOT EDIT.

#include "textflag.h"

// func Issue83(cond uint64, a uint64, b uint64) uint64
TEXT ·Issue83(SB), NOSPLIT, $0-32
	MOVQ cond+0(FP), AX
	MOVQ a+8(FP), CX
	MOVQ b+16(FP), DX
	CMPQ AX, $0x00
	JE   false
	MOVQ CX, ret+24(FP)
	RET
	JMP  false
	ADDQ AX, AX

false:
	MOVQ DX, ret+24(FP)
	RET
