// Code generated by command: go run asm.go -out mem.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func ByteFromSlice(b []byte, offset int) byte
TEXT ·ByteFromSlice(SB), NOSPLIT, $0-33
	MOVQ b_base+0(FP), AX
	MOVQ offset+24(FP), CX
	MOVB (AX)(CX*1), AL
	MOVB AL, ret+32(FP)
	RET

// func ByteFromString(s string, offset int) byte
TEXT ·ByteFromString(SB), NOSPLIT, $0-25
	MOVQ s_base+0(FP), AX
	MOVQ offset+16(FP), CX
	MOVB (AX)(CX*1), AL
	MOVB AL, ret+24(FP)
	RET

// func Int32FromSlice(i []int32, offset int) int32
TEXT ·Int32FromSlice(SB), NOSPLIT, $0-36
	MOVQ i_base+0(FP), AX
	MOVQ offset+24(FP), CX
	MOVL (AX)(CX*4), AX
	MOVL AX, ret+32(FP)
	RET

// func Int64FromSlice(i []int64, offset int) int64
TEXT ·Int64FromSlice(SB), NOSPLIT, $0-40
	MOVQ i_base+0(FP), AX
	MOVQ offset+24(FP), CX
	MOVQ (AX)(CX*8), AX
	MOVQ AX, ret+32(FP)
	RET
