// Code generated by command: go run asm.go -out mem.s -stubs stub.go. DO NOT EDIT.

package mem

// Takes a slice of bytes and an offset and returns the byte at that offset, performs no bounds checking - very unsafe
func ByteFromSlice(b []byte, offset int) byte

// Takes a string and an offset and returns the byte at that offset, performs no bounds checking - very unsafe
func ByteFromString(s string, offset int) byte

// Takes a slice of int32 and an offset and returns the int32 at that offset, performs no bounds checking - very unsafe
func Int32FromSlice(i []int32, offset int) int32

// Takes a slice of int64 and an offset and returns the int64 at that offset, performs no bounds checking - very unsafe
func Int64FromSlice(i []int64, offset int) int64
