// Code generated by command: go run asm.go -out issue145.s -stubs stub.go. DO NOT EDIT.

package issue145

// Shuffle performs in-place shuffling of data according to a shuffle control mask.
func Shuffle(mask []byte, data []byte) [4]uint32
