// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.
// EXPERIMENTAL arm64 output lowered from an amd64 avo program.

//go:build arm64

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R0, R1, R1
	MOVD R1, ret+16(FP)
	RET

// func Sub(x uint64, y uint64) uint64
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUB  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Neg(x uint64) uint64
TEXT ·Neg(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	NEG  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AndOrXor(x uint64, y uint64) uint64
TEXT ·AndOrXor(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD R0, R2
	AND  R1, R2, R2
	ORR  R1, R0, R0
	EOR  R0, R2, R2
	MOVD R2, ret+16(FP)
	RET

// func ShlCL(x uint64, n uint64) uint64
TEXT ·ShlCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShrCL(x uint64, n uint64) uint64
TEXT ·ShrCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func RolCL(x uint64, n uint64) uint64
TEXT ·RolCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	NEG  R1, R16
	ROR  R16, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ZeroExt32(x uint64) uint64
TEXT ·ZeroExt32(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVWU R0, R1
	ADD   R0, R1, R1
	MOVD  R1, ret+8(FP)
	RET

// func HighByte(x uint64) uint64
TEXT ·HighByte(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	UBFX  $8, R0, $8, R16
	BFI   $0, R16, $8, R0
	MOVBU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func ShiftExtractByte64Lo(x uint64) uint64
TEXT ·ShiftExtractByte64Lo(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	UBFX $0, R0, $8, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func ShiftExtractByte64Mid(x uint64) uint64
TEXT ·ShiftExtractByte64Mid(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	UBFX $8, R0, $8, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func ShiftExtractByte64Hi(x uint64) uint64
TEXT ·ShiftExtractByte64Hi(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	UBFX $56, R0, $8, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func ShiftExtractByte32(x uint64) uint64
TEXT ·ShiftExtractByte32(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	UBFX $16, R0, $8, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func LoadIdx(p *[8]uint64, i uint64) uint64
TEXT ·LoadIdx(SB), NOSPLIT, $0-24
	MOVD p+0(FP), R0
	MOVD i+8(FP), R1
	MOVD (R0)(R1<<3), R0
	MOVD R0, ret+16(FP)
	RET

// func Copy16(dst *[16]byte, src *[16]byte)
// Requires: SSE
TEXT ·Copy16(SB), NOSPLIT, $0-16
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	FMOVQ (R1), F0
	FMOVQ F0, (R0)
	RET

// func Prefetch(p *[64]uint64, i uint64) uint64
// Requires: MMX+
TEXT ·Prefetch(SB), NOSPLIT, $0-24
	MOVD p+0(FP), R0
	MOVD i+8(FP), R1
	AND  $0x3f, R1, R1
	PRFM (R0), PLDL1KEEP
	PRFM 64(R0), PLDL2KEEP
	PRFM 32760(R0), PLDL3KEEP
	PRFM 4(R0), PLDL1STRM
	ADD  $260, R0, R15
	PRFM (R15), PLDL1KEEP
	ADD  $32768, R0, R15
	PRFM (R15), PLDL1KEEP
	ADD  $-64, R0, R15
	PRFM (R15), PLDL1KEEP
	ADD  R1<<3, R0, R15
	PRFM (R15), PLDL1KEEP
	ADD  R1, R0, R15
	PRFM 8(R15), PLDL1KEEP
	TST  R1, R1
	MOVD (R0)(R1<<3), R2
	ADD  R1<<3, R0, R15
	PRFM 64(R15), PLDL1KEEP
	BEQ  prefetch_done
	ADD  $0x01, R2, R2

prefetch_done:
	MOVD R2, ret+16(FP)
	RET

// func LessS(a uint64, b uint64) uint64
TEXT ·LessS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BLT  LessS_yes
	MOVD $0x0000000000000000, R0
	JMP  LessS_end

LessS_yes:
	MOVD $0x0000000000000001, R0

LessS_end:
	MOVD R0, ret+16(FP)
	RET

// func GreaterEqS(a uint64, b uint64) uint64
TEXT ·GreaterEqS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BGE  GreaterEqS_yes
	MOVD $0x0000000000000000, R0
	JMP  GreaterEqS_end

GreaterEqS_yes:
	MOVD $0x0000000000000001, R0

GreaterEqS_end:
	MOVD R0, ret+16(FP)
	RET

// func LessU(a uint64, b uint64) uint64
TEXT ·LessU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BLO  LessU_yes
	MOVD $0x0000000000000000, R0
	JMP  LessU_end

LessU_yes:
	MOVD $0x0000000000000001, R0

LessU_end:
	MOVD R0, ret+16(FP)
	RET

// func AboveU(a uint64, b uint64) uint64
TEXT ·AboveU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BHI  AboveU_yes
	MOVD $0x0000000000000000, R0
	JMP  AboveU_end

AboveU_yes:
	MOVD $0x0000000000000001, R0

AboveU_end:
	MOVD R0, ret+16(FP)
	RET

// func Equal(a uint64, b uint64) uint64
TEXT ·Equal(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BEQ  Equal_yes
	MOVD $0x0000000000000000, R0
	JMP  Equal_end

Equal_yes:
	MOVD $0x0000000000000001, R0

Equal_end:
	MOVD R0, ret+16(FP)
	RET

// func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelectEq(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL EQ, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SubGapEq(x uint64, y uint64) uint64
TEXT ·SubGapEq(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUBS R1, R0, R0
	MOVD $0x0000000000000000, R0
	BEQ  SubGapEq_yes
	JMP  SubGapEq_end

SubGapEq_yes:
	MOVD $0x0000000000000001, R0

SubGapEq_end:
	MOVD R0, ret+16(FP)
	RET

// func DecGapZero(x uint64, y uint64) uint64
TEXT ·DecGapZero(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	SUBS $1, R0, R0
	MOVD $0x0000000000000000, R0
	BEQ  DecGapZero_yes
	JMP  DecGapZero_end

DecGapZero_yes:
	MOVD $0x0000000000000001, R0

DecGapZero_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32Eq(a uint64, b uint64) uint64
TEXT ·CmpL32Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BEQ  CmpL32Eq_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32Eq_end

CmpL32Eq_yes:
	MOVD $0x0000000000000001, R0

CmpL32Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32LessS(a uint64, b uint64) uint64
TEXT ·CmpL32LessS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BLT  CmpL32LessS_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32LessS_end

CmpL32LessS_yes:
	MOVD $0x0000000000000001, R0

CmpL32LessS_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32LessU(a uint64, b uint64) uint64
TEXT ·CmpL32LessU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BLO  CmpL32LessU_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32LessU_end

CmpL32LessU_yes:
	MOVD $0x0000000000000001, R0

CmpL32LessU_end:
	MOVD R0, ret+16(FP)
	RET

// func TestL32(a uint64, m uint64) uint64
TEXT ·TestL32(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD m+8(FP), R1
	TSTW R1, R0
	BEQ  TestL32_zero
	MOVD $0x0000000000000000, R0
	JMP  TestL32_end

TestL32_zero:
	MOVD $0x0000000000000001, R0

TestL32_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpW16Eq(a uint64, b uint64) uint64
TEXT ·CmpW16Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	AND  $0xffff, R1, R16
	AND  $0xffff, R0, R15
	CMP  R16, R15
	BEQ  CmpW16Eq_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpW16Eq_end

CmpW16Eq_yes:
	MOVD $0x0000000000000001, R0

CmpW16Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpB8Ne(a uint64, b uint64) uint64
TEXT ·CmpB8Ne(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	AND  $0xff, R1, R16
	AND  $0xff, R0, R15
	CMP  R16, R15
	BNE  CmpB8Ne_diff
	MOVD $0x0000000000000000, R0
	JMP  CmpB8Ne_end

CmpB8Ne_diff:
	MOVD $0x0000000000000001, R0

CmpB8Ne_end:
	MOVD R0, ret+16(FP)
	RET

// func TestW16Eq(a uint64, m uint64) uint64
TEXT ·TestW16Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD m+8(FP), R1
	AND  $0xffff, R1, R16
	AND  $0xffff, R0, R15
	TST  R16, R15
	BEQ  TestW16Eq_zero
	MOVD $0x0000000000000000, R0
	JMP  TestW16Eq_end

TestW16Eq_zero:
	MOVD $0x0000000000000001, R0

TestW16Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func IMul2(x uint64, y uint64) uint64
TEXT ·IMul2(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MUL  R0, R1, R1
	MOVD R1, ret+16(FP)
	RET

// func IMul3(x uint64) uint64
TEXT ·IMul3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $-1640531535, R16
	MUL  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func MulWide(x uint64, y uint64) (lo uint64, hi uint64)
TEXT ·MulWide(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R5
	UMULH R5, R0, R2
	MUL   R5, R0, R0
	MOVD  R0, lo+16(FP)
	MOVD  R2, hi+24(FP)
	RET

// func IMulWide(x int64, y int64) (lo uint64, hi uint64)
TEXT ·IMulWide(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R5
	SMULH R5, R0, R2
	MUL   R5, R0, R0
	MOVD  R0, lo+16(FP)
	MOVD  R2, hi+24(FP)
	RET

// func MulX(x uint64, y uint64) (lo uint64, hi uint64)
// Requires: BMI2
TEXT ·MulX(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R5
	MOVD  y+8(FP), R2
	MUL   R5, R2, R16
	UMULH R5, R2, R3
	MOVD  R16, R0
	MOVD  R0, lo+16(FP)
	MOVD  R3, hi+24(FP)
	RET

// func ShlX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShlX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShrX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShrX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func SarX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·SarX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	ASR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func RorX(x uint64) uint64
// Requires: BMI2
TEXT ·RorX(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ROR  $56, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bzhi(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·Bzhi(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	MOVD $1, R16
	LSL  R1, R16, R16
	SUB  $1, R16, R16
	AND  R16, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Bextr88(x uint64) uint64
// Requires: BMI
TEXT ·Bextr88(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000808, R1
	UBFX $8, R0, $8, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr4_12(x uint64) uint64
// Requires: BMI
TEXT ·Bextr4_12(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000c04, R1
	UBFX $4, R0, $12, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr56_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr56_8(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000838, R1
	LSR  $56, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr8_56(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_56(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00003808, R1
	LSR  $8, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr8_60(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_60(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00003c08, R1
	LSR  $8, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr0_0(x uint64) uint64
// Requires: BMI
TEXT ·Bextr0_0(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000000, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr70_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr70_8(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000846, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConst13(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst13(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000d, R1
	AND  $8191, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConst0(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst0(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000000, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConst64(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst64(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000040, R1
	MOVD R0, ret+8(FP)
	RET

// func ShlXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShlXConst9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000009, R1
	LSL  $9, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShrXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShrXConst9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000009, R1
	LSR  $9, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SetGe(a uint64, b uint64) uint64
TEXT ·SetGe(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	CSET GE, R2
	MOVD R2, ret+16(FP)
	RET

// func AdcAccum(x uint64, acc uint64) uint64
TEXT ·AdcAccum(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  acc+8(FP), R1
	CMP   $0x04, R0
	CSINC HS, R1, R1, R16
	BFI   $0, R16, $8, R1
	MOVD  R1, ret+16(FP)
	RET

// func BswapL(x uint64) uint64
TEXT ·BswapL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	REVW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AddByte(x uint64, y uint64) uint64
TEXT ·AddByte(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R0, R1, R15
	BFI  $0, R15, $8, R1
	MOVD R1, ret+16(FP)
	RET

// func MovbHighDst(x uint64, y uint64) uint64
TEXT ·MovbHighDst(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R1
	MOVD y+8(FP), R0
	BFI  $8, R1, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func MovbLowPreserve(x uint64, y uint64) uint64
TEXT ·MovbLowPreserve(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R1
	MOVD y+8(FP), R0
	UBFX $8, R1, $8, R16
	BFI  $0, R16, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLtS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LT, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLeS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LE, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGtS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL GT, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGeS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL GE, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLsU(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LS, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelMi(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelMi(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL MI, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelPl(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelPl(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL PL, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SxL(x uint64) uint64
TEXT ·SxL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SxB(x uint64) uint64
TEXT ·SxB(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVB R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SxBL(x uint64) uint64
TEXT ·SxBL(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVB  R0, R0
	MOVWU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func SxWL(x uint64) uint64
TEXT ·SxWL(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVH  R0, R0
	MOVWU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func NegL(x uint64) uint64
TEXT ·NegL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	NEGW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func NotL(x uint64) uint64
TEXT ·NotL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MVNW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func NotQ(x uint64) uint64
TEXT ·NotQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MVN  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func RolL7(x uint64) uint64
TEXT ·RolL7(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RORW $25, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func RorQ9(x uint64) uint64
TEXT ·RorQ9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ROR  $0x09, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func RorL9(x uint64) uint64
TEXT ·RorL9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RORW $0x09, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BtrQ5(x uint64) uint64
TEXT ·BtrQ5(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000000000005, R1
	MOVD $1, R16
	LSL  R1, R16, R16
	BIC  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BtcQ5(x uint64) uint64
TEXT ·BtcQ5(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000000000005, R1
	MOVD $1, R16
	LSL  R1, R16, R16
	EOR  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func PopcntQ(x uint64) uint64
// Requires: POPCNT
TEXT ·PopcntQ(SB), NOSPLIT, $0-16
	MOVD    x+0(FP), R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVD    R0, ret+8(FP)
	RET

// func SarQ3(x uint64) uint64
TEXT ·SarQ3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ASR  $0x03, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SarL3(x uint64) uint64
TEXT ·SarL3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ASRW $0x03, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func IncL(x uint64) uint64
TEXT ·IncL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ADDW $1, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShlB2(x uint64) uint64
TEXT ·ShlB2(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	MOVD R0, ret+8(FP)
	RET

// func BsfQ(x uint64) uint64
TEXT ·BsfQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RBIT R0, R1
	CLZ  R1, R1
	MOVD R1, ret+8(FP)
	RET

// func TzcntQ(x uint64) uint64
// Requires: BMI
TEXT ·TzcntQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RBIT R0, R0
	CLZ  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AddL(x uint64, y uint64) uint64
TEXT ·AddL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func SubL(x uint64, y uint64) uint64
TEXT ·SubL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUBW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func AndL(x uint64, y uint64) uint64
TEXT ·AndL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ANDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func OrL(x uint64, y uint64) uint64
TEXT ·OrL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ORRW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ImulL(x uint64, y uint64) uint64
TEXT ·ImulL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MULW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func XchgQ(x uint64, y uint64) uint64
TEXT ·XchgQ(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD R1, R1
	MOVD R0, R16
	MOVD R1, R0
	MOVD R16, R1
	MOVD R0, ret+16(FP)
	RET

// func LeaL(x uint64, y uint64) uint64
TEXT ·LeaL(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ADD   R1<<2, R0, R0
	ADD   $7, R0, R0
	MOVWU R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func VecZero(dst *[16]byte)
// Requires: SSE2
TEXT ·VecZero(SB), NOSPLIT, $0-8
	MOVD  dst+0(FP), R0
	VEOR  V0.B16, V0.B16, V0.B16
	FMOVQ F0, (R0)
	RET

// func VecCopyIdx(dst *[32]byte, src *[32]byte, i uint64)
// Requires: SSE2
TEXT ·VecCopyIdx(SB), NOSPLIT, $0-24
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	MOVD  i+16(FP), R2
	ADD   R2, R1, R15
	FMOVQ (R15), F0
	ADD   R2, R0, R15
	FMOVQ F0, (R15)
	RET

// func VecCopy(dst *[32]byte, src *[32]byte)
// Requires: SSE2
TEXT ·VecCopy(SB), NOSPLIT, $0-16
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	FMOVQ 16(R1), F0
	FMOVQ F0, 16(R0)
	RET

// func Prop0(x uint64, y uint64) uint64
TEXT ·Prop0(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ASR   $0x05, R0, R0
	RORW  $27, R0, R0
	ANDW  R1, R0, R0
	MOVD  $0, R0
	ASR   $0x05, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	MOVD  $0, R0
	NEG   R0, R0
	ORR   R1, R0, R0
	MOVHU R0, R0
	AND   R1, R0, R0
	MOVWU R1, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop1(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop1(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MOVD    $0, R0
	ROR     $51, R0, R0
	CMP     R1, R0
	CSEL    EQ, R1, R0, R0
	EOR     R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	MVN     R0, R0
	ROR     $51, R0, R0
	MOVW    R0, R0
	AND     R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop2(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop2(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	NEG   R0, R0
	ADDW  R1, R0, R0
	MOVWU R1, R0
	MOVHU R0, R0
	ROR   $51, R0, R0
	SUBW  R1, R0, R0
	MUL   R1, R0, R0
	BFI   $0, R1, $8, R0
	REVW  R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop3(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop3(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVW  R0, R0
	SUB   R1, R0, R0
	CMP   R1, R0
	CSET  LT, R16
	BFI   $0, R16, $8, R0
	BFI   $0, R1, $8, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	LSL   $0x03, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MOVHU R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	MULW  R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop4(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop4(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	RORW  $27, R0, R0
	RORW  $27, R0, R0
	MUL   R1, R0, R0
	ADD   R1, R0, R0
	MOVHU R0, R0
	MOVD  $0, R0
	MVN   R0, R0
	LSL   $0x03, R0, R0
	ADD   R1, R0, R0
	LSR   $0x07, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ADD   R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop5(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop5(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ANDW R1, R0, R0
	LSR  $0x07, R0, R0
	LSLW $0x09, R0, R0
	LSLW $0x09, R0, R0
	MOVD $0, R0
	MULW R1, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	SUBW R1, R0, R0
	RBIT R0, R0
	CLZ  R0, R0
	LSLW $0x09, R0, R0
	ROR  $51, R0, R0
	BFI  $0, R1, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop6(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop6(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVWU R1, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ORR   R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	MULW  R1, R0, R0
	MOVW  R0, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	ASR   $0x05, R0, R0
	LSR   $0x07, R0, R0
	MOVW  R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop7(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop7(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	LSLW $0x09, R0, R0
	AND  R1, R0, R0
	MULW R1, R0, R0
	ADDW R1, R0, R0
	ADD  R1, R0, R0
	SUBW R1, R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	NEG  R0, R0
	ROR  $51, R0, R0
	ADD  R1, R0, R0
	RORW $27, R0, R0
	MOVW R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop8(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop8(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ADDW    R1, R0, R0
	RORW    $27, R0, R0
	ADDW    R1, R0, R0
	NEG     R0, R0
	BFI     $0, R1, $8, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	LSLW    $0x09, R0, R0
	MUL     R1, R0, R0
	AND     R1, R0, R0
	MOVD    $0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop9(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop9(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ADDW    R1, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	MULW    R1, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	RORW    $27, R0, R0
	SUB     R1, R0, R0
	NEG     R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ADDW    R1, R0, R0
	MULW    R1, R0, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MVN     R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop10(x uint64, y uint64) uint64
// Requires: BMI, POPCNT
TEXT ·Prop10(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MUL     R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ADDW    R1, R0, R0
	RBIT    R0, R0
	CLZ     R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	ROR     $51, R0, R0
	SUBW    R1, R0, R0
	MUL     R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MUL     R1, R0, R0
	MVN     R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop11(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop11(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ANDW    R1, R0, R0
	MVN     R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	RORW    $27, R0, R0
	ADDW    R1, R0, R0
	RORW    $27, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	ASR     $0x05, R0, R0
	BFI     $0, R1, $8, R0
	MULW    R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVD    R0, ret+16(FP)
	RET

// func MemProp0(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp0(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	MOVD  R1, R3
	AND   $0x00000003, R3, R3
	MOVD  (R2)(R3<<3), R16
	CMP   R16, R0
	CSEL  LO, R1, R0, R0
	ROR   $53, R0, R0
	MOVHU 2(R2), R0
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R3, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	MOVD  (R2)(R3<<3), R16
	EOR   R16, R0, R0
	MOVD  R0, (R2)(R3<<3)
	ROR   $53, R0, R0
	MOVD  (R2)(R3<<3), R16
	ADD   R16, R0, R0
	MOVD  R0, (R2)(R3<<3)
	SUB   R1, R0, R0
	MOVD  (R2)(R3<<3), R16
	ADD   R16, R0, R0
	MOVD  R0, ret+24(FP)
	RET

// func MemProp1(x uint64, y uint64, p *[8]uint64) uint64
TEXT ·MemProp1(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	MOVD  R1, R3
	AND   $0x00000003, R3, R3
	MOVD  16(R2), R16
	MUL   R16, R0, R0
	ADD   R3<<3, R2, R0
	ADD   $8, R0, R0
	SUB   R2, R0, R0
	SUB   R1, R0, R0
	MOVD  R0, (R2)(R3<<3)
	MOVD  16(R2), R16
	MUL   R16, R0, R0
	MOVD  R0, (R2)(R3<<3)
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R3, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R3, R3
	AND   $0x00000003, R3, R3
	MOVW  8(R2), R0
	ROR   $53, R0, R0
	MOVD  R0, ret+24(FP)
	RET

// func MemProp2(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp2(SB), NOSPLIT, $0-32
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD p+16(FP), R2
	MOVD R1, R3
	AND  $0x00000003, R3, R3
	MOVD 16(R2), R16
	MUL  R16, R0, R0
	MOVW 8(R2), R0
	ROR  $53, R0, R0
	MOVD R0, (R2)(R3<<3)
	ADD  R3<<3, R2, R15
	MOVD 8(R15), R16
	ADD  R16, R0, R0
	ROR  $53, R0, R0
	MOVD R0, (R2)(R3<<3)
	MOVD (R2)(R3<<3), R16
	CMP  R16, R0
	CSEL LO, R1, R0, R0
	SUB  R1, R0, R0
	ADD  R1, R0, R0
	MOVD R0, ret+24(FP)
	RET

// func MemProp3(x uint64, y uint64, p *[8]uint64) uint64
TEXT ·MemProp3(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	AND   $0x00000003, R1, R1
	MOVW  R0, 24(R2)
	MOVWU 4(R2), R0
	MOVBU 1(R2), R16
	BFI   $0, R16, $8, R0
	MOVBU 1(R2), R16
	BFI   $0, R16, $8, R0
	MOVW  R0, 24(R2)
	MOVHU 2(R2), R0
	MOVWU 4(R2), R0
	ROR   $53, R0, R0
	ADD   R1<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R1, R1
	AND   $0x00000003, R1, R1
	ADD   R1<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	MOVW  8(R2), R0
	MOVD  R0, ret+24(FP)
	RET

// func MemProp4(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp4(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	MOVD  R1, R3
	AND   $0x00000003, R3, R3
	MOVD  (R2)(R3<<3), R16
	EOR   R16, R0, R0
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R3, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   R1, R0, R0
	MOVD  (R2)(R3<<3), R16
	ADD   R16, R0, R0
	MOVBU 1(R2), R16
	BFI   $0, R16, $8, R0
	MOVHU 2(R2), R0
	MOVD  (R2)(R3<<3), R16
	CMP   R16, R0
	CSEL  LO, R1, R0, R0
	MOVD  (R2)(R3<<3), R16
	ADD   R16, R0, R0
	MOVWU 4(R2), R0
	SUB   R1, R0, R0
	MOVD  R0, ret+24(FP)
	RET

// func MemProp5(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp5(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	MOVD  R1, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R3, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	MOVD  16(R2), R16
	MUL   R16, R0, R0
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	MOVD  16(R2), R16
	MUL   R16, R0, R0
	MOVD  R0, (R2)(R3<<3)
	ADD   R3<<3, R2, R0
	ADD   $8, R0, R0
	SUB   R2, R0, R0
	ADD   R1, R0, R0
	MOVD  16(R2), R16
	MUL   R16, R0, R0
	MOVWU 4(R2), R0
	MOVD  (R2)(R3<<3), R16
	CMP   R16, R0
	CSEL  LO, R1, R0, R0
	MOVD  R0, ret+24(FP)
	RET

// func MemProp6(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp6(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	MOVD  R1, R3
	AND   $0x00000003, R3, R3
	ADD   R1, R0, R0
	MOVD  (R2)(R3<<3), R16
	CMP   R16, R0
	CSEL  LO, R1, R0, R0
	SUB   R1, R0, R0
	ROR   $53, R0, R0
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	ADD   $1, R3, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	SUB   R1, R0, R0
	MOVHU 2(R2), R0
	MOVD  (R2)(R3<<3), R16
	CMP   R16, R0
	CSEL  LO, R1, R0, R0
	ROR   $53, R0, R0
	ADD   R3<<3, R2, R0
	ADD   $8, R0, R0
	SUB   R2, R0, R0
	MOVD  R0, ret+24(FP)
	RET

// func MemProp7(x uint64, y uint64, p *[8]uint64) uint64
TEXT ·MemProp7(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVD  p+16(FP), R2
	MOVD  R1, R3
	AND   $0x00000003, R3, R3
	ADD   R3<<3, R2, R0
	ADD   $8, R0, R0
	SUB   R2, R0, R0
	MOVD  R0, (R2)(R3<<3)
	MOVD  (R2)(R3<<3), R16
	ADD   R16, R0, R0
	MOVWU 4(R2), R0
	MOVD  R0, (R2)(R3<<3)
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	MOVHU 2(R2), R0
	ADD   R3<<3, R2, R15
	MOVWU (R15), R16
	ADDW  R16, R0, R0
	MOVW  R0, 24(R2)
	ADD   R1, R0, R0
	MOVD  R0, ret+24(FP)
	RET

// func BtBranch(x uint64) uint64
TEXT ·BtBranch(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TBNZ $0x00, R0, BtBranch_taken
	MOVD $0x0000000000000014, R0
	JMP  BtBranch_end

BtBranch_taken:
	MOVD $0x000000000000000a, R0

BtBranch_end:
	MOVD R0, ret+8(FP)
	RET

// func BtBranchHigh(x uint64) uint64
TEXT ·BtBranchHigh(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TBNZ $0x03, R0, BtBranchHigh_taken
	MOVD $0x0000000000000014, R0
	JMP  BtBranchHigh_end

BtBranchHigh_taken:
	MOVD $0x000000000000000a, R0

BtBranchHigh_end:
	MOVD R0, ret+8(FP)
	RET

// func BtBranchClear(x uint64) uint64
TEXT ·BtBranchClear(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TBZ  $0x00, R0, BtBranchClear_taken
	MOVD $0x0000000000000014, R0
	JMP  BtBranchClear_end

BtBranchClear_taken:
	MOVD $0x000000000000000a, R0

BtBranchClear_end:
	MOVD R0, ret+8(FP)
	RET

// func BtBranchClearHigh(x uint64) uint64
TEXT ·BtBranchClearHigh(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TBZ  $0x03, R0, BtBranchClearHigh_taken
	MOVD $0x0000000000000014, R0
	JMP  BtBranchClearHigh_end

BtBranchClearHigh_taken:
	MOVD $0x000000000000000a, R0

BtBranchClearHigh_end:
	MOVD R0, ret+8(FP)
	RET

// func MovwzxL(p *[4]uint16, i uint64) uint64
TEXT ·MovwzxL(SB), NOSPLIT, $0-24
	MOVD  p+0(FP), R0
	MOVD  i+8(FP), R1
	MOVD  $0xffffffffffffffff, R2
	MOVHU (R0)(R1<<1), R2
	MOVD  R2, ret+16(FP)
	RET

// func MovbzxHigh(x uint64) uint64
TEXT ·MovbzxHigh(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	UBFX $8, R0, $8, R3
	MOVD R3, ret+8(FP)
	RET

// func CmovL32(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·CmovL32(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	CMP   R0, R0
	CSELW NE, R0, R1, R1
	MOVD  R1, ret+16(FP)
	RET

// func BextrMem(p *[4]uint64, i uint64, ctrl uint64) uint64
// Requires: BMI
TEXT ·BextrMem(SB), NOSPLIT, $0-32
	MOVD p+0(FP), R0
	MOVD i+8(FP), R1
	MOVD ctrl+16(FP), R2
	ADD  R1<<3, R0, R15
	MOVD (R15), R16
	UBFX $0, R2, $8, R15
	LSR  R15, R16, R16
	UBFX $8, R2, $8, R15
	MOVD $1, R0
	LSL  R15, R0, R0
	SUB  $1, R0, R0
	AND  R0, R16, R0
	MOVD R0, ret+24(FP)
	RET

// func XorSelfEq(x uint64) uint64
TEXT ·XorSelfEq(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0, R0
	TST  R0, R0
	BEQ  xorself_yes
	MOVD $0x0000000000000000, R0
	JMP  xorself_end

xorself_yes:
	MOVD $0x0000000000000001, R0

xorself_end:
	MOVD R0, ret+8(FP)
	RET

// func MovLNegImm() uint64
TEXT ·MovLNegImm(SB), NOSPLIT, $0-8
	MOVD $0xffffffff, R0
	MOVD R0, ret+0(FP)
	RET

// func IncLMem(p *[2]uint32)
TEXT ·IncLMem(SB), NOSPLIT, $0-8
	MOVD  p+0(FP), R0
	MOVWU (R0), R16
	ADDW  $1, R16, R16
	MOVW  R16, (R0)
	RET

// func DecLMem(p *[2]uint32)
TEXT ·DecLMem(SB), NOSPLIT, $0-8
	MOVD  p+0(FP), R0
	MOVWU (R0), R16
	SUBW  $1, R16, R16
	MOVW  R16, (R0)
	RET

// func IncQMem(p *[2]uint64)
TEXT ·IncQMem(SB), NOSPLIT, $0-8
	MOVD p+0(FP), R0
	MOVD (R0), R16
	ADD  $1, R16, R16
	MOVD R16, (R0)
	RET

// func CmpBHigh(x uint64) uint64
TEXT ·CmpBHigh(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x02, R16
	AND  $0xff, R16, R16
	UBFX $8, R0, $8, R15
	CMP  R16, R15
	CSET EQ, R3
	MOVD R3, ret+8(FP)
	RET

// func MovWLoad(x uint64, p *uint16) uint64
TEXT ·MovWLoad(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  p+8(FP), R1
	MOVHU (R1), R16
	BFI   $0, R16, $16, R0
	MOVD  R0, ret+16(FP)
	RET

// func MulXAlias(x uint64, y uint64) uint64
// Requires: BMI2
TEXT ·MulXAlias(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R5
	MOVD  y+8(FP), R2
	MUL   R5, R2, R16
	UMULH R5, R2, R0
	MOVD  R0, ret+16(FP)
	RET

// func TestQImm(x uint64, y uint64) uint64
TEXT ·TestQImm(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	TST  $0x00000010, R0
	CSET EQ, R1
	MOVD R1, ret+16(FP)
	RET

// func FlagsAcrossTransparent(a uint64, b uint64) uint64
TEXT ·FlagsAcrossTransparent(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	MVN  R0, R0
	REVW R0, R0
	MOVD R0, R16
	MOVD R2, R0
	MOVD R16, R2
	BEQ  fat_eq
	MOVD $0x0000000000000000, R2
	JMP  fat_end

fat_eq:
	MOVD $0x0000000000000001, R2

fat_end:
	MOVD R2, ret+16(FP)
	RET

// func XorlSign(x uint64, y uint64) uint64
TEXT ·XorlSign(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	EORW R1, R0, R0
	TSTW R0, R0
	BMI  xorlsign_neg
	MOVD $0x0000000000000000, R0
	JMP  xorlsign_end

xorlsign_neg:
	MOVD $0x0000000000000001, R0

xorlsign_end:
	MOVD R0, ret+16(FP)
	RET

// func XorlMem(p *[2]uint32, v uint64)
TEXT ·XorlMem(SB), NOSPLIT, $0-16
	MOVD  p+0(FP), R0
	MOVD  v+8(FP), R1
	MOVWU (R0), R16
	EORW  R1, R16, R16
	MOVW  R16, (R0)
	RET

// func BzhiConst256(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst256(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000000000100, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConstNeg(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConstNeg(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $-1, R1
	MOVD R0, ret+8(FP)
	RET

// func AndQBit31(x uint64) uint64
TEXT ·AndQBit31(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	AND  $-2147483648, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AddQBit31(x uint64) uint64
TEXT ·AddQBit31(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ADD  $-2147483648, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func OrQBit31(x uint64) uint64
TEXT ·OrQBit31(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ORR  $-32, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func CmpQBit31(x uint64) uint64
TEXT ·CmpQBit31(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	CMN  $2147483648, R0
	BEQ  cqb_eq
	MOVD $0x0000000000000000, R0
	JMP  cqb_end

cqb_eq:
	MOVD $0x0000000000000001, R0

cqb_end:
	MOVD R0, ret+8(FP)
	RET

// func TestQBit31(x uint64) uint64
TEXT ·TestQBit31(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TST  $-2147483648, R0
	CSET EQ, R1
	MOVD R1, ret+8(FP)
	RET

// func MovQBit31Mem(p *uint64)
TEXT ·MovQBit31Mem(SB), NOSPLIT, $0-8
	MOVD p+0(FP), R0
	MOVD $-2147483648, R16
	MOVD R16, (R0)
	RET

// func MovQBit31Reg() uint64
TEXT ·MovQBit31Reg(SB), NOSPLIT, $0-8
	MOVD $0x80000000, R0
	MOVD R0, ret+0(FP)
	RET

// func CmpLIntMin(x uint64) uint64
TEXT ·CmpLIntMin(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0, R1
	CMPW $-2147483648, R0
	CSET LT, R2
	ORR  R2, R1, R1
	CMPW $-2147483648, R0
	CSET GE, R2
	LSL  $0x01, R2, R2
	ORR  R2, R1, R1
	CMPW $-2147483648, R0
	CSET GT, R2
	LSL  $0x02, R2, R2
	ORR  R2, R1, R1
	CMPW $-2147483648, R0
	CSET LE, R2
	LSL  $0x03, R2, R2
	ORR  R2, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func ShrQ64(x uint64) uint64
TEXT ·ShrQ64(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSR  $0, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShrQ65(x uint64) uint64
TEXT ·ShrQ65(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSR  $1, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShlQ64(x uint64) uint64
TEXT ·ShlQ64(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSL  $0, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShrL32(x uint64) uint64
TEXT ·ShrL32(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSRW $0, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func IncQ(x uint64) uint64
TEXT ·IncQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ADD  $1, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func DecL(x uint64) uint64
TEXT ·DecL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	SUBW $1, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShrL5(x uint64) uint64
TEXT ·ShrL5(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSRW $0x05, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SxWQ(x uint64) uint64
TEXT ·SxWQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVH R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BsrQ(x uint64) uint64
TEXT ·BsrQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	CLZ  R0, R16
	MOVD $63, R1
	SUB  R16, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func BtsQ5(x uint64) uint64
TEXT ·BtsQ5(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000000000005, R1
	MOVD $1, R16
	LSL  R1, R16, R16
	ORR  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ZxLQ(p *uint64) uint64
TEXT ·ZxLQ(SB), NOSPLIT, $0-16
	MOVD  p+0(FP), R0
	MOVWU (R0), R0
	MOVD  R0, ret+8(FP)
	RET

// func MovW(x uint64, y uint64) uint64
TEXT ·MovW(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	BFI  $0, R1, $16, R0
	MOVD R0, ret+16(FP)
	RET

// func LeaQ(x uint64, y uint64) uint64
TEXT ·LeaQ(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R1<<3, R0, R0
	SUB  $24, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func TestQZero(x uint64, y uint64) uint64
TEXT ·TestQZero(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	TST  R1, R0
	CSET EQ, R2
	MOVD R2, ret+16(FP)
	RET

// func TestBZero(x uint64, y uint64) uint64
TEXT ·TestBZero(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	AND  $0xff, R1, R16
	AND  $0xff, R0, R15
	TST  R16, R15
	CSET EQ, R2
	MOVD R2, ret+16(FP)
	RET

// func TestBSelfZero(x uint64) uint64
TEXT ·TestBSelfZero(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TST  $0xff, R0
	CSET EQ, R1
	MOVD R1, ret+8(FP)
	RET

// func TestWSelfZero(x uint64) uint64
TEXT ·TestWSelfZero(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	TST  $0xffff, R0
	CSET EQ, R1
	MOVD R1, ret+8(FP)
	RET

// func VecCopyReg(dst *[16]byte, src *[16]byte)
// Requires: SSE2
TEXT ·VecCopyReg(SB), NOSPLIT, $0-16
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	FMOVQ (R1), F0
	VMOV  V0.B16, V0.B16
	FMOVQ F0, (R0)
	RET

// func SetAll(a uint64, b uint64) uint64
TEXT ·SetAll(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD $0, R2
	CMP  R1, R0
	CSET EQ, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET NE, R3
	LSL  $0x01, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET LT, R3
	LSL  $0x02, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET LE, R3
	LSL  $0x03, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET GT, R3
	LSL  $0x04, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET GE, R3
	LSL  $0x05, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET LO, R3
	LSL  $0x06, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET HS, R3
	LSL  $0x07, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET HI, R3
	LSL  $0x08, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET LS, R3
	LSL  $0x09, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET MI, R3
	LSL  $0x0a, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET PL, R3
	LSL  $0x0b, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET VS, R3
	LSL  $0x0c, R3, R3
	ORR  R3, R2, R2
	CMP  R1, R0
	CSET VC, R3
	LSL  $0x0d, R3, R3
	ORR  R3, R2, R2
	MOVD R2, ret+16(FP)
	RET

// func JmpAll(a uint64, b uint64) uint64
TEXT ·JmpAll(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD $0, R2
	CMP  R1, R0
	BEQ  jmpall_0_taken
	JMP  jmpall_0_done

jmpall_0_taken:
	ORR $0x00000001, R2, R2

jmpall_0_done:
	CMP R1, R0
	BNE jmpall_1_taken
	JMP jmpall_1_done

jmpall_1_taken:
	ORR $0x00000002, R2, R2

jmpall_1_done:
	CMP R1, R0
	BLT jmpall_2_taken
	JMP jmpall_2_done

jmpall_2_taken:
	ORR $0x00000004, R2, R2

jmpall_2_done:
	CMP R1, R0
	BLE jmpall_3_taken
	JMP jmpall_3_done

jmpall_3_taken:
	ORR $0x00000008, R2, R2

jmpall_3_done:
	CMP R1, R0
	BGT jmpall_4_taken
	JMP jmpall_4_done

jmpall_4_taken:
	ORR $0x00000010, R2, R2

jmpall_4_done:
	CMP R1, R0
	BGE jmpall_5_taken
	JMP jmpall_5_done

jmpall_5_taken:
	ORR $0x00000020, R2, R2

jmpall_5_done:
	CMP R1, R0
	BLO jmpall_6_taken
	JMP jmpall_6_done

jmpall_6_taken:
	ORR $0x00000040, R2, R2

jmpall_6_done:
	CMP R1, R0
	BHS jmpall_7_taken
	JMP jmpall_7_done

jmpall_7_taken:
	ORR $0x00000080, R2, R2

jmpall_7_done:
	CMP R1, R0
	BHI jmpall_8_taken
	JMP jmpall_8_done

jmpall_8_taken:
	ORR $0x00000100, R2, R2

jmpall_8_done:
	CMP R1, R0
	BLS jmpall_9_taken
	JMP jmpall_9_done

jmpall_9_taken:
	ORR $0x00000200, R2, R2

jmpall_9_done:
	CMP R1, R0
	BMI jmpall_10_taken
	JMP jmpall_10_done

jmpall_10_taken:
	ORR $0x00000400, R2, R2

jmpall_10_done:
	CMP R1, R0
	BPL jmpall_11_taken
	JMP jmpall_11_done

jmpall_11_taken:
	ORR $0x00000800, R2, R2

jmpall_11_done:
	CMP R1, R0
	BVS jmpall_12_taken
	JMP jmpall_12_done

jmpall_12_taken:
	ORR $0x00001000, R2, R2

jmpall_12_done:
	CMP R1, R0
	BVC jmpall_13_taken
	JMP jmpall_13_done

jmpall_13_taken:
	ORR $0x00002000, R2, R2

jmpall_13_done:
	MOVD R2, ret+16(FP)
	RET

// func CmovAll(a uint64, b uint64) uint64
// Requires: CMOV
TEXT ·CmovAll(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD $0, R2
	MOVD $0x0000000000000001, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL EQ, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000002, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL NE, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000004, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL LT, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000008, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL LE, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000010, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL GT, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000020, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL GE, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000040, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL LO, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000080, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL HS, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000100, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL HI, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000200, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL LS, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000400, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL MI, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000000800, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL PL, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000001000, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL VS, R3, R5, R5
	ORR  R5, R2, R2
	MOVD $0x0000000000002000, R3
	MOVD $0, R5
	CMP  R1, R0
	CSEL VC, R3, R5, R5
	ORR  R5, R2, R2
	MOVD R2, ret+16(FP)
	RET

// func ShlCountFold(x uint64, n uint64) uint64
TEXT ·ShlCountFold(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R2
	LSL  R2, R0, R3
	MOVD R0, R1
	ADD  R1, R3, R3
	ADD  R2, R3, R3
	MOVD R3, ret+16(FP)
	RET

// func ShrCountFold32(x uint64, n uint64) uint64
TEXT ·ShrCountFold32(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R2
	LSRW R2, R0, R3
	MOVD R0, R1
	ADD  R1, R3, R3
	ADD  R2, R3, R3
	MOVD R3, ret+16(FP)
	RET

// func RolCountFold(x uint64, n uint64) uint64
TEXT ·RolCountFold(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R2
	NEG  R2, R16
	ROR  R16, R0, R3
	MOVD R0, R1
	ADD  R1, R3, R3
	ADD  R2, R3, R3
	MOVD R3, ret+16(FP)
	RET

// func CountFoldRefusedRead(x uint64, n uint64) uint64
TEXT ·CountFoldRefusedRead(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R2
	MOVD R2, R1
	LSL  R1, R0, R0
	ADD  R1, R0, R0
	ADD  R2, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShlCountSelf(n uint64) uint64
TEXT ·ShlCountSelf(SB), NOSPLIT, $0-16
	MOVD n+0(FP), R0
	MOVD R0, R1
	LSL  R1, R1, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func SarCopyFold(x uint64) uint64
TEXT ·SarCopyFold(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ASR  $0x03, R0, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func ShlCopyFoldCX(x uint64) uint64
TEXT ·ShlCopyFoldCX(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSL  $0x02, R0, R1
	ADD  R0, R1, R1
	MOVD R1, ret+8(FP)
	RET

// func AdcAccumQ(x uint64, acc uint64) uint64
TEXT ·AdcAccumQ(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  acc+8(FP), R1
	CMP   $0x04, R0
	CSINC HS, R1, R1, R1
	MOVD  R1, ret+16(FP)
	RET

// func SetGeZeroMov(a uint64, b uint64) uint64
TEXT ·SetGeZeroMov(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	CSET GE, R2
	MOVD R2, ret+16(FP)
	RET

// func SetGeRefusedRead(a uint64, b uint64) uint64
TEXT ·SetGeRefusedRead(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD $0, R2
	ADD  R2, R0, R0
	CMP  R1, R0
	CSET GE, R16
	BFI  $0, R16, $8, R2
	MOVD R2, ret+16(FP)
	RET
