// Package arm64lower runs the functions generated by asm.go against pure-Go
// references. The generated asm is produced for both amd64 and arm64 from one
// avo source, so running this test on each architecture (CI does both) verifies
// the arm64 lowering printer is semantics-preserving.
package arm64lower

import (
	"bytes"
	"fmt"
	"math/bits"
	"strings"
	"testing"
	"testing/quick"

	"github.com/mmcloughlin/avo/tests/arm64lower/condspec"
	"github.com/mmcloughlin/avo/tests/arm64lower/propspec"
)

//go:generate go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go
//go:generate sh prop_table.sh

func TestArith(t *testing.T) {
	cases := []struct {
		name string
		got  interface{}
		want interface{}
	}{
		{"Add", Add, func(x, y uint64) uint64 { return x + y }},
		{"Sub", Sub, func(x, y uint64) uint64 { return x - y }},
		{"Neg", Neg, func(x uint64) uint64 { return -x }},
		{"AndOrXor", AndOrXor, func(x, y uint64) uint64 { return (x & y) ^ (x | y) }},
		{"ShlCL", ShlCL, func(x, n uint64) uint64 { return x << (n & 63) }},
		{"ShrCL", ShrCL, func(x, n uint64) uint64 { return x >> (n & 63) }},
		{"RolCL", RolCL, func(x, n uint64) uint64 { return bits.RotateLeft64(x, int(n&63)) }},
		{"ZeroExt32", ZeroExt32, func(x uint64) uint64 { return uint64(uint32(x)) + x }},
		{"HighByte", HighByte, func(x uint64) uint64 { return (x >> 8) & 0xff }},
		{"ShiftExtractByte64Lo", ShiftExtractByte64Lo, func(x uint64) uint64 { return x&0xff + x }},
		{"ShiftExtractByte64Mid", ShiftExtractByte64Mid, func(x uint64) uint64 { return (x>>8)&0xff + x }},
		{"ShiftExtractByte64Hi", ShiftExtractByte64Hi, func(x uint64) uint64 { return (x>>56)&0xff + x }},
		{"ShiftExtractByte32", ShiftExtractByte32, func(x uint64) uint64 { return uint64((uint32(x)>>16)&0xff) + x }},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if err := quick.CheckEqual(c.got, c.want, nil); err != nil {
				t.Error(err)
			}
		})
	}
}

func TestConditions(t *testing.T) {
	b2u := func(b bool) uint64 {
		if b {
			return 1
		}
		return 0
	}
	pairs := []struct{ a, b uint64 }{
		{0, 0},
		{1, 0},
		{0, 1},
		{5, 5},
		{5, 6},
		{6, 5},
		{^uint64(0), 0},
		{0, ^uint64(0)}, // -1 vs 0 (signed) / max vs 0 (unsigned)
		{^uint64(0), 1},
		{1, ^uint64(0)},
		{1 << 63, 1},
		{1, 1 << 63}, // sign-bit boundaries
	}
	conds := []struct {
		name string
		got  func(a, b uint64) uint64
		want func(a, b uint64) bool
	}{
		{"LessS", LessS, func(a, b uint64) bool { return int64(a) < int64(b) }},
		{"GreaterEqS", GreaterEqS, func(a, b uint64) bool { return int64(a) >= int64(b) }},
		{"LessU", LessU, func(a, b uint64) bool { return a < b }},
		{"AboveU", AboveU, func(a, b uint64) bool { return a > b }},
		{"Equal", Equal, func(a, b uint64) bool { return a == b }},
	}
	for _, c := range conds {
		t.Run(c.name, func(t *testing.T) {
			for _, p := range pairs {
				if got, want := c.got(p.a, p.b), b2u(c.want(p.a, p.b)); got != want {
					t.Errorf("%s(%#x, %#x) = %d, want %d", c.name, p.a, p.b, got, want)
				}
			}
		})
	}
}

func TestSelectEq(t *testing.T) {
	ref := func(a, b, c, d uint64) uint64 {
		if a == b {
			return c
		}
		return d
	}
	cases := [][4]uint64{
		{1, 1, 7, 9}, {1, 2, 7, 9}, {0, 0, 100, 200}, {5, 6, 100, 200},
	}
	for _, c := range cases {
		if got, want := SelectEq(c[0], c[1], c[2], c[3]), ref(c[0], c[1], c[2], c[3]); got != want {
			t.Errorf("SelectEq%v = %d, want %d", c, got, want)
		}
	}
}

// TestFlagGap covers a flag-setting instruction separated from the conditional
// branch that consumes its result by a flag-transparent MOV. The lowering must
// still emit the flag-setting variant of the producer; otherwise the branch
// reads stale NZCV and the result is wrong for some inputs.
func TestFlagGap(t *testing.T) {
	b2u := func(b bool) uint64 {
		if b {
			return 1
		}
		return 0
	}
	t.Run("SubGapEq", func(t *testing.T) {
		for _, p := range []struct{ x, y uint64 }{{5, 5}, {5, 6}, {0, 0}, {1, 0}} {
			if got, want := SubGapEq(p.x, p.y), b2u(p.x == p.y); got != want {
				t.Errorf("SubGapEq(%d, %d) = %d, want %d", p.x, p.y, got, want)
			}
		}
	})
	t.Run("DecGapZero", func(t *testing.T) {
		for _, x := range []uint64{0, 1, 2, 100} {
			if got, want := DecGapZero(x, 0), b2u(x-1 == 0); got != want {
				t.Errorf("DecGapZero(%d) = %d, want %d", x, got, want)
			}
		}
	})
}

// TestCompareWidth covers 32-bit CMPL/TESTL on operands whose upper 32 bits
// differ. A correct lowering compares only the low 32 bits; folding to a 64-bit
// compare is observably wrong here, for signed and unsigned conditions alike.
//
//nolint:gocognit // table-driven differential test; splitting the cases would only add indirection, not clarity.
func TestCompareWidth(t *testing.T) {
	b2u := func(b bool) uint64 {
		if b {
			return 1
		}
		return 0
	}
	t.Run("CmpL32Eq", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0x1_00000005, 0x2_00000005}, // low32 equal, high32 differ
			{0x1_00000005, 0x1_00000006}, // low32 differ
		}
		for _, p := range pairs {
			if got, want := CmpL32Eq(p.a, p.b), b2u(uint32(p.a) == uint32(p.b)); got != want {
				t.Errorf("CmpL32Eq(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("CmpL32LessS", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0xF_FFFFFFFF, 0xF_00000001}, // int32 -1 < 1, but uint64 a > b
			{0x0_00000005, 0x0_00000003},
		}
		for _, p := range pairs {
			if got, want := CmpL32LessS(p.a, p.b), b2u(int32(p.a) < int32(p.b)); got != want {
				t.Errorf("CmpL32LessS(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("CmpL32LessU", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0x2_00000001, 0x1_00000002}, // uint32 1 < 2, but uint64 a > b
			{0x0_00000005, 0x0_00000003},
		}
		for _, p := range pairs {
			if got, want := CmpL32LessU(p.a, p.b), b2u(uint32(p.a) < uint32(p.b)); got != want {
				t.Errorf("CmpL32LessU(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("TestL32", func(t *testing.T) {
		pairs := []struct{ a, m uint64 }{
			{0x1_00000000, 0x1_00000000}, // low32 AND is 0, but 64-bit AND is not
			{0x0_00000006, 0x0_00000002},
		}
		for _, p := range pairs {
			if got, want := TestL32(p.a, p.m), b2u(uint32(p.a)&uint32(p.m) == 0); got != want {
				t.Errorf("TestL32(%#x, %#x) = %d, want %d", p.a, p.m, got, want)
			}
		}
	})
	// CmpW16Eq/CmpB8Ne/TestW16Eq cover the EQ/NE-only zero-extend fallback for
	// sub-32-bit CMP/TEST (see lowerSubwordCompareEqNe in printer/arm64.go):
	// klauspost/compress's zstd fseDecoder.buildDtable compares two uint16
	// values this way. Every case's operands agree in the low bits under test
	// but differ above it, so a naive 64-bit fold gets the wrong answer.
	t.Run("CmpW16Eq", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0x1_0005, 0x2_0005},                         // low16 equal, high bits differ
			{0x1_0005, 0x1_0006},                         // low16 differ
			{0xFFFF_FFFF_0000FFFF, 0x0000_0000_0000FFFF}, // low16 equal (0xFFFF), high bits very different
		}
		for _, p := range pairs {
			if got, want := CmpW16Eq(p.a, p.b), b2u(uint16(p.a) == uint16(p.b)); got != want {
				t.Errorf("CmpW16Eq(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("CmpB8Ne", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0x1_05, 0x2_05}, // low8 equal, high bits differ
			{0x1_05, 0x1_06}, // low8 differ
			{0xFFFF_FFFF_FFFF_00FF, 0x0000_0000_0000_00FF}, // low8 equal (0xFF), high bits very different
		}
		for _, p := range pairs {
			if got, want := CmpB8Ne(p.a, p.b), b2u(uint8(p.a) != uint8(p.b)); got != want {
				t.Errorf("CmpB8Ne(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("TestW16Eq", func(t *testing.T) {
		pairs := []struct{ a, m uint64 }{
			{0x1_0000, 0x1_0000}, // low16 AND is 0, but 64-bit AND is not
			{0x0_0006, 0x0_0002},
		}
		for _, p := range pairs {
			if got, want := TestW16Eq(p.a, p.m), b2u(uint16(p.a)&uint16(p.m) == 0); got != want {
				t.Errorf("TestW16Eq(%#x, %#x) = %d, want %d", p.a, p.m, got, want)
			}
		}
	})
}

func imulWideRef(x, y int64) (lo, hi uint64) {
	uhi, ulo := bits.Mul64(uint64(x), uint64(y))
	h := uhi
	if x < 0 {
		h -= uint64(y)
	}
	if y < 0 {
		h -= uint64(x)
	}
	return ulo, h
}

func bzhiRef(x, n uint64) uint64 {
	if n >= 64 {
		return x
	}
	return x & ((uint64(1) << n) - 1)
}

// TestMultiply covers IMULQ (2- and 1-operand), IMUL3Q, MULQ, and BMI2 MULXQ.
func TestMultiply(t *testing.T) {
	pairs := []struct{ x, y uint64 }{
		{0, 0},
		{1, 1},
		{3, 5},
		{0xdeadbeef, 0x1234},
		{^uint64(0), 2},
		{^uint64(0), ^uint64(0)},
		{1 << 40, 1 << 40},
		{0x9E3779B97F4A7C15, 0x100000001},
	}
	for _, p := range pairs {
		if got, want := IMul2(p.x, p.y), p.x*p.y; got != want {
			t.Errorf("IMul2(%#x, %#x) = %#x, want %#x", p.x, p.y, got, want)
		}
		// IMUL3Q sign-extends its imm32: 0x9E3779B1 has bit 31 set, so the x86
		// multiplier is the sign-extended 0xFFFFFFFF9E3779B1.
		if got, want := IMul3(p.x), p.x*0xFFFFFFFF9E3779B1; got != want {
			t.Errorf("IMul3(%#x) = %#x, want %#x", p.x, got, want)
		}
		wantHi, wantLo := bits.Mul64(p.x, p.y)
		if lo, hi := MulWide(p.x, p.y); lo != wantLo || hi != wantHi {
			t.Errorf("MulWide(%#x, %#x) = (%#x, %#x), want (%#x, %#x)", p.x, p.y, lo, hi, wantLo, wantHi)
		}
		if lo, hi := MulX(p.x, p.y); lo != wantLo || hi != wantHi {
			t.Errorf("MulX(%#x, %#x) = (%#x, %#x), want (%#x, %#x)", p.x, p.y, lo, hi, wantLo, wantHi)
		}
		sLo, sHi := imulWideRef(int64(p.x), int64(p.y))
		if lo, hi := IMulWide(int64(p.x), int64(p.y)); lo != sLo || hi != sHi {
			t.Errorf("IMulWide(%d, %d) = (%#x, %#x), want (%#x, %#x)", int64(p.x), int64(p.y), lo, hi, sLo, sHi)
		}
	}
}

// TestBMI2 covers the BMI2 flag-free shifts/rotate and bit-field ops.
//
//nolint:gocognit // table-driven differential test; splitting the cases would only add indirection, not clarity.
func TestBMI2(t *testing.T) {
	xs := []uint64{0, 1, 0xdeadbeefcafef00d, ^uint64(0), 0x8000000000000000, 0x00ff00ff00ff00ff}
	for _, x := range xs {
		for _, n := range []uint64{0, 1, 7, 8, 31, 32, 63} {
			if got, want := ShlX(x, n), x<<(n&63); got != want {
				t.Errorf("ShlX(%#x, %d) = %#x, want %#x", x, n, got, want)
			}
			if got, want := ShrX(x, n), x>>(n&63); got != want {
				t.Errorf("ShrX(%#x, %d) = %#x, want %#x", x, n, got, want)
			}
			if got, want := SarX(x, n), uint64(int64(x)>>(n&63)); got != want {
				t.Errorf("SarX(%#x, %d) = %#x, want %#x", x, n, got, want)
			}
			if got, want := Bzhi(x, n), bzhiRef(x, n); got != want {
				t.Errorf("Bzhi(%#x, %d) = %#x, want %#x", x, n, got, want)
			}
		}
		if got, want := RorX(x), bits.RotateLeft64(x, -56); got != want {
			t.Errorf("RorX(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr88(x), (x>>8)&0xff; got != want {
			t.Errorf("Bextr88(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr4_12(x), (x>>4)&0xfff; got != want {
			t.Errorf("Bextr4_12(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr56_8(x), x>>56; got != want {
			t.Errorf("Bextr56_8(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr8_56(x), x>>8; got != want {
			t.Errorf("Bextr8_56(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr8_60(x), x>>8; got != want {
			t.Errorf("Bextr8_60(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr0_0(x), uint64(0); got != want {
			t.Errorf("Bextr0_0(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := Bextr70_8(x), uint64(0); got != want {
			t.Errorf("Bextr70_8(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := BzhiConst13(x), x&0x1fff; got != want {
			t.Errorf("BzhiConst13(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := BzhiConst0(x), uint64(0); got != want {
			t.Errorf("BzhiConst0(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := BzhiConst64(x), x; got != want {
			t.Errorf("BzhiConst64(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := ShlXConst9(x), x<<9; got != want {
			t.Errorf("ShlXConst9(%#x) = %#x, want %#x", x, got, want)
		}
		if got, want := ShrXConst9(x), x>>9; got != want {
			t.Errorf("ShrXConst9(%#x) = %#x, want %#x", x, got, want)
		}
	}
}

// TestHuff0Idioms covers SETcc, the ADC carry-accumulate, BSWAPL, and the
// constrained ADDB shape used by the huff0 decoder's generated code.
func TestHuff0Idioms(t *testing.T) {
	xs := []uint64{0, 1, 3, 4, 5, 0xdeadbeefcafef00d, ^uint64(0), 0x8000000000000000, 127}
	for _, a := range xs {
		for _, b := range xs {
			want := uint64(0)
			if int64(a) >= int64(b) {
				want = 1
			}
			if got := SetGe(a, b); got != want {
				t.Errorf("SetGe(%#x, %#x) = %d, want %d", a, b, got, want)
			}
			cf := uint64(0)
			if a < 4 {
				cf = 1
			}
			want = b&^0xff | (b+cf)&0xff
			if got := AdcAccum(a, b); got != want {
				t.Errorf("AdcAccum(%#x, %#x) = %#x, want %#x", a, b, got, want)
			}
			if got, want := AddByte(a, b), b&^0xff|(a+b)&0xff; got != want {
				t.Errorf("AddByte(%#x, %#x) = %#x, want %#x", a, b, got, want)
			}
		}
		rev := uint64(bits.ReverseBytes32(uint32(a)))
		if got := BswapL(a); got != rev {
			t.Errorf("BswapL(%#x) = %#x, want %#x", a, got, rev)
		}
	}
}

// TestMovbExact covers x86 partial-register byte-move semantics: MOVB into a
// register replaces only the addressed byte (low, or bits 15:8 for AH-style
// destinations) and preserves every other bit — the byte-packing idiom huff0's
// generated decoder relies on.
func TestMovbExact(t *testing.T) {
	xs := []uint64{0, 1, 0xdeadbeefcafef00d, ^uint64(0), 0x8000000000000000, 0x00ff00ff00ff00ff, 127}
	for _, a := range xs {
		for _, b := range xs {
			if got, want := MovbHighDst(a, b), b&^uint64(0xff00)|(a&0xff)<<8; got != want {
				t.Errorf("MovbHighDst(%#x, %#x) = %#x, want %#x", a, b, got, want)
			}
			if got, want := MovbLowPreserve(a, b), b&^uint64(0xff)|(a>>8)&0xff; got != want {
				t.Errorf("MovbLowPreserve(%#x, %#x) = %#x, want %#x", a, b, got, want)
			}
		}
	}
}

// TestPrefetch covers the PREFETCH* lowerings: the hints must assemble in
// every operand shape and leave both the address registers and the flags a
// following branch reads untouched.
func TestPrefetch(t *testing.T) {
	var arr [64]uint64
	for i := range arr {
		arr[i] = uint64(i) * 0x9e3779b97f4a7c15
	}
	for _, i := range []uint64{0, 1, 7, 63, 64, 65, 1000, ^uint64(0)} {
		want := arr[i&63]
		if i&63 != 0 {
			want++
		}
		if got := Prefetch(&arr, i); got != want {
			t.Errorf("Prefetch(arr, %d) = %#x, want %#x", i, got, want)
		}
	}
}

// TestCMOVConditions covers the CMOVcc conditions enabled by the completed table.
func TestCMOVConditions(t *testing.T) {
	const c, d = uint64(0x1111), uint64(0x2222)
	sel := func(cond bool) uint64 {
		if cond {
			return c
		}
		return d
	}
	pairs := []struct{ a, b uint64 }{
		{5, 5}, {5, 6}, {6, 5}, {0, ^uint64(0)}, {^uint64(0), 0}, {1 << 63, 1}, {1, 1 << 63},
	}
	cases := []struct {
		name string
		got  func(a, b, c, d uint64) uint64
		want func(a, b uint64) bool
	}{
		{"SelLtS", SelLtS, func(a, b uint64) bool { return int64(a) < int64(b) }},
		{"SelLeS", SelLeS, func(a, b uint64) bool { return int64(a) <= int64(b) }},
		{"SelGtS", SelGtS, func(a, b uint64) bool { return int64(a) > int64(b) }},
		{"SelGeS", SelGeS, func(a, b uint64) bool { return int64(a) >= int64(b) }},
		{"SelLsU", SelLsU, func(a, b uint64) bool { return a <= b }},
		{"SelMi", SelMi, func(a, b uint64) bool { return int64(a-b) < 0 }},
		{"SelPl", SelPl, func(a, b uint64) bool { return int64(a-b) >= 0 }},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			for _, p := range pairs {
				if got, want := tc.got(p.a, p.b, c, d), sel(tc.want(p.a, p.b)); got != want {
					t.Errorf("%s(%#x, %#x) = %#x, want %#x", tc.name, p.a, p.b, got, want)
				}
			}
		})
	}
}

func TestLoadIdx(t *testing.T) {
	var p [8]uint64
	for i := range p {
		p[i] = uint64(i*i + 1)
	}
	for i := uint64(0); i < 8; i++ {
		if got := LoadIdx(&p, i); got != p[i] {
			t.Errorf("LoadIdx(p, %d) = %d, want %d", i, got, p[i])
		}
	}
}

func TestCopy16(t *testing.T) {
	var src, dst [16]byte
	for i := range src {
		src[i] = byte(i*7 + 1)
	}
	Copy16(&dst, &src)
	if dst != src {
		t.Errorf("Copy16: dst %v != src %v", dst, src)
	}
}

// TestOpcodeCoverage exercises the extension, 32-bit ALU, rotate, bit-manipulation
// and 128-bit move lowerings against pure-Go references.
//
//nolint:gocognit // table-driven differential test; splitting the cases would only add indirection, not clarity.
func TestOpcodeCoverage(t *testing.T) {
	xs := []uint64{
		0, 1, 2, 5, 32, 127, 128, 255, 256, 65535, 65536,
		0xdeadbeefcafef00d, ^uint64(0), 1 << 31, 1 << 32, 1 << 63,
		0x00ff00ff00ff00ff, 0xffffffff00000000, 0x80000000,
	}
	unary := []struct {
		name string
		got  func(uint64) uint64
		want func(uint64) uint64
	}{
		{"SxL", SxL, func(x uint64) uint64 { return uint64(int64(int32(x))) }},
		{"SxB", SxB, func(x uint64) uint64 { return uint64(int64(int8(x))) }},
		{"SxBL", SxBL, func(x uint64) uint64 { return uint64(uint32(int32(int8(x)))) }},
		{"SxWL", SxWL, func(x uint64) uint64 { return uint64(uint32(int32(int16(x)))) }},
		{"NegL", NegL, func(x uint64) uint64 { return uint64(-uint32(x)) }},
		{"NotL", NotL, func(x uint64) uint64 { return uint64(^uint32(x)) }},
		{"NotQ", NotQ, func(x uint64) uint64 { return ^x }},
		{"RolL7", RolL7, func(x uint64) uint64 { return uint64(bits.RotateLeft32(uint32(x), 7)) }},
		{"RorQ9", RorQ9, func(x uint64) uint64 { return bits.RotateLeft64(x, -9) }},
		{"RorL9", RorL9, func(x uint64) uint64 { return uint64(bits.RotateLeft32(uint32(x), -9)) }},
		{"BtrQ5", BtrQ5, func(x uint64) uint64 { return x &^ (1 << 5) }},
		{"BtcQ5", BtcQ5, func(x uint64) uint64 { return x ^ (1 << 5) }},
		{"PopcntQ", PopcntQ, func(x uint64) uint64 { return uint64(bits.OnesCount64(x)) }},
		{"SarQ3", SarQ3, func(x uint64) uint64 { return uint64(int64(x) >> 3) }},
		{"SarL3", SarL3, func(x uint64) uint64 { return uint64(uint32(int32(x) >> 3)) }},
		{"IncL", IncL, func(x uint64) uint64 { return uint64(uint32(x) + 1) }},
		// x86 SHLB shifts only the addressed byte and preserves the rest.
		{"ShlB2", ShlB2, func(x uint64) uint64 { return x&^0xff | (x&0xff)<<2&0xff }},
		// TZCNT is defined for a zero input (returns 64); the lowering matches.
		{"TzcntQ", TzcntQ, func(x uint64) uint64 { return uint64(bits.TrailingZeros64(x)) }},
		{"IncQ", IncQ, func(x uint64) uint64 { return x + 1 }},
		{"DecL", DecL, func(x uint64) uint64 { return uint64(uint32(x) - 1) }},
		{"ShrL5", ShrL5, func(x uint64) uint64 { return uint64(uint32(x) >> 5) }},
		{"SxWQ", SxWQ, func(x uint64) uint64 { return uint64(int64(int16(x))) }},
		{"BtsQ5", BtsQ5, func(x uint64) uint64 { return x | 1<<5 }},
		// Shift counts are masked mod width, as x86 does: $64 is a no-op at
		// 64-bit width, $65 shifts by one, $32 is a no-op at 32-bit width.
		{"ShrQ64", ShrQ64, func(x uint64) uint64 { return x }},
		{"ShrQ65", ShrQ65, func(x uint64) uint64 { return x >> 1 }},
		{"ShlQ64", ShlQ64, func(x uint64) uint64 { return x }},
		{"ShrL32", ShrL32, func(x uint64) uint64 { return uint64(uint32(x)) }},
		// BZHI's count is ctrl[7:0]: 256 masks to 0 bits, -1 masks to 255.
		{"BzhiConst256", BzhiConst256, func(x uint64) uint64 { return 0 }},
		{"BzhiConstNeg", BzhiConstNeg, func(x uint64) uint64 { return x }},
		{"TestBSelfZero", TestBSelfZero, func(x uint64) uint64 {
			if x&0xff == 0 {
				return 1
			}
			return 0
		}},
		{"TestWSelfZero", TestWSelfZero, func(x uint64) uint64 {
			if x&0xffff == 0 {
				return 1
			}
			return 0
		}},
	}
	for _, c := range unary {
		t.Run(c.name, func(t *testing.T) {
			for _, x := range xs {
				if got, want := c.got(x), c.want(x); got != want {
					t.Errorf("%s(%#x) = %#x, want %#x", c.name, x, got, want)
				}
			}
		})
	}

	// BSF's result is architecturally undefined for a zero input, so only
	// non-zero values are compared.
	t.Run("BsfQ", func(t *testing.T) {
		for _, x := range xs {
			if x == 0 {
				continue
			}
			if got, want := BsfQ(x), uint64(bits.TrailingZeros64(x)); got != want {
				t.Errorf("BsfQ(%#x) = %d, want %d", x, got, want)
			}
		}
	})

	// BSR is likewise undefined for zero: it reports the index of the highest
	// set bit, so only non-zero values have an architectural answer.
	t.Run("BsrQ", func(t *testing.T) {
		for _, x := range xs {
			if x == 0 {
				continue
			}
			if got, want := BsrQ(x), uint64(bits.Len64(x)-1); got != want {
				t.Errorf("BsrQ(%#x) = %d, want %d", x, got, want)
			}
		}
	})

	// MOVLQZX only exists as a load; check it takes exactly four bytes from the
	// address rather than eight.
	t.Run("ZxLQ", func(t *testing.T) {
		for _, x := range xs {
			v := x
			if got, want := ZxLQ(&v), uint64(uint32(x)); got != want {
				t.Errorf("ZxLQ(%#x) = %#x, want %#x", x, got, want)
			}
		}
	})

	binary := []struct {
		name string
		got  func(uint64, uint64) uint64
		want func(uint64, uint64) uint64
	}{
		// MOVW replaces only the low 16 bits of the destination.
		{"MovW", MovW, func(x, y uint64) uint64 { return x&^0xffff | y&0xffff }},
		{"LeaQ", LeaQ, func(x, y uint64) uint64 { return x + y*8 - 24 }},
		{"TestQZero", TestQZero, func(x, y uint64) uint64 {
			if x&y == 0 {
				return 1
			}
			return 0
		}},
		{"TestBZero", TestBZero, func(x, y uint64) uint64 {
			if x&y&0xff == 0 {
				return 1
			}
			return 0
		}},
		{"AddL", AddL, func(x, y uint64) uint64 { return uint64(uint32(x) + uint32(y)) }},
		{"SubL", SubL, func(x, y uint64) uint64 { return uint64(uint32(x) - uint32(y)) }},
		{"AndL", AndL, func(x, y uint64) uint64 { return uint64(uint32(x) & uint32(y)) }},
		{"OrL", OrL, func(x, y uint64) uint64 { return uint64(uint32(x) | uint32(y)) }},
		{"ImulL", ImulL, func(x, y uint64) uint64 { return uint64(uint32(x) * uint32(y)) }},
		// XchgQ swaps two registers and returns the first, which must hold y.
		{"XchgQ", XchgQ, func(x, y uint64) uint64 { return y }},
		{"LeaL", LeaL, func(x, y uint64) uint64 { return uint64(uint32(x) + uint32(y)*4 + 7) }},
	}
	for _, c := range binary {
		t.Run(c.name, func(t *testing.T) {
			for _, x := range xs {
				for _, y := range xs {
					if got, want := c.got(x, y), c.want(x, y); got != want {
						t.Errorf("%s(%#x, %#x) = %#x, want %#x", c.name, x, y, got, want)
					}
				}
			}
		})
	}
}

// TestVectorMoves covers the 128-bit MOVOU/MOVOA/PXOR lowerings.
func TestVectorMoves(t *testing.T) {
	var dst [16]byte
	for i := range dst {
		dst[i] = byte(i + 1)
	}
	VecZero(&dst)
	if dst != ([16]byte{}) {
		t.Errorf("VecZero left %v", dst)
	}

	var a, b [32]byte
	for i := range b {
		b[i] = byte(i * 3)
	}
	var c, d [32]byte
	for i := range d {
		d[i] = byte(i + 7)
	}
	VecCopyIdx(&c, &d, 8)
	if !bytes.Equal(c[8:24], d[8:24]) {
		t.Errorf("VecCopyIdx copied %v, want %v", c[8:24], d[8:24])
	}

	VecCopy(&a, &b)
	if !bytes.Equal(a[16:], b[16:]) {
		t.Errorf("VecCopy copied %v, want %v", a[16:], b[16:])
	}
	for i, v := range a[:16] {
		if v != 0 {
			t.Fatalf("VecCopy disturbed the low half at %d: %v", i, a[:16])
		}
	}
}

// TestRandomPrograms replays each generated random program's operations through
// their pure-Go references and compares against the compiled assembly. Running
// on amd64 validates that the references model x86 correctly; running on arm64
// then makes any lowering divergence a test failure.
//
// This is the systematic counterpart to the hand-written cases above: every
// silent miscompile found in this lowering so far (high-byte destinations,
// sign-extending narrow loads, flags crossing a label) was discovered by
// accident, and each is the kind of interaction these programs cover by
// construction.
func TestRandomPrograms(t *testing.T) {
	inputs := []uint64{
		0, 1, 2, 7, 0xff, 0x100, 0x7fffffff, 0x80000000, 0xffffffff,
		1 << 63, ^uint64(0), 0xdeadbeefcafef00d, 0x00ff00ff00ff00ff,
		0xfedcba9876543210,
	}
	for n := 0; n < propspec.NumPrograms; n++ {
		prog := propspec.Program(n, propspec.ProgramLength)
		fn := propPrograms[n]
		names := make([]string, len(prog))
		for i, op := range prog {
			names[i] = propspec.Ops[op].Name
		}
		t.Run(fmt.Sprintf("Prop%d", n), func(t *testing.T) {
			for _, x := range inputs {
				for _, y := range inputs {
					want := x
					for _, op := range prog {
						want = propspec.Ops[op].Ref(want, y)
					}
					if got := fn(x, y); got != want {
						t.Fatalf("Prop%d(%#x, %#x) = %#x, want %#x\nprogram: %s",
							n, x, y, got, want, strings.Join(names, " -> "))
					}
				}
			}
		})
	}
}

// TestReviewRegressions covers lowering bugs found by review: a high-byte source
// read as the low byte, a 32-bit conditional move that skipped x86's
// unconditional zero-extension, and BEXTR clobbering its own staged control
// field with a memory operand's address.
//
//nolint:gocognit // table-driven differential test; splitting the cases would only add indirection, not clarity.
func TestReviewRegressions(t *testing.T) {
	xs := []uint64{0, 1, 0xff, 0x1234, 0xdeadbeefcafef00d, ^uint64(0), 1 << 63, 0xffffffff00000000}

	t.Run("MovbzxHigh", func(t *testing.T) {
		for _, x := range xs {
			if got, want := MovbzxHigh(x), (x>>8)&0xff; got != want {
				t.Errorf("MovbzxHigh(%#x) = %#x, want %#x", x, got, want)
			}
		}
	})

	t.Run("CmovL32", func(t *testing.T) {
		for _, x := range xs {
			for _, y := range xs {
				// Condition is false, but a 32-bit CMOV still writes and
				// zero-extends its destination.
				if got, want := CmovL32(x, y), uint64(uint32(y)); got != want {
					t.Errorf("CmovL32(%#x, %#x) = %#x, want %#x", x, y, got, want)
				}
			}
		}
	})

	t.Run("BextrMem", func(t *testing.T) {
		buf := [4]uint64{0x0123456789abcdef, ^uint64(0), 0, 0xf0f0f0f0f0f0f0f0}
		for i := uint64(0); i < 4; i++ {
			for _, ctrl := range []uint64{8 | 8<<8, 0 | 16<<8, 4 | 12<<8, 32 | 8<<8} {
				start, length := ctrl&0xff, (ctrl>>8)&0xff
				want := buf[i] >> start
				if length < 64 {
					want &= (1 << length) - 1
				}
				if got := BextrMem(&buf, i, ctrl); got != want {
					t.Errorf("BextrMem(buf[%d]=%#x, ctrl=%#x) = %#x, want %#x", i, buf[i], ctrl, got, want)
				}
			}
		}
	})

	// A lowering that materialized CF and let the generic branch path run would
	// invert every one of these, since the carry conditions are mapped by their
	// meaning after a compare rather than as a raw bit. The two polarities and
	// two bit indices between them catch that and a dropped immediate.
	t.Run("BtBranch", func(t *testing.T) {
		for _, tc := range []struct {
			name string
			got  func(uint64) uint64
			bit  uint
			set  bool // value returned when the tested bit is 1
		}{
			{"BtBranch", BtBranch, 0, true},
			{"BtBranchHigh", BtBranchHigh, 3, true},
			{"BtBranchClear", BtBranchClear, 0, false},
			{"BtBranchClearHigh", BtBranchClearHigh, 3, false},
		} {
			t.Run(tc.name, func(t *testing.T) {
				for _, x := range []uint64{0, 1, 8, 9, ^uint64(0), ^uint64(1), ^uint64(8), 0x1234567890abcdef} {
					bitSet := x&(1<<tc.bit) != 0
					want := uint64(20)
					if bitSet == tc.set {
						want = 10
					}
					if got := tc.got(x); got != want {
						t.Errorf("%s(%#x): bit %d is %v, got %d, want %d", tc.name, x, tc.bit, bitSet, got, want)
					}
				}
			})
		}
	})

	// The destination arrives holding all ones, so a lowering that extended the
	// halfword without clearing bits 63:16 returns something far larger than the
	// loaded value rather than quietly agreeing.
	t.Run("MovwzxL", func(t *testing.T) {
		buf := [4]uint16{0x0000, 0xffff, 0x8001, 0x1234}
		for i := uint64(0); i < uint64(len(buf)); i++ {
			if got, want := MovwzxL(&buf, i), uint64(buf[i]); got != want {
				t.Errorf("MovwzxL(buf[%d]=%#x) = %#x, want %#x", i, buf[i], got, want)
			}
		}
	})
}

// TestSecondRoundRegressions covers the lowering bugs found by the independent
// review of the fixed printer: the XOR-self zeroing shortcut dropping the flags
// x86 sets there, and a negative 32-bit immediate sign-extending.
func TestSecondRoundRegressions(t *testing.T) {
	t.Run("XorSelfEq", func(t *testing.T) {
		// XOR of a register with itself is always zero, so ZF is always set.
		for _, x := range []uint64{0, 1, ^uint64(0), 0xdeadbeef} {
			if got := XorSelfEq(x); got != 1 {
				t.Errorf("XorSelfEq(%#x) = %d, want 1 (ZF must be set)", x, got)
			}
		}
	})

	t.Run("MovLNegImm", func(t *testing.T) {
		if got, want := MovLNegImm(), uint64(0xffffffff); got != want {
			t.Errorf("MovLNegImm() = %#x, want %#x", got, want)
		}
	})
}

// TestConditionTable executes every condition the lowering can translate in
// every consumer family that can read one. x86 and arm64 disagree about the
// carry flag's sense after a subtraction, so the translation table inverts the
// unsigned conditions on purpose; that is only checkable by running both sides
// against the same compare. The signed conditions matter for the opposite
// reason -- they agree, but only because the overflow flag is set the same way,
// which the operands below deliberately provoke.
func TestConditionTable(t *testing.T) {
	// Chosen to straddle the signed/unsigned boundary and to make a-b overflow:
	// subtracting across the sign boundary is the only way V and N disagree, and
	// that is exactly where MI differs from LT and OS from OC.
	vals := []uint64{
		0, 1, 2, 0x7fffffffffffffff, 0x8000000000000000, 0x8000000000000001,
		^uint64(0), 0xdeadbeefcafef00d, 1 << 32, 0xffffffff,
	}
	families := []struct {
		name string
		fn   func(a, b uint64) uint64
	}{
		{"SETcc", SetAll},
		{"Jcc", JmpAll},
		{"CMOVcc", CmovAll},
	}
	for _, f := range families {
		t.Run(f.name, func(t *testing.T) {
			for _, a := range vals {
				for _, b := range vals {
					got, want := f.fn(a, b), condspec.Mask(a, b)
					if got == want {
						continue
					}
					// Name the conditions that disagree rather than printing two
					// opaque bitmasks.
					for i, c := range condspec.Conds {
						gotBit, wantBit := got>>uint(i)&1 == 1, want>>uint(i)&1 == 1
						if gotBit != wantBit {
							t.Errorf("%s %s: CMPQ(%#x, %#x) gave %v, want %v",
								f.name, c.Name, a, b, gotBit, wantBit)
						}
					}
				}
			}
		})
	}
}

// TestVecCopyReg covers MOVOA, the aligned 128-bit move, in its
// register-to-register form.
func TestVecCopyReg(t *testing.T) {
	var src, dst [16]byte
	for i := range src {
		src[i] = byte(i * 7)
	}
	VecCopyReg(&dst, &src)
	if dst != src {
		t.Errorf("VecCopyReg gave %v, want %v", dst, src)
	}
}

// TestRandomMemPrograms runs the memory-operand family. Where the register-only
// programs check that each operation computes the right value, these check the
// machinery around the operand: the address the lowering builds, the scratch
// register it stages the value through, and the cache that lets a second access
// reuse the first one's address. A stale cached address or a scratch register
// reused while still live produces a wrong answer only in a particular
// sequence, which is why these are generated rather than written by hand.
func TestRandomMemPrograms(t *testing.T) {
	base := [8]uint64{
		0, 1, 0xdeadbeefcafef00d, 0xffffffff00000000,
		0x8000000000000000, 0x00ff00ff00ff00ff, ^uint64(0), 0x123456789abcdef0,
	}
	inputs := []struct{ x, y uint64 }{
		{0, 0},
		{1, 1},
		{0xdeadbeef, 2},
		{^uint64(0), 3},
		{1 << 63, 5},
		{0x0123456789abcdef, 7},
		{0xffffffff, 4},
	}
	for n := 0; n < propspec.NumMemPrograms; n++ {
		prog := propspec.MemProgram(n, propspec.MemProgramLength)
		names := make([]string, len(prog))
		for i, op := range prog {
			names[i] = propspec.MemOps[op].Name
		}
		for _, in := range inputs {
			gotMem := base
			got := memPropPrograms[n](in.x, in.y, &gotMem)

			wantMem := base
			want := in.x
			idx := in.y & 3
			for _, op := range prog {
				want = propspec.MemOps[op].Ref(want, in.y, &wantMem, &idx)
			}
			if got != want {
				t.Errorf("MemProp%d(%#x, %#x) = %#x, want %#x\nprogram: %s",
					n, in.x, in.y, got, want, strings.Join(names, " -> "))
			}
			if gotMem != wantMem {
				t.Errorf("MemProp%d(%#x, %#x) left memory %#x, want %#x\nprogram: %s",
					n, in.x, in.y, gotMem, wantMem, strings.Join(names, " -> "))
			}
		}
	}
}

// TestReviewRound4Regressions covers the silent miscompiles found by the fourth
// round of adversarial review. Every one of them is reachable from an ordinary
// x86 operand form that the in-tree generators happen never to use, which is
// what makes them the interesting class: the printer had been exercised for
// years by code that never took these paths.
//
//nolint:gocognit // table-driven differential test; splitting the cases would only add indirection, not clarity.
func TestReviewRound4Regressions(t *testing.T) {
	// A 32-bit read-modify-write on memory must touch four bytes. The lowering
	// loaded and stored eight, and since the W-form arithmetic zeroes the upper
	// half of the scratch register, the store cleared the following word.
	t.Run("MemRMWWidth", func(t *testing.T) {
		cases := []struct {
			name string
			run  func(p *[2]uint32)
			want [2]uint32
		}{
			{"IncLMem", IncLMem, [2]uint32{6, 0xcafebabe}},
			{"DecLMem", DecLMem, [2]uint32{4, 0xcafebabe}},
			{"XorlMem", func(p *[2]uint32) { XorlMem(p, 0xff) }, [2]uint32{5 ^ 0xff, 0xcafebabe}},
		}
		for _, c := range cases {
			got := [2]uint32{5, 0xcafebabe}
			c.run(&got)
			if got != c.want {
				t.Errorf("%s gave %#x, want %#x (the second element is the witness: "+
					"a wide store zeroes it)", c.name, got, c.want)
			}
		}
		q := [2]uint64{5, 0xdeadbeefcafef00d}
		IncQMem(&q)
		if want := ([2]uint64{6, 0xdeadbeefcafef00d}); q != want {
			t.Errorf("IncQMem gave %#x, want %#x", q, want)
		}
	})

	// XORL is 32-bit, so a sign test after it reads bit 31, not bit 63.
	t.Run("XorlSign", func(t *testing.T) {
		for _, c := range []struct{ x, y uint64 }{
			{0x80000000, 0},
			{0, 0x80000000},
			{0x80000000, 0x80000000},
			{0xffffffff00000000, 0},
			{1, 2},
			{0x7fffffff, 0},
		} {
			want := uint64(0)
			if (uint32(c.x)^uint32(c.y))&0x80000000 != 0 {
				want = 1
			}
			if got := XorlSign(c.x, c.y); got != want {
				t.Errorf("XorlSign(%#x, %#x) = %d, want %d", c.x, c.y, got, want)
			}
		}
	})

	// A byte compare against a high-byte register reads bits 15:8. AH renames to
	// the same arm64 register as AL, so masking compared the wrong byte -- and
	// wrongly in both directions, which these two inputs pin down.
	t.Run("CmpBHigh", func(t *testing.T) {
		for _, c := range []struct {
			x    uint64
			want uint64
		}{
			{0x0205, 1}, // AH == 2, AL == 5
			{0x0502, 0}, // AH == 5, AL == 2: the inverted case
			{0x0200, 1},
			{0x0002, 0},
		} {
			if got := CmpBHigh(c.x); got != c.want {
				t.Errorf("CmpBHigh(%#x) = %d, want %d", c.x, got, c.want)
			}
		}
	})

	// A 16-bit load writes bits 15:0 and preserves the upper 48, like every
	// other MOVW form. A bare zero-extending load is shorter and was wrong.
	t.Run("MovWLoad", func(t *testing.T) {
		for _, c := range []struct {
			x uint64
			v uint16
		}{
			{0xffffffffffff0000, 0x1234},
			{0xdeadbeefcafe0000, 0xffff},
			{0, 0x8000},
			{^uint64(0), 0},
		} {
			v := c.v
			want := c.x&^0xffff | uint64(c.v)
			if got := MovWLoad(c.x, &v); got != want {
				t.Errorf("MovWLoad(%#x, %#x) = %#x, want %#x", c.x, c.v, got, want)
			}
		}
	})

	// x86 lets MULX name one register for both destinations, and defines the
	// high half as written second, so the high half survives.
	t.Run("MulXAlias", func(t *testing.T) {
		for _, c := range []struct{ x, y uint64 }{
			{1 << 32, 0xdeadbeef00000000},
			{3, 5},
			{^uint64(0), ^uint64(0)},
		} {
			hi, _ := bits.Mul64(c.x, c.y)
			if got := MulXAlias(c.x, c.y); got != hi {
				t.Errorf("MulXAlias(%#x, %#x) = %#x, want the high half %#x", c.x, c.y, got, hi)
			}
		}
	})

	// The canonical immediate-test form, which x86 writes immediate-first.
	t.Run("TestQImm", func(t *testing.T) {
		for _, x := range []uint64{0, 0x10, 0x20, ^uint64(0), 0xefffffff} {
			want := uint64(0)
			if x&0x10 == 0 {
				want = 1
			}
			if got := TestQImm(x, 0); got != want {
				t.Errorf("TestQImm(%#x) = %d, want %d", x, got, want)
			}
		}
	})

	// Instructions that preserve EFLAGS on x86 must not break the link between a
	// compare and the branch reading it. These used to abort generation; the
	// risk in allowing them is a silently stale flag read, so the branch outcome
	// is what gets checked.
	t.Run("FlagsAcrossTransparent", func(t *testing.T) {
		for _, c := range []struct{ a, b uint64 }{
			{5, 5}, {5, 6}, {0, 0}, {^uint64(0), ^uint64(0)}, {1 << 63, 0},
		} {
			want := uint64(0)
			if c.a == c.b {
				want = 1
			}
			if got := FlagsAcrossTransparent(c.a, c.b); got != want {
				t.Errorf("FlagsAcrossTransparent(%#x, %#x) = %d, want %d", c.a, c.b, got, want)
			}
		}
	})
}

// TestQWidthImmediates covers 64-bit operand slots holding an immediate with
// bit 31 set. x86-64 encodes imm32 there and sign-extends it, so $0x80000000
// means 0xffffffff80000000 -- and Go's assembler takes the unsigned spelling
// without complaint, which is what made this invisible. Every case is chosen so
// the literal and sign-extended readings disagree.
//
//nolint:gocognit // table-driven differential test; splitting the cases would only add indirection, not clarity.
func TestQWidthImmediates(t *testing.T) {
	const se = uint64(0xffffffff80000000) // what $0x80000000 means at Q width

	xs := []uint64{
		0, 1, 0x80000000, se, ^uint64(0), 1 << 63, 0x7fffffff, 0xdeadbeefcafef00d,
	}

	t.Run("AndQ", func(t *testing.T) {
		for _, x := range xs {
			if got, want := AndQBit31(x), x&se; got != want {
				t.Errorf("AndQBit31(%#x) = %#x, want %#x", x, got, want)
			}
		}
	})
	t.Run("AddQ", func(t *testing.T) {
		for _, x := range xs {
			if got, want := AddQBit31(x), x+se; got != want {
				t.Errorf("AddQBit31(%#x) = %#x, want %#x", x, got, want)
			}
		}
	})
	t.Run("OrQ", func(t *testing.T) {
		for _, x := range xs {
			if got, want := OrQBit31(x), x|uint64(0xffffffffffffffe0); got != want {
				t.Errorf("OrQBit31(%#x) = %#x, want %#x", x, got, want)
			}
		}
	})
	t.Run("CmpQ", func(t *testing.T) {
		// Probed with both readings of the constant: only one is equal.
		for _, x := range xs {
			want := uint64(0)
			if x == se {
				want = 1
			}
			if got := CmpQBit31(x); got != want {
				t.Errorf("CmpQBit31(%#x) = %d, want %d", x, got, want)
			}
		}
	})
	t.Run("TestQ", func(t *testing.T) {
		for _, x := range xs {
			want := uint64(0)
			if x&se == 0 {
				want = 1
			}
			if got := TestQBit31(x); got != want {
				t.Errorf("TestQBit31(%#x) = %d, want %d", x, got, want)
			}
		}
	})
	t.Run("MovQToMem", func(t *testing.T) {
		v := uint64(0)
		MovQBit31Mem(&v)
		if v != se {
			t.Errorf("MovQBit31Mem stored %#x, want %#x", v, se)
		}
	})
	t.Run("MovQToRegIsUnaffected", func(t *testing.T) {
		// The assembler narrows this one to a zero-extending MOVL, so the
		// literal value is correct here. If the sign-extension rewrite ever
		// leaks into this path, this catches it.
		if got, want := MovQBit31Reg(), uint64(0x80000000); got != want {
			t.Errorf("MovQBit31Reg() = %#x, want %#x", got, want)
		}
	})
}

// TestCmpLIntMin covers the one immediate where the CMN rewrite is invalid.
// Subtracting a negative is adding its magnitude, but negating INT32_MIN gives
// 2^31, which as a 32-bit addend is INT32_MIN again -- so the arm64 side would
// add what x86 subtracts. The overflow flag then disagrees on every input and
// all four signed conditions flip, while the unsigned ones look fine.
func TestCmpLIntMin(t *testing.T) {
	for _, x := range []uint64{
		0, 1, 0x7fffffff, 0x80000000, 0xffffffff, 0xffffffff80000000, 1 << 63,
	} {
		a, b := int32(uint32(x)), int32(-2147483648)
		want := uint64(0)
		for i, cond := range []bool{a < b, a >= b, a > b, a <= b} {
			if cond {
				want |= 1 << uint(i)
			}
		}
		if got := CmpLIntMin(x); got != want {
			t.Errorf("CmpLIntMin(%#x) = %#04b, want %#04b (bits are LT,GE,GT,LE)", x, got, want)
		}
	}
}
