// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDQ AX, CX
	MOVQ CX, ret+16(FP)
	RET

// func Sub(x uint64, y uint64) uint64
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBQ CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func Neg(x uint64) uint64
TEXT ·Neg(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	NEGQ AX
	MOVQ AX, ret+8(FP)
	RET

// func AndOrXor(x uint64, y uint64) uint64
TEXT ·AndOrXor(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	MOVQ AX, DX
	ANDQ CX, DX
	ORQ  CX, AX
	XORQ AX, DX
	MOVQ DX, ret+16(FP)
	RET

// func ShlCL(x uint64, n uint64) uint64
TEXT ·ShlCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	SHLQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func ShrCL(x uint64, n uint64) uint64
TEXT ·ShrCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	SHRQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func RolCL(x uint64, n uint64) uint64
TEXT ·RolCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	ROLQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func ZeroExt32(x uint64) uint64
TEXT ·ZeroExt32(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVL AX, CX
	ADDQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func HighByte(x uint64) uint64
TEXT ·HighByte(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVB    AH, AL
	MOVBQZX AL, AX
	MOVQ    AX, ret+8(FP)
	RET

// func ShiftExtractByte64Lo(x uint64) uint64
TEXT ·ShiftExtractByte64Lo(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVQ    AX, CX
	SHRQ    $0x00, CX
	MOVBQZX CL, CX
	ADDQ    AX, CX
	MOVQ    CX, ret+8(FP)
	RET

// func ShiftExtractByte64Mid(x uint64) uint64
TEXT ·ShiftExtractByte64Mid(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVQ    AX, CX
	SHRQ    $0x08, CX
	MOVBQZX CL, CX
	ADDQ    AX, CX
	MOVQ    CX, ret+8(FP)
	RET

// func ShiftExtractByte64Hi(x uint64) uint64
TEXT ·ShiftExtractByte64Hi(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVQ    AX, CX
	SHRQ    $0x38, CX
	MOVBQZX CL, CX
	ADDQ    AX, CX
	MOVQ    CX, ret+8(FP)
	RET

// func ShiftExtractByte32(x uint64) uint64
TEXT ·ShiftExtractByte32(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVL    AX, CX
	SHRL    $0x10, CX
	MOVBLZX CL, CX
	ADDQ    AX, CX
	MOVQ    CX, ret+8(FP)
	RET

// func LoadIdx(p *[8]uint64, i uint64) uint64
TEXT ·LoadIdx(SB), NOSPLIT, $0-24
	MOVQ p+0(FP), AX
	MOVQ i+8(FP), CX
	MOVQ (AX)(CX*8), AX
	MOVQ AX, ret+16(FP)
	RET

// func Copy16(dst *[16]byte, src *[16]byte)
// Requires: SSE
TEXT ·Copy16(SB), NOSPLIT, $0-16
	MOVQ   dst+0(FP), AX
	MOVQ   src+8(FP), CX
	MOVUPS (CX), X0
	MOVUPS X0, (AX)
	RET

// func Prefetch(p *[64]uint64, i uint64) uint64
// Requires: MMX+
TEXT ·Prefetch(SB), NOSPLIT, $0-24
	MOVQ        p+0(FP), AX
	MOVQ        i+8(FP), CX
	ANDQ        $0x3f, CX
	PREFETCHT0  (AX)
	PREFETCHT1  64(AX)
	PREFETCHT2  32760(AX)
	PREFETCHNTA 4(AX)
	PREFETCHT0  260(AX)
	PREFETCHT0  32768(AX)
	PREFETCHT0  -64(AX)
	PREFETCHT0  (AX)(CX*8)
	PREFETCHT0  8(AX)(CX*1)
	TESTQ       CX, CX
	MOVQ        (AX)(CX*8), DX
	PREFETCHT0  64(AX)(CX*8)
	JZ          prefetch_done
	ADDQ        $0x01, DX

prefetch_done:
	MOVQ DX, ret+16(FP)
	RET

// func LessS(a uint64, b uint64) uint64
TEXT ·LessS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JLT  LessS_yes
	MOVQ $0x0000000000000000, AX
	JMP  LessS_end

LessS_yes:
	MOVQ $0x0000000000000001, AX

LessS_end:
	MOVQ AX, ret+16(FP)
	RET

// func GreaterEqS(a uint64, b uint64) uint64
TEXT ·GreaterEqS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JGE  GreaterEqS_yes
	MOVQ $0x0000000000000000, AX
	JMP  GreaterEqS_end

GreaterEqS_yes:
	MOVQ $0x0000000000000001, AX

GreaterEqS_end:
	MOVQ AX, ret+16(FP)
	RET

// func LessU(a uint64, b uint64) uint64
TEXT ·LessU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JCS  LessU_yes
	MOVQ $0x0000000000000000, AX
	JMP  LessU_end

LessU_yes:
	MOVQ $0x0000000000000001, AX

LessU_end:
	MOVQ AX, ret+16(FP)
	RET

// func AboveU(a uint64, b uint64) uint64
TEXT ·AboveU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JHI  AboveU_yes
	MOVQ $0x0000000000000000, AX
	JMP  AboveU_end

AboveU_yes:
	MOVQ $0x0000000000000001, AX

AboveU_end:
	MOVQ AX, ret+16(FP)
	RET

// func Equal(a uint64, b uint64) uint64
TEXT ·Equal(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JEQ  Equal_yes
	MOVQ $0x0000000000000000, AX
	JMP  Equal_end

Equal_yes:
	MOVQ $0x0000000000000001, AX

Equal_end:
	MOVQ AX, ret+16(FP)
	RET

// func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelectEq(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQEQ DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SubGapEq(x uint64, y uint64) uint64
TEXT ·SubGapEq(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBQ CX, AX
	MOVQ $0x0000000000000000, AX
	JEQ  SubGapEq_yes
	JMP  SubGapEq_end

SubGapEq_yes:
	MOVQ $0x0000000000000001, AX

SubGapEq_end:
	MOVQ AX, ret+16(FP)
	RET

// func DecGapZero(x uint64, y uint64) uint64
TEXT ·DecGapZero(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	DECQ AX
	MOVQ $0x0000000000000000, AX
	JEQ  DecGapZero_yes
	JMP  DecGapZero_end

DecGapZero_yes:
	MOVQ $0x0000000000000001, AX

DecGapZero_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32Eq(a uint64, b uint64) uint64
TEXT ·CmpL32Eq(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JEQ  CmpL32Eq_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32Eq_end

CmpL32Eq_yes:
	MOVQ $0x0000000000000001, AX

CmpL32Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32LessS(a uint64, b uint64) uint64
TEXT ·CmpL32LessS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JLT  CmpL32LessS_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32LessS_end

CmpL32LessS_yes:
	MOVQ $0x0000000000000001, AX

CmpL32LessS_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32LessU(a uint64, b uint64) uint64
TEXT ·CmpL32LessU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JCS  CmpL32LessU_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32LessU_end

CmpL32LessU_yes:
	MOVQ $0x0000000000000001, AX

CmpL32LessU_end:
	MOVQ AX, ret+16(FP)
	RET

// func TestL32(a uint64, m uint64) uint64
TEXT ·TestL32(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  m+8(FP), CX
	TESTL AX, CX
	JEQ   TestL32_zero
	MOVQ  $0x0000000000000000, AX
	JMP   TestL32_end

TestL32_zero:
	MOVQ $0x0000000000000001, AX

TestL32_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpW16Eq(a uint64, b uint64) uint64
TEXT ·CmpW16Eq(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPW AX, CX
	JEQ  CmpW16Eq_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpW16Eq_end

CmpW16Eq_yes:
	MOVQ $0x0000000000000001, AX

CmpW16Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpB8Ne(a uint64, b uint64) uint64
TEXT ·CmpB8Ne(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPB AL, CL
	JNE  CmpB8Ne_diff
	MOVQ $0x0000000000000000, AX
	JMP  CmpB8Ne_end

CmpB8Ne_diff:
	MOVQ $0x0000000000000001, AX

CmpB8Ne_end:
	MOVQ AX, ret+16(FP)
	RET

// func TestW16Eq(a uint64, m uint64) uint64
TEXT ·TestW16Eq(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  m+8(FP), CX
	TESTW AX, CX
	JEQ   TestW16Eq_zero
	MOVQ  $0x0000000000000000, AX
	JMP   TestW16Eq_end

TestW16Eq_zero:
	MOVQ $0x0000000000000001, AX

TestW16Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func IMul2(x uint64, y uint64) uint64
TEXT ·IMul2(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	IMULQ AX, CX
	MOVQ  CX, ret+16(FP)
	RET

// func IMul3(x uint64) uint64
TEXT ·IMul3(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	IMUL3Q $0x9e3779b1, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func MulWide(x uint64, y uint64) (lo uint64, hi uint64)
TEXT ·MulWide(SB), NOSPLIT, $0-32
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), SI
	MULQ SI
	MOVQ AX, lo+16(FP)
	MOVQ DX, hi+24(FP)
	RET

// func IMulWide(x int64, y int64) (lo uint64, hi uint64)
TEXT ·IMulWide(SB), NOSPLIT, $0-32
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), SI
	IMULQ SI
	MOVQ  AX, lo+16(FP)
	MOVQ  DX, hi+24(FP)
	RET

// func MulX(x uint64, y uint64) (lo uint64, hi uint64)
// Requires: BMI2
TEXT ·MulX(SB), NOSPLIT, $0-32
	MOVQ  x+0(FP), SI
	MOVQ  y+8(FP), DX
	MULXQ SI, AX, BX
	MOVQ  AX, lo+16(FP)
	MOVQ  BX, hi+24(FP)
	RET

// func ShlX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShlX(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	SHLXQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func ShrX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShrX(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	SHRXQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func SarX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·SarX(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	SARXQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func RorX(x uint64) uint64
// Requires: BMI2
TEXT ·RorX(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	RORXQ $0x38, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func Bzhi(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·Bzhi(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func Bextr88(x uint64) uint64
// Requires: BMI
TEXT ·Bextr88(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000808, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr4_12(x uint64) uint64
// Requires: BMI
TEXT ·Bextr4_12(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000c04, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr56_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr56_8(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000838, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr8_56(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_56(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00003808, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr8_60(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_60(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00003c08, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr0_0(x uint64) uint64
// Requires: BMI
TEXT ·Bextr0_0(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000000, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr70_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr70_8(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000846, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func BzhiConst13(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst13(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x0000000d, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func BzhiConst0(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst0(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000000, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func BzhiConst64(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst64(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000040, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func ShlXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShlXConst9(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000009, CX
	SHLXQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func ShrXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShrXConst9(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000009, CX
	SHRXQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func SetGe(a uint64, b uint64) uint64
TEXT ·SetGe(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  b+8(FP), CX
	XORL  DX, DX
	CMPQ  AX, CX
	SETGE DL
	MOVQ  DX, ret+16(FP)
	RET

// func AdcAccum(x uint64, acc uint64) uint64
TEXT ·AdcAccum(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ acc+8(FP), CX
	CMPQ AX, $0x04
	ADCB $+0, CL
	MOVQ CX, ret+16(FP)
	RET

// func BswapL(x uint64) uint64
TEXT ·BswapL(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	BSWAPL AX
	MOVQ   AX, ret+8(FP)
	RET

// func AddByte(x uint64, y uint64) uint64
TEXT ·AddByte(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDB AL, CL
	MOVQ CX, ret+16(FP)
	RET

// func MovbHighDst(x uint64, y uint64) uint64
TEXT ·MovbHighDst(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), CX
	MOVQ y+8(FP), AX
	MOVB CL, AH
	MOVQ AX, ret+16(FP)
	RET

// func MovbLowPreserve(x uint64, y uint64) uint64
TEXT ·MovbLowPreserve(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), CX
	MOVQ y+8(FP), AX
	MOVB CH, AL
	MOVQ AX, ret+16(FP)
	RET

// func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLtS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQLT DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLeS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQLE DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGtS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQGT DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGeS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQGE DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLsU(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQLS DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelMi(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelMi(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQMI DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelPl(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelPl(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQPL DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SxL(x uint64) uint64
TEXT ·SxL(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVLQSX AX, AX
	MOVQ    AX, ret+8(FP)
	RET

// func SxB(x uint64) uint64
TEXT ·SxB(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVBQSX AL, AX
	MOVQ    AX, ret+8(FP)
	RET

// func SxBL(x uint64) uint64
TEXT ·SxBL(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVBLSX AL, AX
	MOVQ    AX, ret+8(FP)
	RET

// func SxWL(x uint64) uint64
TEXT ·SxWL(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVWLSX AX, AX
	MOVQ    AX, ret+8(FP)
	RET

// func NegL(x uint64) uint64
TEXT ·NegL(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	NEGL AX
	MOVQ AX, ret+8(FP)
	RET

// func NotL(x uint64) uint64
TEXT ·NotL(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	NOTL AX
	MOVQ AX, ret+8(FP)
	RET

// func NotQ(x uint64) uint64
TEXT ·NotQ(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	NOTQ AX
	MOVQ AX, ret+8(FP)
	RET

// func RolL7(x uint64) uint64
TEXT ·RolL7(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	ROLL $0x07, AX
	MOVQ AX, ret+8(FP)
	RET

// func RorQ9(x uint64) uint64
TEXT ·RorQ9(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	RORQ $0x09, AX
	MOVQ AX, ret+8(FP)
	RET

// func RorL9(x uint64) uint64
TEXT ·RorL9(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	RORL $0x09, AX
	MOVQ AX, ret+8(FP)
	RET

// func BtrQ5(x uint64) uint64
TEXT ·BtrQ5(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVQ $0x0000000000000005, CX
	BTRQ CX, AX
	MOVQ AX, ret+8(FP)
	RET

// func BtcQ5(x uint64) uint64
TEXT ·BtcQ5(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVQ $0x0000000000000005, CX
	BTCQ CX, AX
	MOVQ AX, ret+8(FP)
	RET

// func PopcntQ(x uint64) uint64
// Requires: POPCNT
TEXT ·PopcntQ(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	POPCNTQ AX, AX
	MOVQ    AX, ret+8(FP)
	RET

// func SarQ3(x uint64) uint64
TEXT ·SarQ3(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SARQ $0x03, AX
	MOVQ AX, ret+8(FP)
	RET

// func SarL3(x uint64) uint64
TEXT ·SarL3(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SARL $0x03, AX
	MOVQ AX, ret+8(FP)
	RET

// func IncL(x uint64) uint64
TEXT ·IncL(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	INCL AX
	MOVQ AX, ret+8(FP)
	RET

// func ShlB2(x uint64) uint64
TEXT ·ShlB2(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SHLB $0x02, AL
	MOVQ AX, ret+8(FP)
	RET

// func BsfQ(x uint64) uint64
TEXT ·BsfQ(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	BSFQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func TzcntQ(x uint64) uint64
// Requires: BMI
TEXT ·TzcntQ(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	TZCNTQ AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func AddL(x uint64, y uint64) uint64
TEXT ·AddL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDL CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func SubL(x uint64, y uint64) uint64
TEXT ·SubL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBL CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func AndL(x uint64, y uint64) uint64
TEXT ·AndL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ANDL CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func OrL(x uint64, y uint64) uint64
TEXT ·OrL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ORL  CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func ImulL(x uint64, y uint64) uint64
TEXT ·ImulL(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	IMULL CX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func XchgQ(x uint64, y uint64) uint64
TEXT ·XchgQ(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	MOVQ  CX, CX
	XCHGQ AX, CX
	MOVQ  AX, ret+16(FP)
	RET

// func LeaL(x uint64, y uint64) uint64
TEXT ·LeaL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	LEAL 7(AX)(CX*4), AX
	MOVQ AX, ret+16(FP)
	RET

// func VecZero(dst *[16]byte)
// Requires: SSE2
TEXT ·VecZero(SB), NOSPLIT, $0-8
	MOVQ  dst+0(FP), AX
	PXOR  X0, X0
	MOVOU X0, (AX)
	RET

// func VecCopyIdx(dst *[32]byte, src *[32]byte, i uint64)
// Requires: SSE2
TEXT ·VecCopyIdx(SB), NOSPLIT, $0-24
	MOVQ  dst+0(FP), AX
	MOVQ  src+8(FP), CX
	MOVQ  i+16(FP), DX
	MOVOU (CX)(DX*1), X0
	MOVOU X0, (AX)(DX*1)
	RET

// func VecCopy(dst *[32]byte, src *[32]byte)
// Requires: SSE2
TEXT ·VecCopy(SB), NOSPLIT, $0-16
	MOVQ  dst+0(FP), AX
	MOVQ  src+8(FP), CX
	MOVOU 16(CX), X0
	MOVOU X0, 16(AX)
	RET

// func Prop0(x uint64, y uint64) uint64
TEXT ·Prop0(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	SARQ    $0x05, AX
	ROLL    $0x05, AX
	ANDL    CX, AX
	XORQ    AX, AX
	SARQ    $0x05, AX
	SHLB    $0x02, AL
	XORQ    AX, AX
	NEGQ    AX
	ORQ     CX, AX
	MOVWQZX AX, AX
	ANDQ    CX, AX
	MOVL    CX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop1(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop1(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	XORQ    AX, AX
	ROLQ    $0x0d, AX
	CMPQ    AX, CX
	CMOVQEQ CX, AX
	XORQ    CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	NOTQ    AX
	ROLQ    $0x0d, AX
	MOVLQSX AX, AX
	ANDQ    CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	POPCNTQ AX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop2(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop2(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	CMPQ    AX, CX
	CMOVQEQ CX, AX
	NEGQ    AX
	ADDL    CX, AX
	MOVL    CX, AX
	MOVWQZX AX, AX
	ROLQ    $0x0d, AX
	SUBL    CX, AX
	IMULQ   CX, AX
	MOVB    CL, AL
	BSWAPL  AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	ADDB    CL, AL
	MOVQ    AX, ret+16(FP)
	RET

// func Prop3(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop3(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVLQSX AX, AX
	SUBQ    CX, AX
	CMPQ    AX, CX
	SETLT   AL
	MOVB    CL, AL
	CMPQ    AX, CX
	CMOVQEQ CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	SHLQ    $0x03, AX
	ADDB    CL, AL
	MOVWQZX AX, AX
	TZCNTQ  AX, AX
	IMULL   CX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop4(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop4(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	ROLL    $0x05, AX
	ROLL    $0x05, AX
	IMULQ   CX, AX
	ADDQ    CX, AX
	MOVWQZX AX, AX
	XORQ    AX, AX
	NOTQ    AX
	SHLQ    $0x03, AX
	ADDQ    CX, AX
	SHRQ    $0x07, AX
	TZCNTQ  AX, AX
	ADDQ    CX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop5(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop5(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	ANDL    CX, AX
	SHRQ    $0x07, AX
	SHLL    $0x09, AX
	SHLL    $0x09, AX
	XORQ    AX, AX
	IMULL   CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	SUBL    CX, AX
	TZCNTQ  AX, AX
	SHLL    $0x09, AX
	ROLQ    $0x0d, AX
	MOVB    CL, AL
	MOVQ    AX, ret+16(FP)
	RET

// func Prop6(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop6(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVL    CX, AX
	SHLB    $0x02, AL
	CMPQ    AX, CX
	CMOVQEQ CX, AX
	TZCNTQ  AX, AX
	ORQ     CX, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	IMULL   CX, AX
	MOVLQSX AX, AX
	CMPQ    AX, CX
	CMOVQEQ CX, AX
	SARQ    $0x05, AX
	SHRQ    $0x07, AX
	MOVLQSX AX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop7(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop7(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	SHLL    $0x09, AX
	ANDQ    CX, AX
	IMULL   CX, AX
	ADDL    CX, AX
	ADDQ    CX, AX
	SUBL    CX, AX
	CMPQ    AX, CX
	CMOVQEQ CX, AX
	NEGQ    AX
	ROLQ    $0x0d, AX
	ADDQ    CX, AX
	ROLL    $0x05, AX
	MOVLQSX AX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop8(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop8(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	ADDL    CX, AX
	ROLL    $0x05, AX
	ADDL    CX, AX
	NEGQ    AX
	MOVB    CL, AL
	ADDB    CL, AL
	POPCNTQ AX, AX
	SHLL    $0x09, AX
	IMULQ   CX, AX
	ANDQ    CX, AX
	XORQ    AX, AX
	CMPQ    AX, CX
	SETLT   AL
	MOVQ    AX, ret+16(FP)
	RET

// func Prop9(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop9(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	ADDL    CX, AX
	ADDB    CL, AL
	IMULL   CX, AX
	ADDB    CL, AL
	ROLL    $0x05, AX
	SUBQ    CX, AX
	NEGQ    AX
	POPCNTQ AX, AX
	ADDL    CX, AX
	IMULL   CX, AX
	SHLB    $0x02, AL
	NOTQ    AX
	MOVQ    AX, ret+16(FP)
	RET

// func Prop10(x uint64, y uint64) uint64
// Requires: BMI, POPCNT
TEXT ·Prop10(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	IMULQ   CX, AX
	POPCNTQ AX, AX
	ADDL    CX, AX
	TZCNTQ  AX, AX
	ADDB    CL, AL
	ROLQ    $0x0d, AX
	SUBL    CX, AX
	IMULQ   CX, AX
	POPCNTQ AX, AX
	IMULQ   CX, AX
	NOTQ    AX
	ADDB    CL, AL
	MOVQ    AX, ret+16(FP)
	RET

// func Prop11(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop11(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	ANDL    CX, AX
	NOTQ    AX
	POPCNTQ AX, AX
	ROLL    $0x05, AX
	ADDL    CX, AX
	ROLL    $0x05, AX
	CMPQ    AX, CX
	CMOVQCS CX, AX
	CMPQ    AX, CX
	SETLT   AL
	SARQ    $0x05, AX
	MOVB    CL, AL
	IMULL   CX, AX
	POPCNTQ AX, AX
	MOVQ    AX, ret+16(FP)
	RET

// func MemProp0(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp0(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	CMPQ    AX, (DX)(BX*8)
	CMOVQCS CX, AX
	ROLQ    $0x0b, AX
	MOVWQZX 2(DX), AX
	ADDL    (DX)(BX*8), AX
	INCQ    BX
	ANDQ    $0x00000003, BX
	ADDL    (DX)(BX*8), AX
	XORQ    (DX)(BX*8), AX
	MOVQ    AX, (DX)(BX*8)
	ROLQ    $0x0b, AX
	ADDQ    (DX)(BX*8), AX
	MOVQ    AX, (DX)(BX*8)
	SUBQ    CX, AX
	ADDQ    (DX)(BX*8), AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp1(x uint64, y uint64, p *[8]uint64) uint64
TEXT ·MemProp1(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	IMULQ   16(DX), AX
	LEAQ    8(DX)(BX*8), AX
	SUBQ    DX, AX
	SUBQ    CX, AX
	MOVQ    AX, (DX)(BX*8)
	IMULQ   16(DX), AX
	MOVQ    AX, (DX)(BX*8)
	ADDL    (DX)(BX*8), AX
	INCQ    BX
	ANDQ    $0x00000003, BX
	ADDL    (DX)(BX*8), AX
	INCQ    BX
	ANDQ    $0x00000003, BX
	MOVLQSX 8(DX), AX
	ROLQ    $0x0b, AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp2(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp2(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	IMULQ   16(DX), AX
	MOVLQSX 8(DX), AX
	ROLQ    $0x0b, AX
	MOVQ    AX, (DX)(BX*8)
	ADDQ    8(DX)(BX*8), AX
	ROLQ    $0x0b, AX
	MOVQ    AX, (DX)(BX*8)
	CMPQ    AX, (DX)(BX*8)
	CMOVQCS CX, AX
	SUBQ    CX, AX
	ADDQ    CX, AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp3(x uint64, y uint64, p *[8]uint64) uint64
TEXT ·MemProp3(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	ANDQ    $0x00000003, CX
	MOVL    AX, 24(DX)
	MOVL    4(DX), AX
	MOVB    1(DX), AL
	MOVB    1(DX), AL
	MOVL    AX, 24(DX)
	MOVWQZX 2(DX), AX
	MOVL    4(DX), AX
	ROLQ    $0x0b, AX
	ADDL    (DX)(CX*8), AX
	INCQ    CX
	ANDQ    $0x00000003, CX
	ADDL    (DX)(CX*8), AX
	MOVLQSX 8(DX), AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp4(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp4(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	XORQ    (DX)(BX*8), AX
	ADDL    (DX)(BX*8), AX
	INCQ    BX
	ANDQ    $0x00000003, BX
	ADDL    (DX)(BX*8), AX
	ADDQ    CX, AX
	ADDQ    (DX)(BX*8), AX
	MOVB    1(DX), AL
	MOVWQZX 2(DX), AX
	CMPQ    AX, (DX)(BX*8)
	CMOVQCS CX, AX
	ADDQ    (DX)(BX*8), AX
	MOVL    4(DX), AX
	SUBQ    CX, AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp5(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp5(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	ADDL    (DX)(BX*8), AX
	INCQ    BX
	ANDQ    $0x00000003, BX
	ADDL    (DX)(BX*8), AX
	IMULQ   16(DX), AX
	ADDL    (DX)(BX*8), AX
	IMULQ   16(DX), AX
	MOVQ    AX, (DX)(BX*8)
	LEAQ    8(DX)(BX*8), AX
	SUBQ    DX, AX
	ADDQ    CX, AX
	IMULQ   16(DX), AX
	MOVL    4(DX), AX
	CMPQ    AX, (DX)(BX*8)
	CMOVQCS CX, AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp6(x uint64, y uint64, p *[8]uint64) uint64
// Requires: CMOV
TEXT ·MemProp6(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	ADDQ    CX, AX
	CMPQ    AX, (DX)(BX*8)
	CMOVQCS CX, AX
	SUBQ    CX, AX
	ROLQ    $0x0b, AX
	ADDL    (DX)(BX*8), AX
	INCQ    BX
	ANDQ    $0x00000003, BX
	ADDL    (DX)(BX*8), AX
	SUBQ    CX, AX
	MOVWQZX 2(DX), AX
	CMPQ    AX, (DX)(BX*8)
	CMOVQCS CX, AX
	ROLQ    $0x0b, AX
	LEAQ    8(DX)(BX*8), AX
	SUBQ    DX, AX
	MOVQ    AX, ret+24(FP)
	RET

// func MemProp7(x uint64, y uint64, p *[8]uint64) uint64
TEXT ·MemProp7(SB), NOSPLIT, $0-32
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	MOVQ    p+16(FP), DX
	MOVQ    CX, BX
	ANDQ    $0x00000003, BX
	LEAQ    8(DX)(BX*8), AX
	SUBQ    DX, AX
	MOVQ    AX, (DX)(BX*8)
	ADDQ    (DX)(BX*8), AX
	MOVL    4(DX), AX
	MOVQ    AX, (DX)(BX*8)
	ADDL    (DX)(BX*8), AX
	MOVWQZX 2(DX), AX
	ADDL    (DX)(BX*8), AX
	MOVL    AX, 24(DX)
	ADDQ    CX, AX
	MOVQ    AX, ret+24(FP)
	RET

// func BtBranch(x uint64) uint64
TEXT ·BtBranch(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	BTL  $0x00, AX
	JC   BtBranch_taken
	MOVQ $0x0000000000000014, AX
	JMP  BtBranch_end

BtBranch_taken:
	MOVQ $0x000000000000000a, AX

BtBranch_end:
	MOVQ AX, ret+8(FP)
	RET

// func BtBranchHigh(x uint64) uint64
TEXT ·BtBranchHigh(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	BTL  $0x03, AX
	JC   BtBranchHigh_taken
	MOVQ $0x0000000000000014, AX
	JMP  BtBranchHigh_end

BtBranchHigh_taken:
	MOVQ $0x000000000000000a, AX

BtBranchHigh_end:
	MOVQ AX, ret+8(FP)
	RET

// func BtBranchClear(x uint64) uint64
TEXT ·BtBranchClear(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	BTL  $0x00, AX
	JNC  BtBranchClear_taken
	MOVQ $0x0000000000000014, AX
	JMP  BtBranchClear_end

BtBranchClear_taken:
	MOVQ $0x000000000000000a, AX

BtBranchClear_end:
	MOVQ AX, ret+8(FP)
	RET

// func BtBranchClearHigh(x uint64) uint64
TEXT ·BtBranchClearHigh(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	BTL  $0x03, AX
	JNC  BtBranchClearHigh_taken
	MOVQ $0x0000000000000014, AX
	JMP  BtBranchClearHigh_end

BtBranchClearHigh_taken:
	MOVQ $0x000000000000000a, AX

BtBranchClearHigh_end:
	MOVQ AX, ret+8(FP)
	RET

// func MovwzxL(p *[4]uint16, i uint64) uint64
TEXT ·MovwzxL(SB), NOSPLIT, $0-24
	MOVQ    p+0(FP), AX
	MOVQ    i+8(FP), CX
	MOVQ    $0xffffffffffffffff, DX
	MOVWLZX (AX)(CX*2), DX
	MOVQ    DX, ret+16(FP)
	RET

// func MovbzxHigh(x uint64) uint64
TEXT ·MovbzxHigh(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVBLZX AH, BX
	MOVQ    BX, ret+8(FP)
	RET

// func CmovL32(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·CmovL32(SB), NOSPLIT, $0-24
	MOVQ    x+0(FP), AX
	MOVQ    y+8(FP), CX
	CMPQ    AX, AX
	CMOVLNE AX, CX
	MOVQ    CX, ret+16(FP)
	RET

// func BextrMem(p *[4]uint64, i uint64, ctrl uint64) uint64
// Requires: BMI
TEXT ·BextrMem(SB), NOSPLIT, $0-32
	MOVQ   p+0(FP), AX
	MOVQ   i+8(FP), CX
	MOVQ   ctrl+16(FP), DX
	BEXTRQ DX, (AX)(CX*8), AX
	MOVQ   AX, ret+24(FP)
	RET

// func XorSelfEq(x uint64) uint64
TEXT ·XorSelfEq(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	XORQ AX, AX
	JEQ  xorself_yes
	MOVQ $0x0000000000000000, AX
	JMP  xorself_end

xorself_yes:
	MOVQ $0x0000000000000001, AX

xorself_end:
	MOVQ AX, ret+8(FP)
	RET

// func MovLNegImm() uint64
TEXT ·MovLNegImm(SB), NOSPLIT, $0-8
	MOVL $-1, AX
	MOVQ AX, ret+0(FP)
	RET

// func IncLMem(p *[2]uint32)
TEXT ·IncLMem(SB), NOSPLIT, $0-8
	MOVQ p+0(FP), AX
	INCL (AX)
	RET

// func DecLMem(p *[2]uint32)
TEXT ·DecLMem(SB), NOSPLIT, $0-8
	MOVQ p+0(FP), AX
	DECL (AX)
	RET

// func IncQMem(p *[2]uint64)
TEXT ·IncQMem(SB), NOSPLIT, $0-8
	MOVQ p+0(FP), AX
	INCQ (AX)
	RET

// func CmpBHigh(x uint64) uint64
TEXT ·CmpBHigh(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	XORQ  BX, BX
	CMPB  AH, $0x02
	SETEQ BL
	MOVQ  BX, ret+8(FP)
	RET

// func MovWLoad(x uint64, p *uint16) uint64
TEXT ·MovWLoad(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ p+8(FP), CX
	MOVW (CX), AX
	MOVQ AX, ret+16(FP)
	RET

// func MulXAlias(x uint64, y uint64) uint64
// Requires: BMI2
TEXT ·MulXAlias(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), SI
	MOVQ  y+8(FP), DX
	MULXQ SI, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func TestQImm(x uint64, y uint64) uint64
TEXT ·TestQImm(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	XORQ  CX, CX
	TESTQ $0x00000010, AX
	SETEQ CL
	MOVQ  CX, ret+16(FP)
	RET

// func FlagsAcrossTransparent(a uint64, b uint64) uint64
TEXT ·FlagsAcrossTransparent(SB), NOSPLIT, $0-24
	MOVQ   a+0(FP), AX
	MOVQ   b+8(FP), CX
	CMPQ   AX, CX
	NOTQ   AX
	BSWAPL AX
	XCHGQ  AX, DX
	JEQ    fat_eq
	MOVQ   $0x0000000000000000, DX
	JMP    fat_end

fat_eq:
	MOVQ $0x0000000000000001, DX

fat_end:
	MOVQ DX, ret+16(FP)
	RET

// func XorlSign(x uint64, y uint64) uint64
TEXT ·XorlSign(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	XORL CX, AX
	JMI  xorlsign_neg
	MOVQ $0x0000000000000000, AX
	JMP  xorlsign_end

xorlsign_neg:
	MOVQ $0x0000000000000001, AX

xorlsign_end:
	MOVQ AX, ret+16(FP)
	RET

// func XorlMem(p *[2]uint32, v uint64)
TEXT ·XorlMem(SB), NOSPLIT, $0-16
	MOVQ p+0(FP), AX
	MOVQ v+8(FP), CX
	XORL CX, (AX)
	RET

// func BzhiConst256(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst256(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x0000000000000100, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func BzhiConstNeg(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConstNeg(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $-1, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func AndQBit31(x uint64) uint64
TEXT ·AndQBit31(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	ANDQ $0x80000000, AX
	MOVQ AX, ret+8(FP)
	RET

// func AddQBit31(x uint64) uint64
TEXT ·AddQBit31(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	ADDQ $0x80000000, AX
	MOVQ AX, ret+8(FP)
	RET

// func OrQBit31(x uint64) uint64
TEXT ·OrQBit31(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	ORQ  $0xffffffe0, AX
	MOVQ AX, ret+8(FP)
	RET

// func CmpQBit31(x uint64) uint64
TEXT ·CmpQBit31(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	CMPQ AX, $0x80000000
	JEQ  cqb_eq
	MOVQ $0x0000000000000000, AX
	JMP  cqb_end

cqb_eq:
	MOVQ $0x0000000000000001, AX

cqb_end:
	MOVQ AX, ret+8(FP)
	RET

// func TestQBit31(x uint64) uint64
TEXT ·TestQBit31(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	XORQ  CX, CX
	TESTQ $0x80000000, AX
	SETEQ CL
	MOVQ  CX, ret+8(FP)
	RET

// func MovQBit31Mem(p *uint64)
TEXT ·MovQBit31Mem(SB), NOSPLIT, $0-8
	MOVQ p+0(FP), AX
	MOVQ $0x80000000, (AX)
	RET

// func MovQBit31Reg() uint64
TEXT ·MovQBit31Reg(SB), NOSPLIT, $0-8
	MOVQ $0x80000000, AX
	MOVQ AX, ret+0(FP)
	RET

// func CmpLIntMin(x uint64) uint64
TEXT ·CmpLIntMin(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	XORQ  CX, CX
	XORQ  DX, DX
	CMPL  AX, $-2147483648
	SETLT DL
	ORQ   DX, CX
	XORQ  DX, DX
	CMPL  AX, $-2147483648
	SETGE DL
	SHLQ  $0x01, DX
	ORQ   DX, CX
	XORQ  DX, DX
	CMPL  AX, $-2147483648
	SETGT DL
	SHLQ  $0x02, DX
	ORQ   DX, CX
	XORQ  DX, DX
	CMPL  AX, $-2147483648
	SETLE DL
	SHLQ  $0x03, DX
	ORQ   DX, CX
	MOVQ  CX, ret+8(FP)
	RET

// func ShrQ64(x uint64) uint64
TEXT ·ShrQ64(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SHRQ $0x40, AX
	MOVQ AX, ret+8(FP)
	RET

// func ShrQ65(x uint64) uint64
TEXT ·ShrQ65(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SHRQ $0x41, AX
	MOVQ AX, ret+8(FP)
	RET

// func ShlQ64(x uint64) uint64
TEXT ·ShlQ64(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SHLQ $0x40, AX
	MOVQ AX, ret+8(FP)
	RET

// func ShrL32(x uint64) uint64
TEXT ·ShrL32(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SHRL $0x20, AX
	MOVQ AX, ret+8(FP)
	RET

// func IncQ(x uint64) uint64
TEXT ·IncQ(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	INCQ AX
	MOVQ AX, ret+8(FP)
	RET

// func DecL(x uint64) uint64
TEXT ·DecL(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	DECL AX
	MOVQ AX, ret+8(FP)
	RET

// func ShrL5(x uint64) uint64
TEXT ·ShrL5(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	SHRL $0x05, AX
	MOVQ AX, ret+8(FP)
	RET

// func SxWQ(x uint64) uint64
TEXT ·SxWQ(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVWQSX AX, AX
	MOVQ    AX, ret+8(FP)
	RET

// func BsrQ(x uint64) uint64
TEXT ·BsrQ(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	BSRQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func BtsQ5(x uint64) uint64
TEXT ·BtsQ5(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVQ $0x0000000000000005, CX
	BTSQ CX, AX
	MOVQ AX, ret+8(FP)
	RET

// func ZxLQ(p *uint64) uint64
TEXT ·ZxLQ(SB), NOSPLIT, $0-16
	MOVQ    p+0(FP), AX
	MOVLQZX (AX), AX
	MOVQ    AX, ret+8(FP)
	RET

// func MovW(x uint64, y uint64) uint64
TEXT ·MovW(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	MOVW CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func LeaQ(x uint64, y uint64) uint64
TEXT ·LeaQ(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	LEAQ -24(AX)(CX*8), AX
	MOVQ AX, ret+16(FP)
	RET

// func TestQZero(x uint64, y uint64) uint64
TEXT ·TestQZero(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	XORQ  DX, DX
	TESTQ AX, CX
	SETEQ DL
	MOVQ  DX, ret+16(FP)
	RET

// func TestBZero(x uint64, y uint64) uint64
TEXT ·TestBZero(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	XORQ  DX, DX
	TESTB AL, CL
	SETEQ DL
	MOVQ  DX, ret+16(FP)
	RET

// func TestBSelfZero(x uint64) uint64
TEXT ·TestBSelfZero(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	XORQ  CX, CX
	TESTB AL, AL
	SETEQ CL
	MOVQ  CX, ret+8(FP)
	RET

// func TestWSelfZero(x uint64) uint64
TEXT ·TestWSelfZero(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	XORQ  CX, CX
	TESTW AX, AX
	SETEQ CL
	MOVQ  CX, ret+8(FP)
	RET

// func VecCopyReg(dst *[16]byte, src *[16]byte)
// Requires: SSE2
TEXT ·VecCopyReg(SB), NOSPLIT, $0-16
	MOVQ  dst+0(FP), AX
	MOVQ  src+8(FP), CX
	MOVOU (CX), X0
	MOVOA X0, X0
	MOVOU X0, (AX)
	RET

// func SetAll(a uint64, b uint64) uint64
TEXT ·SetAll(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  b+8(FP), CX
	XORQ  DX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETEQ BL
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETNE BL
	SHLQ  $0x01, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETLT BL
	SHLQ  $0x02, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETLE BL
	SHLQ  $0x03, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETGT BL
	SHLQ  $0x04, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETGE BL
	SHLQ  $0x05, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETCS BL
	SHLQ  $0x06, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETCC BL
	SHLQ  $0x07, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETHI BL
	SHLQ  $0x08, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETLS BL
	SHLQ  $0x09, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETMI BL
	SHLQ  $0x0a, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETPL BL
	SHLQ  $0x0b, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETOS BL
	SHLQ  $0x0c, BX
	ORQ   BX, DX
	XORQ  BX, BX
	CMPQ  AX, CX
	SETOC BL
	SHLQ  $0x0d, BX
	ORQ   BX, DX
	MOVQ  DX, ret+16(FP)
	RET

// func JmpAll(a uint64, b uint64) uint64
TEXT ·JmpAll(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	XORQ DX, DX
	CMPQ AX, CX
	JEQ  jmpall_0_taken
	JMP  jmpall_0_done

jmpall_0_taken:
	ORQ $0x00000001, DX

jmpall_0_done:
	CMPQ AX, CX
	JNE  jmpall_1_taken
	JMP  jmpall_1_done

jmpall_1_taken:
	ORQ $0x00000002, DX

jmpall_1_done:
	CMPQ AX, CX
	JLT  jmpall_2_taken
	JMP  jmpall_2_done

jmpall_2_taken:
	ORQ $0x00000004, DX

jmpall_2_done:
	CMPQ AX, CX
	JLE  jmpall_3_taken
	JMP  jmpall_3_done

jmpall_3_taken:
	ORQ $0x00000008, DX

jmpall_3_done:
	CMPQ AX, CX
	JGT  jmpall_4_taken
	JMP  jmpall_4_done

jmpall_4_taken:
	ORQ $0x00000010, DX

jmpall_4_done:
	CMPQ AX, CX
	JGE  jmpall_5_taken
	JMP  jmpall_5_done

jmpall_5_taken:
	ORQ $0x00000020, DX

jmpall_5_done:
	CMPQ AX, CX
	JCS  jmpall_6_taken
	JMP  jmpall_6_done

jmpall_6_taken:
	ORQ $0x00000040, DX

jmpall_6_done:
	CMPQ AX, CX
	JCC  jmpall_7_taken
	JMP  jmpall_7_done

jmpall_7_taken:
	ORQ $0x00000080, DX

jmpall_7_done:
	CMPQ AX, CX
	JHI  jmpall_8_taken
	JMP  jmpall_8_done

jmpall_8_taken:
	ORQ $0x00000100, DX

jmpall_8_done:
	CMPQ AX, CX
	JLS  jmpall_9_taken
	JMP  jmpall_9_done

jmpall_9_taken:
	ORQ $0x00000200, DX

jmpall_9_done:
	CMPQ AX, CX
	JMI  jmpall_10_taken
	JMP  jmpall_10_done

jmpall_10_taken:
	ORQ $0x00000400, DX

jmpall_10_done:
	CMPQ AX, CX
	JPL  jmpall_11_taken
	JMP  jmpall_11_done

jmpall_11_taken:
	ORQ $0x00000800, DX

jmpall_11_done:
	CMPQ AX, CX
	JOS  jmpall_12_taken
	JMP  jmpall_12_done

jmpall_12_taken:
	ORQ $0x00001000, DX

jmpall_12_done:
	CMPQ AX, CX
	JOC  jmpall_13_taken
	JMP  jmpall_13_done

jmpall_13_taken:
	ORQ $0x00002000, DX

jmpall_13_done:
	MOVQ DX, ret+16(FP)
	RET

// func CmovAll(a uint64, b uint64) uint64
// Requires: CMOV
TEXT ·CmovAll(SB), NOSPLIT, $0-24
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	XORQ    DX, DX
	MOVQ    $0x0000000000000001, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQEQ BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000002, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQNE BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000004, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQLT BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000008, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQLE BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000010, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQGT BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000020, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQGE BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000040, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQCS BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000080, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQCC BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000100, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQHI BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000200, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQLS BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000400, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQMI BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000000800, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQPL BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000001000, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQOS BX, SI
	ORQ     SI, DX
	MOVQ    $0x0000000000002000, BX
	XORQ    SI, SI
	CMPQ    AX, CX
	CMOVQOC BX, SI
	ORQ     SI, DX
	MOVQ    DX, ret+16(FP)
	RET

// func ShlCountFold(x uint64, n uint64) uint64
TEXT ·ShlCountFold(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), DX
	MOVQ DX, CX
	MOVQ AX, BX
	SHLQ CL, BX
	MOVQ AX, CX
	ADDQ CX, BX
	ADDQ DX, BX
	MOVQ BX, ret+16(FP)
	RET

// func ShrCountFold32(x uint64, n uint64) uint64
TEXT ·ShrCountFold32(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), DX
	MOVQ DX, CX
	MOVQ AX, BX
	SHRL CL, BX
	MOVQ AX, CX
	ADDQ CX, BX
	ADDQ DX, BX
	MOVQ BX, ret+16(FP)
	RET

// func RolCountFold(x uint64, n uint64) uint64
TEXT ·RolCountFold(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), DX
	MOVQ DX, CX
	MOVQ AX, BX
	ROLQ CL, BX
	MOVQ AX, CX
	ADDQ CX, BX
	ADDQ DX, BX
	MOVQ BX, ret+16(FP)
	RET

// func CountFoldRefusedRead(x uint64, n uint64) uint64
TEXT ·CountFoldRefusedRead(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), DX
	MOVQ DX, CX
	SHLQ CL, AX
	ADDQ CX, AX
	ADDQ DX, AX
	MOVQ AX, ret+16(FP)
	RET

// func ShlCountSelf(n uint64) uint64
TEXT ·ShlCountSelf(SB), NOSPLIT, $0-16
	MOVQ n+0(FP), AX
	MOVQ AX, CX
	SHLQ CL, CX
	ADDQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func SarCopyFold(x uint64) uint64
TEXT ·SarCopyFold(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVQ AX, CX
	SARQ $0x03, CX
	ADDQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func ShlCopyFoldCX(x uint64) uint64
TEXT ·ShlCopyFoldCX(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVQ AX, CX
	SHLQ $0x02, CX
	ADDQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func AdcAccumQ(x uint64, acc uint64) uint64
TEXT ·AdcAccumQ(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ acc+8(FP), CX
	CMPQ AX, $0x04
	ADCQ $+0, CX
	MOVQ CX, ret+16(FP)
	RET

// func SetGeZeroMov(a uint64, b uint64) uint64
TEXT ·SetGeZeroMov(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  b+8(FP), CX
	MOVQ  $0x00000000, DX
	CMPQ  AX, CX
	SETGE DL
	MOVQ  DX, ret+16(FP)
	RET

// func SetGeRefusedRead(a uint64, b uint64) uint64
TEXT ·SetGeRefusedRead(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  b+8(FP), CX
	XORQ  DX, DX
	ADDQ  DX, AX
	CMPQ  AX, CX
	SETGE DL
	MOVQ  DX, ret+16(FP)
	RET
