#!/bin/sh
# Regenerates prop_table.go for the two random-program families.
n=$(grep -oE 'NumPrograms = [0-9]+' propspec/propspec.go | grep -oE '[0-9]+')
m=$(grep -oE 'NumMemPrograms   = [0-9]+' propspec/propspec.go | grep -oE '[0-9]+')
{
	echo "// Code generated by prop_table.sh. DO NOT EDIT."
	echo
	echo "package arm64lower"
	echo
	echo 'import "github.com/mmcloughlin/avo/tests/arm64lower/propspec"'
	echo
	echo "// propPrograms indexes the generated Prop<n> functions so the test can drive"
	echo "// them in a loop. avo's stub printer emits plain function declarations, so this"
	echo "// table is the small amount of glue that turns them into a slice."
	echo "var propPrograms = [...]func(x, y uint64) uint64{"
	i=0
	while [ "$i" -lt "$n" ]; do echo "	Prop$i,"; i=$((i+1)); done
	echo "}"
	echo
	echo "// Fails to compile if the table and propspec.NumPrograms drift apart."
	echo 'var _ = [1]struct{}{}[len(propPrograms)-propspec.NumPrograms]'
	echo
	echo "// memPropPrograms is the same glue for the memory-operand family."
	echo "var memPropPrograms = [...]func(x, y uint64, p *[8]uint64) uint64{"
	i=0
	while [ "$i" -lt "$m" ]; do echo "	MemProp$i,"; i=$((i+1)); done
	echo "}"
	echo
	echo 'var _ = [1]struct{}{}[len(memPropPrograms)-propspec.NumMemPrograms]'
} > prop_table.go
