// Code generated by prop_table.sh. DO NOT EDIT.

package arm64lower

import "github.com/mmcloughlin/avo/tests/arm64lower/propspec"

// propPrograms indexes the generated Prop<n> functions so the test can drive
// them in a loop. avo's stub printer emits plain function declarations, so this
// table is the small amount of glue that turns them into a slice.
var propPrograms = [...]func(x, y uint64) uint64{
	Prop0,
	Prop1,
	Prop2,
	Prop3,
	Prop4,
	Prop5,
	Prop6,
	Prop7,
	Prop8,
	Prop9,
	Prop10,
	Prop11,
}

// Fails to compile if the table and propspec.NumPrograms drift apart.
var _ = [1]struct{}{}[len(propPrograms)-propspec.NumPrograms]

// memPropPrograms is the same glue for the memory-operand family.
var memPropPrograms = [...]func(x, y uint64, p *[8]uint64) uint64{
	MemProp0,
	MemProp1,
	MemProp2,
	MemProp3,
	MemProp4,
	MemProp5,
	MemProp6,
	MemProp7,
}

var _ = [1]struct{}{}[len(memPropPrograms)-propspec.NumMemPrograms]

// slotPropPrograms is the same glue for the frame-slot family.
var slotPropPrograms = [...]func(x, y uint64) uint64{
	SlotProp0,
	SlotProp1,
	SlotProp2,
	SlotProp3,
	SlotProp4,
	SlotProp5,
	SlotProp6,
	SlotProp7,
	SlotProp8,
	SlotProp9,
	SlotProp10,
	SlotProp11,
	SlotProp12,
	SlotProp13,
	SlotProp14,
	SlotProp15,
	SlotProp16,
	SlotProp17,
	SlotProp18,
	SlotProp19,
	SlotProp20,
	SlotProp21,
	SlotProp22,
	SlotProp23,
	SlotProp24,
	SlotProp25,
	SlotProp26,
	SlotProp27,
	SlotProp28,
	SlotProp29,
	SlotProp30,
	SlotProp31,
	SlotProp32,
	SlotProp33,
	SlotProp34,
	SlotProp35,
	SlotProp36,
	SlotProp37,
	SlotProp38,
	SlotProp39,
	SlotProp40,
	SlotProp41,
	SlotProp42,
	SlotProp43,
	SlotProp44,
	SlotProp45,
	SlotProp46,
	SlotProp47,
}

var _ = [1]struct{}{}[len(slotPropPrograms)-propspec.NumSlotPrograms]
