// Code generated by prop_table.sh. DO NOT EDIT.

package arm64lower

import "github.com/mmcloughlin/avo/tests/arm64lower/propspec"

// propPrograms indexes the generated Prop<n> functions so the test can drive
// them in a loop. avo's stub printer emits plain function declarations, so this
// table is the small amount of glue that turns them into a slice.
var propPrograms = [...]func(x, y uint64) uint64{
	Prop0,
	Prop1,
	Prop2,
	Prop3,
	Prop4,
	Prop5,
	Prop6,
	Prop7,
	Prop8,
	Prop9,
	Prop10,
	Prop11,
}

// Fails to compile if the table and propspec.NumPrograms drift apart.
var _ = [1]struct{}{}[len(propPrograms)-propspec.NumPrograms]

// memPropPrograms is the same glue for the memory-operand family.
var memPropPrograms = [...]func(x, y uint64, p *[8]uint64) uint64{
	MemProp0,
	MemProp1,
	MemProp2,
	MemProp3,
	MemProp4,
	MemProp5,
	MemProp6,
	MemProp7,
}

var _ = [1]struct{}{}[len(memPropPrograms)-propspec.NumMemPrograms]
