// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.

package arm64lower

func Add(x uint64, y uint64) uint64

func Sub(x uint64, y uint64) uint64

func Neg(x uint64) uint64

func AndOrXor(x uint64, y uint64) uint64

func ShlCL(x uint64, n uint64) uint64

func ShrCL(x uint64, n uint64) uint64

func RolCL(x uint64, n uint64) uint64

func ZeroExt32(x uint64) uint64

func HighByte(x uint64) uint64

func ShiftExtractByte64Lo(x uint64) uint64

func ShiftExtractByte64Mid(x uint64) uint64

func ShiftExtractByte64Hi(x uint64) uint64

func ShiftExtractByte32(x uint64) uint64

func LoadIdx(p *[8]uint64, i uint64) uint64

func Copy16(dst *[16]byte, src *[16]byte)

func Prefetch(p *[64]uint64, i uint64) uint64

func LessS(a uint64, b uint64) uint64

func GreaterEqS(a uint64, b uint64) uint64

func LessU(a uint64, b uint64) uint64

func AboveU(a uint64, b uint64) uint64

func Equal(a uint64, b uint64) uint64

func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64

func SubGapEq(x uint64, y uint64) uint64

func DecGapZero(x uint64, y uint64) uint64

func CmpL32Eq(a uint64, b uint64) uint64

func CmpL32LessS(a uint64, b uint64) uint64

func CmpL32LessU(a uint64, b uint64) uint64

func TestL32(a uint64, m uint64) uint64

func CmpW16Eq(a uint64, b uint64) uint64

func CmpB8Ne(a uint64, b uint64) uint64

func TestW16Eq(a uint64, m uint64) uint64

func IMul2(x uint64, y uint64) uint64

func IMul3(x uint64) uint64

func MulWide(x uint64, y uint64) (lo uint64, hi uint64)

func IMulWide(x int64, y int64) (lo uint64, hi uint64)

func MulX(x uint64, y uint64) (lo uint64, hi uint64)

func ShlX(x uint64, n uint64) uint64

func ShrX(x uint64, n uint64) uint64

func SarX(x uint64, n uint64) uint64

func RorX(x uint64) uint64

func Bzhi(x uint64, n uint64) uint64

func Bextr88(x uint64) uint64

func Bextr4_12(x uint64) uint64

func Bextr56_8(x uint64) uint64

func Bextr8_56(x uint64) uint64

func Bextr8_60(x uint64) uint64

func Bextr0_0(x uint64) uint64

func Bextr70_8(x uint64) uint64

func BzhiConst13(x uint64) uint64

func BzhiConst0(x uint64) uint64

func BzhiConst64(x uint64) uint64

func ShlXConst9(x uint64) uint64

func ShrXConst9(x uint64) uint64

func SetGe(a uint64, b uint64) uint64

func AdcAccum(x uint64, acc uint64) uint64

func BswapL(x uint64) uint64

func AddByte(x uint64, y uint64) uint64

func MovbHighDst(x uint64, y uint64) uint64

func MovbLowPreserve(x uint64, y uint64) uint64

func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64

func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64

func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64

func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64

func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64

func SelMi(a uint64, b uint64, c uint64, d uint64) uint64

func SelPl(a uint64, b uint64, c uint64, d uint64) uint64

func SxL(x uint64) uint64

func SxB(x uint64) uint64

func SxBL(x uint64) uint64

func SxWL(x uint64) uint64

func NegL(x uint64) uint64

func NotL(x uint64) uint64

func NotQ(x uint64) uint64

func RolL7(x uint64) uint64

func RorQ9(x uint64) uint64

func RorL9(x uint64) uint64

func BtrQ5(x uint64) uint64

func BtcQ5(x uint64) uint64

func PopcntQ(x uint64) uint64

func SarQ3(x uint64) uint64

func SarL3(x uint64) uint64

func IncL(x uint64) uint64

func ShlB2(x uint64) uint64

func BsfQ(x uint64) uint64

func TzcntQ(x uint64) uint64

func AddL(x uint64, y uint64) uint64

func SubL(x uint64, y uint64) uint64

func AndL(x uint64, y uint64) uint64

func OrL(x uint64, y uint64) uint64

func ImulL(x uint64, y uint64) uint64

func XchgQ(x uint64, y uint64) uint64

func LeaL(x uint64, y uint64) uint64

func VecZero(dst *[16]byte)

func VecCopyIdx(dst *[32]byte, src *[32]byte, i uint64)

func VecCopy(dst *[32]byte, src *[32]byte)

func Prop0(x uint64, y uint64) uint64

func Prop1(x uint64, y uint64) uint64

func Prop2(x uint64, y uint64) uint64

func Prop3(x uint64, y uint64) uint64

func Prop4(x uint64, y uint64) uint64

func Prop5(x uint64, y uint64) uint64

func Prop6(x uint64, y uint64) uint64

func Prop7(x uint64, y uint64) uint64

func Prop8(x uint64, y uint64) uint64

func Prop9(x uint64, y uint64) uint64

func Prop10(x uint64, y uint64) uint64

func Prop11(x uint64, y uint64) uint64

func MemProp0(x uint64, y uint64, p *[8]uint64) uint64

func MemProp1(x uint64, y uint64, p *[8]uint64) uint64

func MemProp2(x uint64, y uint64, p *[8]uint64) uint64

func MemProp3(x uint64, y uint64, p *[8]uint64) uint64

func MemProp4(x uint64, y uint64, p *[8]uint64) uint64

func MemProp5(x uint64, y uint64, p *[8]uint64) uint64

func MemProp6(x uint64, y uint64, p *[8]uint64) uint64

func MemProp7(x uint64, y uint64, p *[8]uint64) uint64

func BtBranch(x uint64) uint64

func BtBranchHigh(x uint64) uint64

func BtBranchClear(x uint64) uint64

func BtBranchClearHigh(x uint64) uint64

func MovwzxL(p *[4]uint16, i uint64) uint64

func MovbzxHigh(x uint64) uint64

func CmovL32(x uint64, y uint64) uint64

func BextrMem(p *[4]uint64, i uint64, ctrl uint64) uint64

func XorSelfEq(x uint64) uint64

func MovLNegImm() uint64

func IncLMem(p *[2]uint32)

func DecLMem(p *[2]uint32)

func IncQMem(p *[2]uint64)

func CmpBHigh(x uint64) uint64

func MovWLoad(x uint64, p *uint16) uint64

func MulXAlias(x uint64, y uint64) uint64

func TestQImm(x uint64, y uint64) uint64

func FlagsAcrossTransparent(a uint64, b uint64) uint64

func XorlSign(x uint64, y uint64) uint64

func XorlMem(p *[2]uint32, v uint64)

func BzhiConst256(x uint64) uint64

func BzhiConstNeg(x uint64) uint64

func AndQBit31(x uint64) uint64

func AddQBit31(x uint64) uint64

func OrQBit31(x uint64) uint64

func CmpQBit31(x uint64) uint64

func TestQBit31(x uint64) uint64

func MovQBit31Mem(p *uint64)

func MovQBit31Reg() uint64

func CmpLIntMin(x uint64) uint64

func ShrQ64(x uint64) uint64

func ShrQ65(x uint64) uint64

func ShlQ64(x uint64) uint64

func ShrL32(x uint64) uint64

func IncQ(x uint64) uint64

func DecL(x uint64) uint64

func ShrL5(x uint64) uint64

func SxWQ(x uint64) uint64

func BsrQ(x uint64) uint64

func BtsQ5(x uint64) uint64

func ZxLQ(p *uint64) uint64

func MovW(x uint64, y uint64) uint64

func LeaQ(x uint64, y uint64) uint64

func TestQZero(x uint64, y uint64) uint64

func TestBZero(x uint64, y uint64) uint64

func TestBSelfZero(x uint64) uint64

func TestWSelfZero(x uint64) uint64

func VecCopyReg(dst *[16]byte, src *[16]byte)

func SetAll(a uint64, b uint64) uint64

func JmpAll(a uint64, b uint64) uint64

func CmovAll(a uint64, b uint64) uint64

func ShlCountFold(x uint64, n uint64) uint64

func ShrCountFold32(x uint64, n uint64) uint64

func RolCountFold(x uint64, n uint64) uint64

func CountFoldRefusedRead(x uint64, n uint64) uint64

func ShlCountSelf(n uint64) uint64

func SarCopyFold(x uint64) uint64

func ShlCopyFoldCX(x uint64) uint64

func AdcAccumQ(x uint64, acc uint64) uint64

func SetGeZeroMov(a uint64, b uint64) uint64

func SetGeRefusedRead(a uint64, b uint64) uint64
