name: bot
permissions:
  contents: read
on:
  pull_request:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bot Token
        uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe # v1.5.2
        id: bot
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Get Bot User
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.bot.outputs.token }}
          script: |
            github.rest.users.getAuthenticated();
