name: bot
permissions:
  contents: read
on:
  pull_request:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Bot User
        id: bot-user
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.users.getByUsername({username: 'cadobot[bot]'});
            for (const [key, value] in Object.entries(res.data)) {
              core.setOutput(key, value)
            }
      - name: Report
        run: |
          echo "${{ steps.bot-user.outputs.login }}"
          echo "${{ steps.bot-user.outputs.id }}"
