name: metadata
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "24 5 1 * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.27.x
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Update Package Metadata
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./script/metadata
      - name: Diff
        run: git diff
      - name: Generate
        run: ./script/generate
      - name: Diff
        run: git diff
      - name: Create Pull Request
        uses: ./.github/actions/create-pull-request
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          branch: auto-tests-thirdparty-update-metadata
          title: "tests/thirdparty: update package metadata"
          body: "Auto-generated update of third-party package metadata."
