name: pr
permissions:
  contents: read
on:
  pull_request:
jobs:
  automerge:
    if: github.actor == 'cadobot[bot]' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bot Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: bot
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Automerge Bot Pull Requests
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
