name: pr
permissions:
  contents: read
on:
  pull_request:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bot Token
        uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe # v1.5.2
        id: bot
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Automerge Bot Pull Requests
        if: github.actor == 'cadobot[bot]' && !github.event.pull_request.draft
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Generate
        run: |
          date > report.txt
          git add report.txt
      - name: Create Pull Request
        uses: ./.github/actions/create-pull-request
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          branch: auto-test-create-pull-request
          title: "ci: test create-pull-request action"
          body: "Test for `create-pull-request` action."
