name: stress
permissions:
  contents: read
on:
  schedule:
    - cron: "33 3 * * 6"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -tags=stress
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.x
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Generate
        run: ./script/generate
      - name: Status
        run: git status
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -bench . ./...
      - name: Coverage
        run: ./script/coverage
      - name: Upload Stress Unit Test Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: unittests.coverprofile
          flags: stress
